src/components/Masthead/Masthead.stories.tsx, src/components/Masthead/Masthead.tsx, src/components/Masthead/index.ts
References:
- HTML code: https://github.com/GovTechSG/sgds-web-component/blob/master/src/components/Masthead/sgds-masthead.ts
- CSS properties: https://github.com/GovTechSG/sgds-web-component/blob/master/src/components/Masthead/sgds-masthead.scss
=> feat: add Government masthead component

src/templates/next/components/KeyStatistics/KeyStatistics.tsx
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: use set colours instead of hardcoding

src/templates/next/components/Infobar/Infobar.tsx
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: use new button in infobar

src/common/Button.ts, src/engine/render.tsx, src/templates/next/components/Button/Button.tsx
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: allow overriding link component in Button

src/templates/next/components/Button/Button.stories.tsx, src/templates/next/components/Button/Button.tsx, src/templates/next/components/Hero/Hero.tsx, src/templates/next/components/Infobar/Infobar.tsx
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: colors in button

src/common/Navbar.ts, src/common/OrderedList.ts, src/presets/next.js, src/templates/next/components/Navbar/Navbar.stories.tsx, src/templates/next/components/Navbar/Navbar.tsx, src/templates/next/layouts/Skeleton/Skeleton.tsx, src/templates/next/layouts/render.tsx, tsconfig.json
Figma: https://www.figma.com/file/8TEzSSDbx97gctRJ7nKdqG/Website-Template-Gen-2?type=design&node-id=1811-9913&mode=dev
Note:
- There is no animation currently except for hovering, so the navbar items will appear immediately instead of easing in. Deprioritising building that animation first.
- Also adjusted the orderedlist prop such that the `start` prop is optional.
=> feat: introduce navbar component

schema/CNAME, schema/next/0.1.0.json, schema/next/samples/about.json, schema/next/samples/index.json, src/common/Footer.ts, src/engine/types.ts, src/templates/classic/components/Footer/Footer.tsx, src/templates/next/layouts/Skeleton/Skeleton.tsx, src/templates/next/layouts/render.tsx
Some props were updated, and let's consolidate the schema in one branch for easier update/visibility.
=> feat: update props and add schema

src/templates/next/components/Image/Image.stories.tsx, src/templates/next/components/Image/Image.tsx, src/templates/next/components/Image/index.ts
=> feat(img): add img component

src/common/Accordion.ts, src/common/index.ts, src/engine/types.ts, src/templates/next/components/Accordion/Accordion.stories.tsx, src/templates/next/components/Accordion/Accordion.tsx, src/templates/next/components/Accordion/index.ts, src/templates/next/components/index.ts, src/templates/next/layouts/render.tsx
Figma: https://www.figma.com/file/8TEzSSDbx97gctRJ7nKdqG/Website-Template-Gen-2?type=design&node-id=2446-7719&mode=design&t=Bg5JItUHey5WDA3K-4
=> feat: introduce accordion for next theme

docs/next/0.1.0.json
=> chore: update schema to split native and complex components

src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx, src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Closes ISOM-966.
Design to confirm:
=> fix: design fixes for keystatistics component

src/interfaces/internal/Masthead.ts, src/presets/next.ts, src/templates/next/components/internal/Masthead/Masthead.tsx, src/templates/next/components/internal/Navbar/Navbar.stories.tsx, src/templates/next/components/internal/Navbar/Navbar.tsx, src/templates/next/layouts/Article/Article.tsx, src/templates/next/layouts/Collection/CollectionClient.tsx, src/templates/next/layouts/Content/Content.tsx, src/templates/next/layouts/Homepage/Homepage.stories.tsx, src/templates/next/layouts/Homepage/Homepage.tsx, src/templates/next/layouts/NotFound/NotFound.tsx, src/templates/next/render/render.tsx
Closes ISOM-960.
Closes ISOM-961.
=> fix: design for navbar and masthead

src/interfaces/native/Text.ts, src/templates/next/components/internal/Notification/Notification.tsx, src/templates/next/components/native/Prose/Prose.tsx, src/templates/next/components/native/Table/Table.stories.tsx, src/templates/next/components/native/Table/Table.tsx, src/utils/getTextAsHtml.ts
Split from #74, only for table component.
Fixes ISOM-964.
=> fix: design fixes for table component

src/templates/next/components/complex/Accordion/Accordion.tsx
Resolves [ISOM-965](https://linear.app/ogp/issue/ISOM-956/accordion-design-review)
=> chore(accordion): styling fixes

src/templates/next/components/complex/InfoCols/InfoCols.tsx
Resolves [ISOM-965](https://linear.app/ogp/issue/ISOM-965/infocol-design-review)
=> chore(infocols): design review

src/templates/next/components/complex/Hero/Hero.tsx
As described in the ticket [here](https://linear.app/ogp/issue/ISOM-965/infocol-design-review)
=> fix(hero): stlying changes for hero

packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
Design fixes for Navbar component. Only desktop view is affected.
Note:
- The text colours are hard-coded for now, as no design tokens have been allocated yet. It is still subject to future change.
Figma: https://www.figma.com/design/8TEzSSDbx97gctRJ7nKdqG/Website-Template-Gen-2?node-id=4488-9936&t=RQmuT8l6myyX12S7-4
=> fix: design fixes for navbar component

packages/components/src/templates/next/components/native/Table/Table.tsx
Minor design updates for table:
- Header row text is left-aligned
- Header row text has smaller font size
=> fix(style): design fixes for table

packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
- Megamenu style fixes
- Mobile menu style fixes
=> fix(styling): navbar design fixes

packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.tsx, packages/components/src/templates/next/components/internal/TableOfContents/TableOfContents.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx, packages/components/tailwind.config.js
Design fixes for content page and ToC
- Add max width for content page header for scannability
- Remove fixed width for ToC
- Add colors to content page header
=> fix(style): content page and ToC styling updates

apps/studio/package.json, package-lock.json, packages/studio/package-lock.json, tooling/template/package.json
https://www.notion.so/opengov/Snyk-reviews-252f290d93524e7e916503719f04e78d?pvs=4
Our deps are out of date, need to update deps to fix
up deps
=> fix(snyk): update packages

packages/components/src/templates/next/components/complex/Hero/Hero.tsx
Design fixes to hero banner
- Middle align text for better balance
- Thicker font weight for heading
- Darker gradient for better contrast
=> fix(styling): hero design fixes

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20240624071353_update_to_blob/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/resource/resource.types.ts
see [here](https://opengovproducts.slack.com/archives/C06R4DX966P/p1719212071025839)
- shift out the table's properties to a jsonb
- not reusing the existing `Blob` table because the mental model is that db table map to to a specific isomer schema
=> chore: migrate schema

.github/workflows/mergify.yml
Add mergify so deps don't pile
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore: mergify

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20240624130652_/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/src/schemas/folder.ts, apps/studio/src/schemas/page.ts, apps/studio/src/schemas/site.ts, apps/studio/src/server/modules/_app.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.types.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/src/server/modules/site/site.types.ts
At present, we have some type mismatches and also, we have implemented methods to get data from db but no actual data + connection yet. 
Seed the db with data
=> feat(db): seed db

apps/studio/prisma/seed.ts, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/schemas/folder.ts, apps/studio/src/schemas/page.ts, apps/studio/src/schemas/site.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/resource/resource.types.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/src/server/modules/site/site.types.ts
Previously, our data was hardcoded on the frontend. now, we will dynamically get it out from our backend and feed it into the `Preview`
- refer to all ids as `number` 
- update seed script to seed db with some mock data 
- retrieve data from db using trpc
=> feat(preview): connect preview to db

apps/studio/src/features/editing-experience/components/LayoutSelection.stories.tsx, apps/studio/src/features/editing-experience/data/articleLayoutPreview.json, apps/studio/src/features/editing-experience/data/contentLayoutPreview.json, apps/studio/src/server/trpc.ts, apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/msw/handlers/site.ts
The placeholder schemas were not updated originally after the Isomer JSON schema was updated. Formatting is also broken.
**Bug Fixes**:
- Upgraded the placeholder schemas
- Formatted the monorepo
=> chore: update placeholder schemas and fix format

apps/studio/src/pages/sites/[siteId]/index.tsx
This pull request enhances the user interface of the Site Page by introducing a dropdown menu. The menu includes options to create folders, pages, and collections, improving the user experience. Refactoring involved importing new icons and components, and correcting a minor typo in variable naming.
=> feat: move create resource options to menu

apps/studio/prisma/seed.ts
Add conflict handling logic to the Prisma seed script to avoid duplication errors.
This PR introduces the `.onConflict` method to various database insertions in `apps/studio/prisma/seed.ts` to handle conflicts by updating existing records instead of throwing errors. Additionally, it includes deduplication logic for the `Blob` table, checking if a blob already exists before attempting to insert a new one.
1. Run the Prisma seed script: `npx prisma db seed`
2. Verify that no duplication errors occur during the seeding process.
3. Check the database to ensure that records are correctly updated in case of conflicts.
This change is necessary to prevent duplication errors during the seeding process, ensuring a smoother development and deployment workflow.
=> feat: add conflict handling in prisma seed script

packages/components/src/templates/next/components/complex/Callout/Callout.tsx
- Updated text style to use new typography tokens
- Minor spacing changes  
- Replaced TailwindCSS utility colours with new semantic colour tokens
=> fix: update styles for Callout component

packages/components/src/templates/next/components/internal/Footer/Footer.tsx
- Updated typography and semantic colour tokens
- Updated padding for mobile and tablet breakpoints
=> feat: refactor footer styling for isomer package

apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: errorneous string cast

apps/studio/package.json, package-lock.json, packages/components/.storybook/main.ts, packages/components/.storybook/preview.ts, packages/components/package.json, packages/components/src/presets/next/colors.ts, packages/components/src/templates/next/components/internal/Navbar/HamburgerIcon.tsx, packages/components/src/templates/next/components/internal/Navbar/MobileNavItemAccordion.tsx, packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, tooling/storybook/index.ts, tooling/storybook/modes.ts, tooling/storybook/viewports.ts
Schema props have not been changed. Just behaviour.
- Upgraded `usehooks-ts` from 2.9.2 to 3.1.0
- Add new packages for easier declaration of tailwind classes (`tailwind-merge`, `tailwind-variants`)
- Add new `react-aria` package for accessibility and UX
New stories for `Navbar` is added for the various states
=> feat: update Navbar component to fit design

package-lock.json, packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx
- Update typography and semantic colour tokens
- Changed underline offset to not cut off at descenders
- Changed chevron to smaller size
=> fix: update Breadcrumb component to new design

packages/components/src/templates/next/components/complex/Infobar/Infobar.tsx
- Update typography and semantic colour tokens
- Updated padding / margin for block
- Updated button spacing
Need to update button styles after variants are in
Reference: [Figma design](https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/(New%2C-WIP)-Isomer-Next-Component-Library?node-id=1-18&m=dev)
=> fix: update Infobar component

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts
CI/CD not flagging on lint/format issues on prisma migrations because of turbo's build pipeline :(
Quick fix before I devote more time into correcting that pipeline
=> fix: lint and format

packages/components/src/presets/next/colors.ts
Adding new hyperlink colours
- [Explorations on Figma](https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/(New%2C-WIP)-Isomer-Next-Component-Library?node-id=3988-9354)
- Not using "visited" anymore
=> ISOM1305: Add hyperlink colours to tokens

packages/components/src/templates/next/components/complex/Hero/Hero.tsx
- Apply tokens to hero banner
- Adjust min height and y-padding
- Adjust button gaps and wrapping behaviour
- Adjust gradient for better contrast in middle breakpoints
=> feat(components): Hero banner tokens and styling

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx, packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
- Apply type and colour tokens
- Fix spacing to match Figma
- Change text alignment to left
=> fix(component): Statistics styling changes

apps/studio/src/components/Datatable/Datatable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx, package-lock.json
update to hoveer styling
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: table link

apps/studio/package.json, apps/studio/src/schemas/url.ts, apps/studio/src/server/modules/auth/sgid/sgid.router.ts, package-lock.json, package.json
See [thread](https://opengovproducts.slack.com/archives/CK9GGK6EP/p1722841650033399). This PR modifies our redirect url validation.
=> feat: use starter-kitty for redirect validator

packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/CollectionCard/index.ts, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
Update `CollectionCard` to new styling
- Simplified `CollectionCard` component props
- Unified `ArticleCard` and `FileCard` under the `CollectionCard` component
- Updated the component to use `react-aria-components` for accessibility features
- Added Chromatic modes for visual regression testing (`desktop`, `mobile`)
- Adjusted image and text layout for better responsiveness
1. Run the storybook and verify the `CollectionCard` renders correctly in all Chromatic modes
2. Verify the layout and accessibility features of the `CollectionCard` component
3. Check that the prop changes do not introduce any regressions
Sync with design
=> feat: update CollectionCard to new styling

packages/components/src/templates/next/components/native/Table/Table.stories.tsx, packages/components/src/templates/next/components/native/Table/Table.tsx
Updated table styling for improved visual consistency and border handling.
- Updated row and cell border styles to ensure consistent appearance
- Removed redundant border declarations on individual cells
- Adjusted CSS classes for better border visibility and alignment
1. Navigate to a page containing tables
2. Verify that table borders are consistent
3. Check that rows and cells have visible borders
4. Ensure table content alignment and spacing remain correct
5. Test responsiveness and overflow behavior on different screen sizes
This change improves the visual consistency of tables across the application. By updating border styles, we ensure a more uniform appearance and eliminate potential gaps or inconsistencies in table layouts. This enhancement contributes to a more polished and …
=> fix(components): double borders when having nested tables

packages/components/.storybook/preview.ts, packages/components/src/presets/next/index.ts, packages/components/src/templates/next/components/internal/Button/Button.tsx, packages/components/src/templates/next/components/internal/Checkbox/Checkbox.stories.tsx, packages/components/src/templates/next/components/internal/Checkbox/Checkbox.tsx, packages/components/src/templates/next/components/internal/Filter/Filter.stories.tsx, packages/components/src/templates/next/components/internal/Filter/Filter.tsx, packages/components/src/templates/next/components/internal/Filter/FilterDrawer.tsx, packages/components/src/templates/next/components/internal/Search.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Collection/CollectionPageHeader.tsx, packages/components/src/templates/next/layouts/Collection/useCollection.ts, packages/components/src/templates/next/types/Filter.ts
This PR adds a mobile specific drawer to the collections page
=> feat: add mobile specific filter drawer to collections page

packages/components/src/templates/next/layouts/Content/Content.tsx
Also generate all siderail children for non-current links.
=> feat: generate all siderail children at once

packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx
Also closes ISOM-1324
Replaced FocusScope with Dialog component for improved accessibility in the NavItem megamenu.
Also fixes stacking issues with other components.
- Replaced `FocusScope` from react-aria with `Dialog` from @headlessui/react in the NavItem component.
- Removed the overlay div from the Navbar component.
- Added a background overlay to the Dialog component.
- Updated the NavbarItemProps interface to include new properties for the Dialog component.
1. Navigate to the Collection story in Storybook.
2. Interact with the navbar items to open and close the megamenu.
3. Verify that the megamenu opens and closes correctly.
4. Check that focus management and keyboard navigation work as expected within the megamenu.
5. Ensure the background overlay appears when the megamenu is …
=> fix: render navbar megamenu in a portal

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/components/CmsSidebar/CmsSidebarContainer.tsx, apps/studio/src/components/Datatable/EmptyTablePlaceholder.tsx, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/src/stories/Page/SitePage.stories.tsx, apps/studio/tests/msw/handlers/page.ts
Improved CMS sidebar navigation, updated empty state messages, and enhanced folder and page management functionality.
- Updated icon mappings in CmsSideNav component to use Icon component
- Enhanced EmptyTablePlaceholder to display different messages based on context
- Modified CollectionTable and ResourceTable to include group labels
- Updated FolderSettingsModal toast messages for better clarity
- Improved MoveResourceModal to filter out non-folder items
- Updated FolderPage to use dynamic links instead of permalinks
- Added lastUpdated field to default page creation in page service
1. Navigate through the CMS sidebar and verify icon display
2. Check empty state messages in collection and resource tables
3. Create and update folders, verifying toast messages
4. Attempt to move resources …
=> fix(uat): UI + functionality fixes

apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx
Update entity name from `x` to collection page/page respectively.
=> chore: fix entity name

.aws/deploy/task-definition.json
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: env vars

.aws/deploy/task-definition.json, .env.example, .env.test, apps/studio/next.config.mjs, apps/studio/src/env.mjs, apps/studio/src/hooks/useUploadAssetMutation.ts, apps/studio/src/lib/s3.ts, apps/studio/src/server/modules/asset/asset.service.ts, turbo.json
The assets bucket name and S3 region is not public, which means our CSP rules is set to undefined.
**Bug Fixes**:
- Prefix both environment variables with `NEXT_PUBLIC_`.
=> fix: make assets bucket name public

package-lock.json, packages/components/package.json, packages/components/src/templates/next/components/internal/IconButton/IconButton.tsx, packages/components/src/templates/next/components/internal/Navbar/MobileNavMenu/MobileNavbarMenu.tsx, packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
Improved accessibility and user experience of the Navbar component by implementing focus management and enhancing mobile navigation.
- Added `react-focus-on` library to manage focus within the mobile navigation menu and mega menu.
- Updated the MobileNavMenu to use FocusOn component for better keyboard navigation.
- Replaced Dialog component with a custom implementation using FocusOn in the NavItem component.
- Adjusted the IconButton component styles for better alignment and consistency.
- Implemented smooth scrolling when opening navigation items on desktop.
- Refined the mobile navigation menu's positioning and overlay.
1. Open the application and navigate to a page with the Navbar component.
2. Test keyboard navigation in both desktop and mobile views:
- Tab through menu items and …
=> feat(components): fix issues with mobile navbar due to incorrect focus lock

tooling/build/scripts/publisher.sh, tooling/build/scripts/publishing/index.ts, tooling/build/scripts/publishing/queries.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: reconstruct publishing script from DB

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx
1. colours out of sync
2. title not overflowing
3. wrong icon
4. `p` component instead of `h3`
5. no chevron for button
Closes ISOM-1346 
Closes ISOM-1343
Closes ISOM-1351
Closes ISOM-1347
Closes ISOM-1354
mostly minor UI updates + style changes.
for chevron, use the menu exports from design system rather than the chakra one
=> fix(style): minor UI fixes for site content

apps/studio/src/features/editing-experience/components/Preview.tsx
last updated shows invalid date
add it to the `page` props being set above
=> fix: last updated

apps/studio/src/components/CmsSidebar/CmsSidebarOnlyContainer.tsx, apps/studio/src/components/CmsSidebar/index.tsx, apps/studio/src/pages/sites/[siteId]/settings.tsx, apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/src/templates/layouts/AdminSidebarOnlyLayout.tsx
Update the settings page to fit design
Closes ISOM-1359
1. minor misc fixes involving design
2. create a new layout that omits the side nav for the settings page
3. update button logic for settings page 
- opted to create a new layout rather than adding a new `prop`. i think having abit of repetition here in exchange for clear roles and not exploding the container component is something that i feel is worth it. the additional clarity i feel is worth the xtra code
=> chore: update mt

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx
Added active state to sidebar navigation and implemented query parsing for resource identification.
- Introduced `useQueryParse` hook and `siteSchema` for parsing URL parameters
- Added `getCurResource` function to determine the current active resource
- Implemented active state for sidebar navigation items
- Integrated `z` (Zod) for schema validation
1. Navigate to different pages within the CMS (root page, folder, collection)
2. Verify that the corresponding sidebar item is highlighted as active
3. Check that the active state updates correctly when switching between resources
This change improves the user experience by providing visual feedback on the current location within the CMS. It helps users easily identify which resource they are currently viewing or editing, enhancing …
=> feat: update accordion to be active when it's the active route

packages/components/src/templates/next/components/internal/Filter/Filter.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx, packages/components/src/templates/next/layouts/Collection/useCollection.ts, packages/components/src/templates/next/layouts/Collection/utils.ts
Enhanced the Collection component to handle empty states and improve filter functionality.
- Added conditional rendering for the "Filter results" button based on the presence of filters
- Implemented a new message for collections with no items
- Created a new `CollectionResults` component to handle various result states
- Updated the filter logic to remove filters with no items
- Improved the display of search results and filter counts
- Added new stories for empty collections and no search results
Bunch of new stories to cover the requirements
These changes improve the user experience by providing clear feedback when there are no items or search results in a collection. The enhanced filter functionality ensures that users only see relevant filter options, reducing confusion and improving …
=> feat: improve Collection layout for empty states and no filters

packages/components/src/templates/next/components/internal/Masthead/Masthead.stories.tsx, packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx
Refactored the Masthead component to improve accessibility, responsiveness, and code organization.
- Restructured the Masthead component into smaller, reusable sub-components
- Implemented a context provider for better state management
- Enhanced accessibility with proper ARIA attributes and roles
- Improved responsive design for both mobile and desktop views
- Added new story for expanded state in Storybook
- Integrated react-aria-components for better accessibility support
- Updated styling using the `tv` utility for more consistent and maintainable styles
1. Run the Storybook and navigate to the Masthead component
2. Test the component in both mobile and desktop viewports
3. Verify that the "How to identify" button expands/collapses the content correctly
4. Check accessibility using …
=> feat(Masthead): refactor and enhance accessibility

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/features/preview/hooks/useSiteThemeCssVars.ts, packages/components/src/types/site.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: expected shape for the site theme colours

apps/studio/tests/msw/handlers/sites.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> chore: fix shape of site theme

packages/components/src/templates/next/components/internal/Link/Link.tsx, packages/components/src/templates/next/components/internal/Navbar/MobileNavMenu/MobileNavItemAccordion.tsx, packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx
Added support for external links in the Navbar component with visual indicators.
- Modified the `Link` component to handle external links with optional icon
- Updated `MobileNavItemAccordion` and `NavItem` components to use the enhanced `Link` component
- Added logic to detect and handle external URLs
- Included a new external link example in the Navbar stories
1. Navigate to the Navbar component in the storybook
2. Verify that external links open in a new tab
3. Check for the presence of external link icons in both desktop and mobile views
4. Ensure internal links behave as before
5. Test the new "External Link" item in the Navbar stories
This change improves user experience by clearly distinguishing between internal and external links in the navigation. It also enhances security by …
=> feat: add external link support to Navbar components

tooling/build/scripts/publishing/index.ts
The shape of theme got desynced again
**Bug Fixes**:
- Fix shape in publishing script.
=> fix: shape of site config for theme

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
Design wants to use a skeleton for loading state and not a spiner
Closes ISOM-1426
- Swap to skeleton.
- have to use 2 separate skeletons because initially `page` is potentially undefined. 
- i used the base homepage button to calculate a nice looking skeleton for the initial one.
No ss/vid cos i couldn't get the load in for the second skeleton. can try on `uat` or `main` if possible
=> refactor: change to skeleton

tooling/build/scripts/publishing/index.ts
duplicate of https://github.com/opengovsg/isomer/pull/508 into `main`
=> fix(publishing): update write logic

apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx
breadcrumbs had the wrong styling before
add text component and use the correct `textStyle`
=> fix: breadcrumbs styling

apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts, package-lock.json, packages/components/package.json, packages/components/src/interfaces/internal/Notification.ts, packages/components/src/templates/next/components/internal/Link/Link.tsx, packages/components/src/templates/next/components/internal/Notification/Notification.stories.tsx, packages/components/src/templates/next/components/internal/Notification/Notification.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx, packages/components/src/types/site.ts
Updated the Notification component, improved Link styling, and adjusted Navbar responsiveness.
- Updated `markdown-to-jsx` dependency to version 7.5.0
- Enhanced Link component styling with improved focus and hover states
- Adjusted Navbar responsiveness for medium-sized screens
- Redesigned Notification component with Markdown support and improved layout
- Added new stories for Notification component
- Integrated Notification component into the Skeleton layout
1. Check the updated Link styling for focus and hover states
2. Verify Navbar responsiveness on medium-sized screens
3. Test the new Notification component with various content types (short text, long text, with title)
4. Ensure the Notification component renders correctly in the Skeleton layout
5. Verify external links in the …
=> feat: enhance Notification component and update Link styles

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx
see ticket
1. remove the `useEffect` that does the auto generation so that it'll fallback to using the actual url.
=> fix: remove autogeneration of url on folder settings

apps/studio/src/server/modules/resource/resource.router.ts
See ticket for a description and video fo the problem
1. add a `where` clause on the query for the `siteId`.
=> fix: make sure that we get resources only from single site

packages/components/.storybook/preview.tsx, packages/components/tailwind.config.ts, tooling/template/app/[[...permalink]]/page.tsx, tooling/template/app/layout.tsx
Added `antialiased` tailwind class to improve text rendering and updated Storybook configuration.
- Added an antialiased class to the body element in the root layout.
- Created a LayoutDecorator for Storybook to apply the antialiased class.
- Updated Tailwind configuration to include Storybook files in the content array.
- Removed unnecessary fragment in the Page component.
- Updated generateMetadata function parameter name.
1. Run the application and verify that text rendering is smoother across all pages.
2. Launch Storybook and confirm that components are displayed with antialiased text.
3. Check that Tailwind styles are correctly applied to Storybook components.
The antialiased class improves text rendering, making it smoother and more readable across different browsers and devices. …
=> feat: add antialiased class to template layout, component stories

apps/studio/.devcontainer/devcontainer.json, apps/studio/.storybook/preview.tsx, apps/studio/README.md, apps/studio/src/env.mjs, apps/studio/src/features/landing/components/AppPublicHeader.tsx
Renamed "Starter Kit" to "Isomer Studio" across the project.
- Updated the app name from "Starter Kit" to "Isomer Studio" in various files:
- DevContainer configuration
- Storybook preview
- README.md
- Environment variables
- Landing page header
- Added a reference to Starter Kit in the README.md file
1. Check the DevContainer name in `.devcontainer/devcontainer.json`
2. Run Storybook and verify the app name in the preview
3. Review the README.md file for updated content
4. Verify the default app name in `src/env.mjs`
5. Run the application and check the landing page header
This change establishes "Isomer Studio" as the distinct identity for the project while acknowledging its foundation in the Starter Kit. It ensures consistency across the codebase and user-facing elements, providing a …
=> update occurrences of starter kit

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/Drawer/DrawerHeader.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/DraggableDrawerButton.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAccordionTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAllOfControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsCalloutTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsDropdownControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsIntegerControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsRadioControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsGroupLayout.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsVerticalLayout.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx
Closes ISOM-1517
Enhanced the editing experience with improved UI components and layout adjustments.
- Updated padding and spacing in various components for better visual consistency
- Improved the ComplexEditorNestedDrawer with a new layout and navigation buttons
- Refined the DrawerHeader component to be more flexible
- Removed duplicate renderer in FormBuilder
- Adjusted styling and layout of form controls and layouts
- Changed "Save changes" button text to "Save block"
1. Open the editing experience in the studio
2. Navigate through different form components and nested drawers
3. Verify the updated layout, spacing, and navigation controls
4. Test the functionality of the new "Previous" and "Next" buttons in nested drawers
5. Confirm that the "Save block" button appears correctly
These …
=> feat: improve form builder UI and array control navigation

.github/workflows/deploy_production.yml
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: add needs

.aws/deploy/task-definition.json, .env.example, apps/studio/.gitignore, apps/studio/package.json, apps/studio/src/env.mjs, apps/studio/src/server/context.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/trpc.ts, apps/studio/tests/integration/helpers/growthbook/mockFeatureFlags.ts, apps/studio/tests/integration/helpers/growthbook/mockInstance.ts, apps/studio/tests/integration/helpers/iron-session.ts, package-lock.json
Integrated GrowthBook for feature flagging and user whitelisting.
- Added GrowthBook client key to environment variables and task definition
- Implemented GrowthBook context in the server
- Added user whitelisting checks in authentication and authorization processes
- Updated .gitignore to exclude .ssh directory
1. Set up a GrowthBook account and obtain a client key
2. Add the client key to your environment variables
3. Create a feature flag named "whitelisted_users" in GrowthBook with a whitelist of email addresses
4. Attempt to log in with both whitelisted and non-whitelisted email addresses
5. Verify that only whitelisted users can access the application
This change introduces feature flagging capabilities and user whitelisting, allowing for controlled access to the application. It …
=> Add Growthbook integration and user whitelist

packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx
format check is failing on all branches since #637. This PR fixes the format error.
=> fix(components): run format

packages/components/src/templates/next/layouts/NotFound/NotFound.tsx
Edit copy to be more suitable for public-facing sites:
=> [Template] Edit copy for 404 page

apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/src/stories/Page/LandingPage.stories.ts
Stories died in the single day Chromatic CLI was broken. Very sad.
=> fix: fix broken stories due to missing msw handlers

packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
Previously, logo spacing was too tight
- Change logo sizing and spacing 
- Add realistic test cases
=> feat(components): return navbar spacing and logo sizing back to original

packages/components/src/templates/next/components/native/Table/Table.tsx
@sehyunidaaa relented and agreed that having sticky table headers may be confusing on tables that span different columns. Thus we are removing the sticky columns.
This PR simplifies the Table component by removing overflow detection and sticky row functionality. 
- Simplified Table component by removing complex logic for overflow detection and sticky rows
- Updated table styling for a more consistent appearance across all cells
- Removed unused imports and state management
**Bug Fixes**:
- Addressed potential issues with sticky positioning and overflow detection in varying screen sizes
Storybook
- Test table rendering with various content types (text, lists, paragraphs)
- Verify table appearance and consistency across different screen sizes
- Ensure table accessibility …
=> feat(components): remove sticky table columns

apps/studio/package.json, apps/studio/public/assets/css/preview-tw.css, apps/studio/turbo.json, packages/components/turbo.json, turbo.json
- Removed unnecessary generate and prebuild scripts from package.json
- Updated turbo.json configurations for better build dependencies and task management
- Refined CSS classes and styles in preview-tw.css
**Bug Fixes**:
- Fixed inconsistencies in container styles and responsive breakpoints
=> chore: update build dependencies and optimize studio scripts

apps/studio/src/server/trpc.ts
previously our email check was case sensitive, which led to validation failing when the users input an upper cased character
lowercase the email so that we perform an unconditional check. ~do note that this assumes the email stored in grwoth book is also lowercased, other wise this comparison will no longer be valid~
=> fix: email checking

apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx
our preview doenst update in resopnse to user input.
set the user input to the correct key for merging
=> fix: page title in preview

apps/studio/prisma/seed.ts
as per title
copy over theme from db
=> chore: update seed script to insert theme

apps/studio/src/components/PageEditor/constants.ts, packages/components/src/interfaces/complex/Infobar.ts, packages/components/src/interfaces/internal/Footer.ts, packages/components/src/templates/next/components/complex/Contentpic/Contentpic.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.stories.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.tsx
We need a WhatsApp social media link.
**Features**:
- Add support for WhatsApp.
**Bug Fixes**:
- Fixed copy for infocards title.
- Fixed max length for button URL on hero banner.
- Break words on content pic component.
=> feat: add whatsapp social media link

.env.example
`NEXT_PUBLIC_APP_ENV` not added to .env which lead to error since it's a required env
=> add NEXT_PUBLIC_APP_ENV to .env.example

apps/studio/prisma/seed.ts
`ResourcePermission` not seeded causing issue
- Details ...
**Features**:
- seed `ResourcePermission`
- add `editor` and `publisher` seed account too
=> Add resource permission to seed

.aws/deploy/task-definition.json
our task definition has the wrong values set for dd keys
update tsak def
=> fix: update dd env and service

.aws/deploy/task-definition.json
dd tags need to be separated by space
add space
=> chore: fix tags

tooling/template/next.config.mjs
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> fix: add key for 

apps/studio/src/instrumentation.ts, apps/studio/src/server/modules/_app.ts
nextjs has a special file, `instrumentation.ts` that we need to use to setup instrumentation. 
add this file and initialise the tracer there
=> fix: instrumentation

apps/studio/src/server/modules/permissions/__tests__/permissions.service.test.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/permissions/permissions.util.ts, apps/studio/tests/integration/helpers/seed/index.ts
Currently values are hardcoded
- Details ...
- single source of truth by importing them everywhere instead of hardcoding values
=> replace with RoleType for SSOT

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/components/ResourceSelector/ResourceItem.tsx, apps/studio/src/components/ResourceSelector/ResourceSelector.tsx, apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebar.tsx, apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebarContent.tsx, apps/studio/src/features/dashboard/components/DirectorySidebar/useIsActive.ts, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx, apps/studio/src/features/editing-experience/components/EditLinkPreview.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/pages/sites/[siteId]/settings.tsx, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/utils/resource.ts, apps/studio/src/utils/sitemap.ts, apps/studio/tests/integration/helpers/seed/index.ts
Currently values are hardcoded
- Details ...
- single source of truth by importing them everywhere instead of hardcoding values
=> replace with ResourceType for SSOT

apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/DetailsScreen.tsx
1. styling in create colleciton item and create page (in folder) is different due to the padding
1. remove extra paddings
**fixed**
**old**
=> chore: fix styling

apps/studio/prisma/constants.ts, apps/studio/prisma/scripts/README.md, apps/studio/prisma/scripts/addUsersToSite.ts, apps/studio/prisma/scripts/createSite.ts, apps/studio/prisma/scripts/updateAllUserPermissionsForSite.ts, apps/studio/prisma/scripts/updateUserPermissions.ts, apps/studio/prisma/seed.ts
Right now, we often have to whitelist/create site/update user permissions. This PR adds these 3 common functionality in via db scripts
1. use kysely and write common scripts 
2. add simple readme for usage
=> chore(scripts): add db scripts for common tasks

apps/studio/prisma/constants.ts, apps/studio/prisma/scripts/README.md, apps/studio/prisma/scripts/addUsersToSite.ts, apps/studio/prisma/scripts/createSite.ts
Minor changes to DB scripts and improve readme
=> update readme and logs for scripts

apps/studio/next.config.mjs
we previously removed the hook by accident, leading to a loss in instrumentation :sadge:
1. add the hoook back with docs
=> chore: fix instrumentation

apps/studio/next.config.mjs, apps/studio/public/assets/css/preview-tw.css, apps/studio/src/components/PageEditor/constants.ts, package-lock.json, packages/components/package.json, packages/components/src/interfaces/complex/DynamicDataBanner.ts, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.stories.tsx, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.tsx, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBannerClient.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
https://github.com/opengovsg/isomer/pull/902
- does not have CSP in studio thus demo fails
- `fetch` structured in a way that cause nextjs static export to fail
- Details ...
**Bug Fixes**:
- update studio's CSP to allow connect-src based on S3 asset URL instead of hardcoding
- replace `react-query` - `fetch` isn't available during build time since it's a browser API, and suggested solution is to wrap it in `useEffect`. however, `useQuery` itself is a hook and should not be placed inside `useEffect` due to potential hydration error. To keep things simple, i have replace `useQuery` altogether with the basic `useState` and `useEffect`
note: first part on CSP only required for local development
https://www.loom.com/share/acc94c03b3bf4486882c23c0c93c154b?sid=7ef0be6f-d0b8- …
=> isom-1678 dynamic blocks for muis fix

apps/studio/src/server/trpc.ts
we want to have more logs so we can debug easily
log the `rawInput` - since dd parses json, we will get this as data in dd which we can filter by
=> chore: log everything

apps/studio/prisma/constants.ts
We were missing sophie and felicia as migrators.
- Add them.
=> chore: add sophie and felicia as migrators

packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/Tag/Tag.tsx, packages/components/src/templates/next/render/renderComponentPreviewText.ts, packages/components/src/types/page.ts, packages/components/src/types/variants.ts
one off clean-up of linting issues by running `npm run format:fix` and `npm run lint:fix`
=> 2025-01-17 - lint and format

apps/studio/src/server/modules/site/__tests__/site.router.test.ts
failing unit test as we have extra value that's not used
Delete extra value
=> chore: fix unit test

apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/integration/helpers/seed/index.ts, apps/studio/tests/msw/constants.ts, apps/studio/tests/msw/handlers/collection.ts, apps/studio/tests/msw/handlers/me.ts, apps/studio/tests/msw/handlers/sites.ts
- Stories have dynamic dates, leading to repeated (but useless) snapshiots, where the only thing changed is the date
- set the date to a fixed date
=> chore: update dates to fixed date

apps/studio/src/features/editing-experience/components/form-builder/hooks/useImage.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, package-lock.json
we need to process the image and show the uploaded stae
add blue infobox
=> fix: image

apps/studio/src/features/dashboard/components/PageSettingsModal.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/tests/msw/handlers/page.ts, package-lock.json
- toast copy on page settings save is misleading
- article page header lacks toast on save
- update toast copy for page settings save
- add toast for article page header save
=> chore(copy): update copy + add toast

apps/studio/public/assets/css/preview-tw.css, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.stories.tsx, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBannerClient.tsx, packages/components/src/templates/next/components/internal/SearchableTable/SearchableTableClient.tsx
make improvement to MUIS prayers timing banner so its more visible, based on user feedback
RE: https://opengovproducts.slack.com/archives/C06R4DX966P/p1740648804675979?thread_ts=1740625948.189109&cid=C06R4DX966P
- Details ...
- update the UI
no test needed (verifiable through storybook)
=> Improve muis prayers banner UI

apps/studio/src/lib/mail.ts
one can send email to non-whitelisted email via email service
- Details ...
- add a safeguard check to prevent it
=> feat: Add email whitelist check before sending emails

apps/studio/src/server/modules/me/me.service.ts, apps/studio/src/utils/email.ts
Closes https://linear.app/ogp/issue/ISOM-1765/refactor-remove-dead-code
=> isom-1765 remove dead code

apps/studio/src/features/users/components/UserPermissionModal/AddUserModal.tsx
bug fix for wrong conditional for whitelist
=> chore: fix wrong conditional

packages/components/src/templates/next/components/complex/Contentpic/Contentpic.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx
Aspect ratio for components were variable for every screen size and content
Fix aspect ratio for collection thumbnail and contentpic:
Infocards will be dealt with on a different PR.
=> fix aspect ratio for collectionCards / contentPic

apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/auth/__tests__/auth.router.test.ts, apps/studio/src/server/modules/auth/auth.router.ts
see attached issue
Closes ISOM-1789
1. add log to router 
2. add tests
=> chore(audit-log): add logging to logout with tests

apps/studio/src/server/modules/collection/collection.router.ts
see https://github.com/opengovsg/isomer/pull/1175#discussion_r2005810267
swap to using `tx`
=> chore: use tx instead of db for all or nothing

apps/studio/src/server/modules/audit/__tests__/utils.ts, apps/studio/src/server/modules/collection/__tests__/collection.router.test.ts, apps/studio/src/server/modules/collection/__tests__/utils.ts, apps/studio/src/server/modules/page/__tests__/page.router.test.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/__tests__/resource.service.test.ts
See related ticket
- add audit logging to page router 
- add tests to page router for audit logs
=> feat(audit-logging): add audit logging to page router

apps/studio/package.json, package-lock.json
update starter kitty to latest version
=> chore: update @opengovsg/starter-kitty-validators to version 1.2.11

.github/workflows/deploy_production.yml, .github/workflows/update_release_branch.yml, tooling/build/scripts/preBuild.sh, tooling/build/scripts/publisher.sh
Closes https://linear.app/ogp/issue/ISOM-1826/update-release-procedure-to-push-to-a-release-branch
- add a job in exisiting github action workflow to push main to release on release trigger
- update prebuild.sh and publisher.sh
=> isom-1826 update release procedure to push to a release branch

apps/studio/src/components/ErrorBoundary/DefaultNotFound.tsx, apps/studio/src/components/ErrorBoundary/DefaultServerError.tsx, apps/studio/src/constants/misc.ts, apps/studio/src/features/dashboard/SiteList.tsx, apps/studio/src/features/sign-in/components/SingpassCallback.tsx, apps/studio/src/pages/sign-in/singpass/index.tsx, apps/studio/src/server/modules/auth/singpass/singpass.router.ts, apps/studio/src/stories/Page/SignInPage/SingpassSignInPage.stories.tsx
There is no proper error handling for the Singpass authentication mechanism.
- Add error handling screens.
=> feat: add error handling for Singpass authentication

apps/studio/docker-compose.yml
docker-compose failure causing test failure
=> fix: update mockpass repository URL in docker-compose.yml

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsChildPageLayoutControl.tsx, package-lock.json, packages/components/src/interfaces/internal/ChildrenPages.ts, packages/components/src/templates/next/components/internal/ChildrenPages/ChildrenPages.stories.tsx, packages/components/src/templates/next/components/internal/ChildrenPages/ChildrenPages.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx
See attached ticket
- Add a `RowsLayout` component that renders when teh `layout` selected is row 
- Add the `imageObjectSchema` to our `articlePageSchema` -> not tackling updated design of article page yet, will be done in subsequent ticket
- fixed infocard `layout` to `index`; this was guaranteed before (have to look at `IndexPage.layout`), so this is not changing anything
see storybook, attached videos here are also from story book
https://github.com/user-attachments/assets/d79a543e-bf17-42f6-8692-85fc8ae2585f
=> feat(index-page): row layout

packages/components/src/templates/next/components/complex/Blockquote/Blockquote.tsx
rendering wrote image source without assetBaseUrl
- Details ...
**Bug Fixes**:
- add assetbaseurl
=> fix blockquote image display

tooling/build/scripts/preBuild.sh, tooling/build/scripts/publisher.sh
re: https://opengovproducts.slack.com/archives/C06R4DX966P/p1746703110996739?thread_ts=1746694175.428299&cid=C06R4DX966P
=> fix: remove tag annotation from version

apps/studio/src/server/modules/collection/collection.router.ts
- remove unused endpoint - came across this when working on another ticket
- good time to remove, before VAPT
=> remove unused endpoint (getSiblingsOf)

apps/studio/src/server/modules/collection/__tests__/collection.router.test.ts, apps/studio/src/server/modules/collection/collection.router.ts
see attached ticket
1. add a `validateUserPermission` call for `read` here
=> chore: add read permissions for `readCollectionLink`

apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/permissions/permissions.type.ts
Perms check for publish action is wrong
Add check for "publish" action
=> add perms check for publish action

.github/workflows/deploy_vapt.yml
=> fix: update vapt s3 asset bucket name

.github/dependabot.yml
ooopsie invalid schema, it has to be nested
=> fix - dependabot ignore wrong schema

.gitignore
=> chore: add aider to gitignore

apps/studio/prisma/constants.ts
Add gautam to isomer admin to view studio
=> chore(add-admin): add name studio admin

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/constants.ts
20MB for the file size limit is too little.
- Increase the file size limit from 20MB to 50MB
=> chore: increase file size limit to 50MB

apps/studio/src/server/modules/asset/__tests__/asset.service.test.ts
Missing test case for path traversal 
Add test case in
=> chore: add test case for path traversal

.github/workflows/aws_deploy.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml
> [!NOTE]
>
> Still **pending the approval** of the app to be installed on our Slack workspace
There is a lack of visibility when a release happens.
**Features**:
- Notify the configured channel, mentioning the configured team that a deployment to production has started and completed either successfully or failed.
=> feat: notify Slack channel upon release
