opengovsg/isomer

src/classic/components/Hero/Hero.stories.tsx, src/classic/components/Hero/Hero.tsx, src/classic/components/Hero/HeroDropdown.tsx, src/classic/components/Hero/HeroInfobox.tsx, src/classic/components/Masthead/Masthead.tsx, src/common/Hero.ts, tailwind.config.js
References:
- Infobox (mobile): https://github.com/isomerpages/isomerpages-template/blob/next-gen/_includes/homepage/hero/components/hero-infobox-mobile.html
- Infobox (desktop): https://github.com/isomerpages/isomerpages-template/blob/next-gen/_includes/homepage/hero/components/hero-infobox-desktop.html
- Dropdown: https://github.com/isomerpages/isomerpages-template/blob/next-gen/_includes/homepage/hero/components/hero-dropdown.html
- Side layout: https://github.com/isomerpages/isomerpages-template/blob/next-gen/_includes/homepage/hero/hero-side-layout.html
- Hero component: https://github.com/isomerpages/isomerpages-template/blob/next-gen/_includes/homepage/hero.html
=> feat(hero): add hero layouts with key highlights

.storybook/preview.ts, src/index.css, src/templates/classic/components/Button/Button.stories.tsx, src/templates/classic/components/Cards/Cards.stories.tsx, src/templates/classic/components/Content/Content.stories.tsx, src/templates/classic/components/Footer/Footer.stories.tsx, src/templates/classic/components/Header/Header.stories.tsx, src/templates/classic/components/Hero/Hero.stories.tsx, src/templates/classic/components/Image/Image.stories.tsx, src/templates/classic/components/InfoCards/InfoCards.stories.tsx, src/templates/classic/components/Infobar/Infobar.stories.tsx, src/templates/classic/components/Infopic/Infopic.stories.tsx, src/templates/classic/components/Masthead/Masthead.stories.tsx, src/templates/classic/components/Search/Search.stories.tsx, src/templates/classic/components/SidePane/SidePane.stories.tsx, src/templates/next/components/Button/Button.stories.tsx, src/templates/next/components/Navbar/Navbar.stories.tsx, tailwind.config.js
We currently default to using Lato for everything, even though Isomer Next uses Inter.
**Features**:
- Use Storybook's native support for switching themes to allow us to specify the theme to use.
=> feat: add theme support to storybook

src/presets/classic.js, src/presets/next.js, src/templates/classic/components/Button/Button.tsx, src/templates/classic/components/Hero/Hero.tsx, src/templates/classic/components/Hero/HeroDropdown.tsx, src/templates/classic/components/Hero/HeroInfobox.tsx, src/templates/classic/components/InfoCols/InfoCols.tsx, src/templates/classic/components/Infobar/Infobar.tsx, src/templates/classic/components/Infopic/Infopic.tsx, src/templates/classic/components/Search/Search.tsx, src/templates/next/components/Hero/Hero.tsx, src/templates/next/components/InfoCols/InfoCols.tsx, tailwind.config.js
Our theme presets is a little messy right now.
**Features**:
- Separate the theme presets for each template. This also allows us to publish the presets as a separate NPM package in the future, and downstream sites can just import the package, layer the site-specific theme colours on top, and build the final site.
=> feat: use separate theme presets for each template

src/common/Callout.ts, src/common/index.ts, src/templates/next/components/Callout/Callout.stories.tsx, src/templates/next/components/Callout/Callout.tsx, src/templates/next/components/Callout/index.ts, src/templates/next/components/Paragraph/Paragraph.tsx, src/templates/next/components/index.ts
uses Paragraph component to get mark support out of the box
https://linear.app/ogp/issue/ISOM-786/create-callout-component-in-isomer-next
only adding Info variant for now as other variants are not designed yet
https://www.figma.com/file/8TEzSSDbx97gctRJ7nKdqG/Website-Template-Gen-2?type=design&node-id=1064-7687&mode=design&t=B0tzSBrd08CX5BvG-0
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> feat: add callout component

.github/workflows/ci.yml
As of now, main line breaks, and there is no feedback to devs that their code is introducing bugs. 
This adds the cicd make sure that bulid is passing the builds to warn devs
eg: current state:
note: this pr does not fix the errors, just adds observability to the problem. I think this should still go into main line, and  separate prs are needed to fix the issues in main line builds
=> feat(qol): add cicd

src/engine/types.ts, src/templates/next/layouts/Collection/Collection.stories.tsx, src/templates/next/layouts/Content/Content.stories.tsx, src/templates/next/layouts/Homepage/Homepage.stories.tsx, src/templates/next/layouts/Skeleton/Skeleton.tsx
move lastUpdated to props instead of letting `Skeleton` always use current time
(this was also causing chromatic to keep reporting diffs on the layout stories)
moved that logic to the template instead : https://github.com/isomerpages/isomer-next-base-template/pull/1
=> fix: supply lastUpdated instead of using current time in Skeleton

src/engine/types.ts, src/templates/next/layouts/Collection/Collection.tsx, src/templates/next/layouts/Content/Content.tsx, src/templates/next/layouts/Homepage/Homepage.tsx, src/templates/next/layouts/SearchSG/SearchSG.stories.tsx, src/templates/next/layouts/SearchSG/SearchSG.tsx, src/templates/next/layouts/SearchSG/index.ts, src/templates/next/layouts/index.ts
Refer to the [onboarding guide](https://docs.developer.tech.gov.sg/docs/searchsg-onboarding-guide/customisation-embed?id=step-1-load-the-searchconfigjs-script-for-result-page).
Not doing the search results page yet for local search as that is more complicated + we are prioritising SearchSG integration.
=> feat: introduce SearchSG embedded results page

src/presets/next.ts, src/templates/next/components/complex/Button/Button.tsx
Closes [ISOM-959](https://linear.app/ogp/issue/ISOM-959/button-design-review)
- Updated styling to match [designs on Figma](https://www.figma.com/file/8TEzSSDbx97gctRJ7nKdqG/Website-Template-Gen-2?type=design&node-id=1597%3A3747&mode=design&t=RxkJylzpBCboL0Tr-1)
- Swapped out tokens (not used anywhere else)
- Details ...
=> fix: adjust styling for buttons

src/templates/next/components/internal/Footer/Footer.tsx
Previously the legal section was not aligned to the bottom of the footer. So it was looking quite jank on desktop.
Thanks @kishore for the help!
Sorry for the minuscule PRs
=> fix(footer): nit - align legal part to the bottom of the footer

.github/workflows/chromatic.yml, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/internal/Card.tsx
Styling fixes and one a11y fix for infocards
1. Removed gap-12, changed to pb-12 (pb-8 for <sm) below title area instead (gap-12 was causing an extra left padding when there is no title)
2. Removed horizontal card variant from the Default info cards layout. Instead, at md-lg range, cards collapse to a 2-col layout. This is after trying out designs at different viewports; turns out vertical variant still fits.
3. Added border-radius of 6px
5. Hover state opacity 80% 
6. <a> is inside the card content instead of the whole card. Whole card is still clickable (ref: [Cards](https://inclusive-components.design/cards/))
7. Fixed image height to h-52
8. Scaled down padding in the text section
9. Added line-clamp for title and paragraph.
**BEFORE**:
**AFTER**:
at w=800px, cards collapse to 2 …
=> fix(infocards): styling and a11y fix for infocards

packages/components/src/common/icons.ts, packages/components/src/interfaces/complex/Button.ts, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.stories.tsx, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx
Design changes to infocols
- Row-gap 5rem
- Col-gap 7rem
- Add background behind icon
- Gap below block title 6rem
- Details ...
- [ x] No - this PR is backwards compatible
**BEFORE**:
**AFTER**:
=> fix(infocols): design fixes, more icon support

packages/components/src/templates/next/components/complex/Infopic/Infopic.stories.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.tsx
- Previously, the two infopic variants were the same. Updated the 2nd infopic variant to use within content pages and added some styling changes to match [designs here](https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/Isomer-Next-Component-Library?node-id=1-10)
"Side by Side" variant has a border radius and is for content page usage
"Side Part" variant is for homepage usage
=> fix(infopic): style fixes for infopic variants

packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/layouts/Article/Article.stories.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx
Article layout was looking jank
Key changes:
- Smaller title font size
- Removed box around summary
- Summary font colour is lighter
- Removed divider
- Adjusted some spacing
After images:
=> fix(style): article layout design fixes

packages/components/src/presets/next.ts, packages/components/src/templates/next/components/internal/BaseParagraph/BaseParagraph.tsx, packages/components/src/templates/next/components/native/Heading/Heading.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx
Previously, spacing between headings / paragraphs were either too big or missing, causing janky views on content pages:
Also, the "h2" styles on content pages were very big.
This PR includes updates to:
- heading-02 size is smaller
- between-paragraph gap is larger for more whitespace
- some headings have a smaller margin-top
- paragraphs have a margin-bottom so that accordions / tables that follow it aren't too close.
=> fix(styling): spacing updates for paragraph, headings

packages/components/src/templates/next/components/complex/Accordion/Accordion.tsx, packages/components/src/templates/next/components/complex/Button/Button.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/internal/Card.tsx
Adding minor design fixes to single PR because most of these are one-liners per component:
- **Accordion** had focus state which was appearing on active state, removed (focus state is for keyboard manipulation)
- **Button** y-padding needs to be larger
- **Infocards** should use h2 tag (like all other blocks) instead of h3 
- **Infocards** should use outline instead of border
The linter may have caused reordering of classnames
=> fix(styling): minor design fixes for components

packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx, packages/components/src/utils/getBreadcrumbFromSiteMap.ts
Update breadcrumb design for three main changes:
- "Home" should be displayed
- Better to not display current page; after doing some competitive analysis, seems like it's rare to show the current page and it serves zero user value as well, especially since we always show the page title top and center. It also messes up the Article layout a bit especially when the current page title is very long
- Last menu in crumbs should not have chevron trailing after it
=> fix: update breadcrumb display

packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/CollectionSearch/CollectionSearch.tsx, packages/components/src/templates/next/components/internal/CollectionSort/CollectionSort.tsx, packages/components/src/templates/next/components/internal/Filter/Filter.tsx, packages/components/src/templates/next/components/internal/LocalSearchInputBox/LocalSearchInputBox.tsx, packages/components/src/templates/next/components/internal/Pagination/Pagination.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
A temporary design cleanup for the Collections layout. **This layout will be going through redesigns soon**, so this cleanup is just to iron out alignment issues to make more presentable, notably:
- Temporarily hide selected filters (it's been commented out)
- Pagination: fix issue where left-arrow was really small and alignment issue
- Vertical alignment of "Filter by" and Results so that the horizontal lines don't look janky
- Filters was taking up too little width, adjusted to take up more space (1/4 in larger screens)
- Search bar is thicker for visual balance
- Page title and subtitle take up limited width, to follow other page layouts & best practices
- Fix missing gap above empty results copy in mobile
Before:
After:
Mobile:
=> fix(styling): collections layout design cleanup

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Tweaks to stats block:
- row gap between title and stats
- adjust max-width
- adjust title size
=> fix(styling): stats block styling updates

apps/studio/src/components/features/editing-experience/PageCreateModal.tsx, apps/studio/src/features/editing-experience/PageCreateModal.tsx, apps/studio/src/pages/dashboard/index.tsx
We need to allow users to create new pages on Studio.
Closes ISOM-1142
Implement Chakra modal with react-hook-form validations.
- Details ...
**AFTER**:
=> ISOM-1142: feat(modal): page create modal with validations

packages/studio/package-lock.json, tooling/build/amplify/create-app.js, tooling/template/app/[[...permalink]]/page.tsx, tooling/template/app/layout.tsx, tooling/template/app/not-found.tsx, tooling/template/app/robots.ts, tooling/template/app/sitemap.ts, tooling/template/tailwind.config.js
The base template wasn't linted before, there was a lingering package-lock.json file in `packages/studio` and the create-app.js file can only create one app at a time.
- Lint all the files inside the base template folder.
- Remove the package-lock.json file from the `packages/studio` folder, this has already been replaced by `apps/studio/package-lock.json`.
- Update the `create-app.js` file to allow creating multiple apps at one go.
=> chore: lint files, remove extra package-lock.json

apps/studio/src/schemas/folder.ts, apps/studio/src/server/modules/folder/folder.router.ts, package-lock.json, package.json
Closes [ISOM-1147](https://linear.app/ogp/issue/ISOM-1147/create-dto-for-read-folder)
Adds dto for BE<>FE for reading of folder, used in features like display folder contents.
- FE to BE schema requires siteId and resourceId for the folder. Assumptions made is that resourceId could be null if we want to retrieve root level folder for the particular site, but may have to look at this again.
- BE to FE scheme is in folder.router, distinction made between child folder and child pages.
- Details ...
=> ISOM-1147: feat: read folder dto

docs/next/0.1.0.json
Closes ISOM-1196.
Closes ISOM-1197.
- Moved image component from native to complex component
- Renamed keys that were using kebab-case to camelCase
**Notes**:
- No changes are needed on mti-corp or other repos as the changes are only internally referenced by the schema. The page schemas uses the `type` key which were not renamed.
- **FOR FEEDBACK**: Decided to keep component names (referenced by the page schemas) to be lowercase (i.e. `unorderedlist` instead of `unorderedList`) for simplicity. Let me know if this approach is sane or we should use camelCase as much as possible.
=> chore: rename keys from kebab-case to camelCase

turbo.json
Current turbo.json missed out the dependency we have on the isomer-components package. Hence, this causes `turbo build` to fail.
Add the `^build` so that turbo will build the packages by starting with the one that has no internal dependencies and walk its way up the tree. Can go through https://turbo.build/repo/docs/reference/configuration for more info.
Also adds some minor changes to add `dist` as a output for caching purpose, and globalEnv configs.
- Details ...
=> Fix turbo json

packages/components/src/templates/next/components/internal/Footer/Footer.tsx
GovTech has updated their report vulnerability link since they have migrated to Isomer Classic.
- Updated the link to point to https://www.tech.gov.sg/report-vulnerability
=> chore: update report vulnerability link

apps/studio/src/schemas/folder.ts, apps/studio/src/server/modules/_app.ts, apps/studio/src/server/modules/folder/folder.router.ts
Closes [ISOM-1194](https://linear.app/ogp/issue/ISOM-1194/create-api-to-return-the-sites-pages), partially. This is just a simple endpoint that allows for testing of the site dashboard page with DB data. It is missing the following things which I have also added to a new ticket 1203(not linking it as linear might pick up on it): 
1. Currently, no permission checking is done.
2. Since there is no decided solution for storing page status, whether it's published or draft, this is not working yet(just returns published for now)
3. Similar to the above, there is no current decided solution for where the last edited information(datetime and user) is stored. Potentially, this could be stored as the diffs between edits, or somewhere in the db. Dummy data is fielded for this at the moment.
Lastly, …
=> Rudimentary endpoint for getting a folder/site's content

apps/studio/prisma/seed.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/src/server/modules/site/site.types.ts, packages/components/src/types/index.ts, packages/components/src/types/site.ts
The producer (components) does not differentiate the site-wide props that are generated or user-defined.
- The `IsomerSiteProps` are broken down into types that are generated and user-defined, so that consumers know how to differentiate between them.
=> feat: breakdown site-wide props types

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsDropdownControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsIntegerControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsOneOfControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsProseControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsRadioControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/index.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsVerticalLayout.tsx
The JSONForms implementation do not support the array, oneOf and prose inputs.
**Features**:
- Add placeholders for these types of inputs. Full implementation will come in subsequent PRs.
=> feat: add placeholders for array, oneOf and prose inputs

apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/pages/dashboard/edit/index.tsx, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/resource/resource.types.ts, apps/studio/src/types/editorDrawer.ts
we want to have drag and drop functionality to re-arrange blocks easily
Closes ISOM-1170.
- at present, there are a few stateful variables (multiple calls of `useState` for managing old/new editor state) 
- to have a single centralised place to manage them, i've streamlined them into `editorState/setEditorState` from the `useEditorDrawerContext`
- then, i hooked up this state to the `onDragEnd` call for dnd. 
- the feedback loop is then:
- i drag something and drop
- on drag end triggers
- new state is derived post-drag
- this new state is saved into `editorState`
- new state is fed into `Preview`, which triggers a re-render
- i'm not quite sure what the `old/newEditorState` is (i've removed both of them) 
- not quite sure what `isCopied` etc is too …
=> feat(dnd): add dnd to preview

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsObjectControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/index.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsVerticalLayout.tsx
We do not have a nested object renderer, which makes us unable to render the hero dropdown fields (since it is a nested object within each of the hero variants).
**Features**:
- Added an object renderer to render nested objects specifically. ([Reference here](https://github.com/eclipsesource/jsonforms/blob/master/packages/material-renderers/src/complex/MaterialObjectRenderer.tsx))
**BEFORE**:
**AFTER**:
=> feat: introduce JSONForms nested object renderer

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsGroupLayout.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsVerticalLayout.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/index.ts, apps/studio/src/features/editing-experience/data/0.1.0.json, apps/studio/src/types/schema.ts
We don't have a group layout renderer yet, so we are not able to group similar fields together.
**Features**:
- Introduce a new group layout renderer so that we can group similar fields together and apply a header to them.
=> feat: introduce JSONForms group layout renderer

.github/CODEOWNERS
Super annoying spam every night due to dependabot. By adding the package.json and package-lock.json rules to codeowners, those files will be marked as ownerless and thus no email spam from dependabot PRs.
=> feat: do not assign CODEOWNERS as reviewers for dependabot PRs

apps/studio/.storybook/preview.tsx, apps/studio/src/pages/api/trpc/[trpc].ts, apps/studio/src/utils/trpc.ts
Batching using trpc v10 in a dockerised environement is not production ready. 
For ref, can refer to egazette finding: GTA-35-004 WP1/WP2: Potential DoS Risk through TRPC batching (Medium)
Ideally, this would be solved by checking the total number of batching calls that were made, and it there was more than x number of calls that were made, the server should return a `TOO_MANY_REQUESTS`. However, this will logic will have tight coupling with the implementation with trpc. This will take a hit in latency, and if eng feels this is not worth the tradeoff, can treat this as throw away code but must be confident in hand-rolling own implmentation, since [TRPC](https://opengovproducts.slack.com/archives/C0774ABT2J2/p1719827474185169?thread_ts=1719579080.985729&cid=C0774ABT2J2) is applying …
=> fix(trpc): remove batching

.github/workflows/chromatic.yml
This PR updates the Chromatic workflow configuration to improve efficiency by running only when relevant changes are detected in specific directories.
Also start running Chromatic for studio app.
- Renamed the workflow from "Chromatic for Isomer Components" to "Chromatic".
- Added a `changes` job to detect changes in specific directories (`packages/components/**` and `apps/studio/**`).
- Split the Chromatic job into two separate jobs (`ui` and `studio`) that run based on changes detected in the respective directories.
- Updated the Chromatic GitHub Action to the latest version and made various optimizations.
- Verify that the Chromatic workflow runs only when there are changes in the `packages/components/**` or `apps/studio/**` directories.
- Ensure that the `ui` job runs for changes in …
=> feat: update chromatic github action for studio

apps/studio/src/features/editing-experience/components/PageCreateModal.stories.tsx, apps/studio/src/features/editing-experience/components/PageCreateModal.tsx, apps/studio/src/schemas/page.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/theme/components/Modal.ts
Closes ISOM-1248
Update PageCreateModal component with the expected page URL generation behavior and form validation.
- Created `PageCreateModal.stories.tsx` for Storybook configurations
- Added form validation using Zod schemas
- Enhanced Page URL generation logic
- Updated Chakra UI modal theme configuration
1. Open the Storybook interface.
2. Navigate to `Components/PageCreateModal` stories.
3. Verify that the PageCreateModal component renders correctly.
4. Test the form validation and URL generation.
This change adds the necessary modal component for creating new pages within the application, improving the user experience for adding pages.
---
=> feat(CreatePageModal): add form validation and expected behaviour for modal

apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, packages/components/src/engine/index.ts, packages/components/src/index.ts, packages/components/src/interfaces/native/Heading.ts, packages/components/src/interfaces/native/ListItem.ts, packages/components/src/interfaces/native/Prose.ts, packages/components/src/interfaces/native/Table.ts, packages/components/src/schemas/components.ts, packages/components/src/schemas/index.ts, packages/components/src/schemas/main.ts, packages/components/src/types/components.ts
For some reason builds could work before without using refs, but now it doesn't. It is now time to settle the schemas once and for all.
Concretely, the problem is that the schema (after removal of all the Type.Ref) kept running into issues because of duplicate `$id` definitions. This is because the same component can be referenced multiple times by different components, especially the native ones.
**Features**:
- Make all native components be Type.Ref'd.
- Introduce `getComponentSchema` as the main entry point for component consumers to consume the underlying JSON schemas.
- This method ensures that all native components are referenced using Type.Ref, then we separately maintain a definitions list which contains the actual definition for those `$id`.
- This ensures …
=> feat: ref all native components and use getComponentSchema

tooling/build/scripts/preBuild.sh
Now it is not possible to build the next sites because we have a dependency on the `@isomer/eslint-config` and other stuff.
**Bug Fixes**:
- Decouple this dependency for the time being, since the CodeBuild process we will be using in the future will use the entire monorepo.
=> fix: decouple template package.json for building sites

packages/components/src/types/schema.ts
The `Type.Null` is too strongly typed, causing developer grief.
**Bug Fixes**:
- Change all instances of `Type.Null` into `IsomerComponentsSchemas` to standardise with the other page schemas. We still enforce that it is an empty array via the `minItems` and `maxItems` props.
=> fix: remove null types from page content

apps/studio/src/server/trpc.ts, apps/studio/tests/integration/helpers/iron-session.ts
This PR fixes an issue with Cross-Site Request Forgery (CSRF) protection. While actions that change the application’s state require JSON data in the POST body, the request's content type is not validated. This allows an attacker to craft a cross-site request that the server would accept, leading to a state change in the application.
Currently, because the session cookies do not have the SameSite attribute explicitly set to None, the browser prevents the exploitation of this CSRF vulnerability. However, an XSS on the subdomain could allow the exploitation of this vulnerability.
The fix to this issue is to allow only application/json as a valid content type, to mitigate the risk of CSRF.
=> fix: add content type header middleware

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/DraggableDrawerButton.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx
Closes ISOM-1219.
**Features**:
- Enhance the existing array custom renderer to handle drag-and-drop of sub-components.
- Implementation was referenced from [JSONForm's MaterialListWithDetailRenderer](https://github.com/eclipsesource/jsonforms/blob/master/packages/material-renderers/src/additional/ListWithDetailMasterItem.tsx), especially regarding how they obtain the appropriate child label to display.
=> feat: introduce sub-component dnd custom renderer

packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx
breadcrumbs were previously messy with every link underlined.
Closes [ISOM-1256](https://linear.app/ogp/issue/ISOM-1256/restyling-breadcrumbs)
Restyled as per [Figma](https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/(New%2C-WIP)-Isomer-Next-Component-Library?node-id=424-2944)
From Storybook:
- Details ...
- [x ] No - this PR is backwards compatible
=> [TEMPLATE] fix: restyle breadcrumb to reduce visual clutter

tooling/build/scripts/generate-sitemap.js
The schema was updated, so the auto-generated index page did not conform with the new schema.
**Bug Fixes**:
- Fix the schema of the auto-generated index page, so it is now within a Prose block.
=> chore: fix schema for generated index page

apps/studio/src/schemas/site.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts
Currently, no procedure catering for move of resource and setting site configs.
Adds procedures to move resources (single), and set site config (override fully) and set site notification (minimum requirement of site settings).
TODO: changes in site configs should trigger a immediate publish
- Details ...
=> ISOM-1258: add-site-and-move-procedures

apps/studio/package.json, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/prisma/types.ts, apps/studio/src/features/editing-experience/components/PageCreateModal.tsx, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/hooks/useQueryParse.ts, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/schemas/page.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/stories/Page/SitePage.stories.tsx, apps/studio/tests/msw/handlers/site.ts, package-lock.json, packages/components/src/engine/index.ts
Added the `prisma-json-types-generator` module to the project and associated it with the JSON columns in the Prisma schema. This enables the usage of strongly typed JSON columns in the database.
- Added `prisma-json-types-generator` version `^3.0.4` to `package.json` and `package-lock.json`.
- Updated `schema.prisma` to include a new generator for `prisma-json-types-generator`.
- Added type annotations for JSON fields in various models.
- Created a new `types.ts` file to define types for the JSON columns.
- Updated various parts of the codebase to use the new strongly typed JSON fields.
1. Install the new dependencies by running `npm install`.
2. Verify that the Prisma client is generated with the new JSON types by running `npx prisma generate`.
3. Run the existing tests to ensure that no …
=> feat: add types to JSON columns in prisma schema

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/server/modules/page/page.router.ts
The various page states have not yet been wired up.
**Features**:
- Wire up all the page states so the editing flow is more complete.
- What is NOT done/not working:
- Adding of new blocks (will do in a separate PR, because need to adjust the schema to set default values)
- Editing hero component (I think the schema is slightly incorrect, may update this PR later or do separately).
=> feat: wire up all page states in editing experience

apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx
Redirection not working because the wrapper was above the `useMe` call. This PR fixes that.
=> fix: move usage of `useMe` below EnforceLoginStatePageWrapper

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/utils/resource.ts, apps/studio/tests/msw/handlers/page.ts
Refactor the handling of resource types in the dashboard components to use the "type" field directly from the data source instead of deriving it from other fields.
- Modified `ResourceTable`, `ResourceTableMenu`, and `TitleCell` components to use the `type` field directly.
- Updated the `ResourceTableMenuProps` and `TitleCellProps` interfaces to align with the new data structure.
- Adjusted the server-side `page.router` to include the `Resource.type` field in queries.
- Removed the outdated `ResourceType` type and `getResourceType` function.
- Updated mock data in `msw` handlers to include the `type` field.
1. Verify that the dashboard displays resources correctly, with the appropriate icons and menu items for each resource type.
2. Check the functionality of resource-specific actions, …
=> feat: use type column from db  for resource list table

apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/PreviewLayout.tsx, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/tests/msw/handlers/sites.ts
Enhance the Preview component to include `siteId` and dynamic overrides for date and permalink based on the selected layout. Various files have been updated to support these changes, including new properties, hooks, and configurations.
- Added `siteId` to `useCreatePageWizardContext`. Adjusted all related components to pass `siteId` down to the Preview.
- Introduced `useMemo` in `PreviewLayout` to create dynamic overrides for date and last modified fields based on the current layout.
- Updated `Preview` component to accept new props: `overrides`, `siteId`, and `permalink`. Used `merge` for override handling.
- Updated page fetching logic and trpc router to consistently use `permalink` instead of `pageName`.
- Revised mock handlers and site configuration service to include additional site …
=> feat: properly update page and site config in preview renderer

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx
Modified the `TitleCell` in site dashboard to include dynamic links to resources.
=> feat: add rudimentary link to resource in dashboard

apps/studio/next.config.mjs
The Ajv compilation to create the validation function requires `unsafe-eval` to be enabled for `script-src`.
**Bug Fixes**:
- Enable `unsafe-eval` for script-src for the time being, so that we can proceed with user testing.
- Ref: https://ajv.js.org/security.html#content-security-policy
=> fix: enable unsafe-eval for user test

apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/server/modules/page/page.router.ts
The default blocks contents are currently set to undefined.
- Add default block contents for all the blocks except for the hero component.
- Also set logger to false for Ajv since we don't use it for debugging (and it is very noisy).
=> chore: add default blocks contents

packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/interfaces/complex/InfoCols.ts, packages/components/src/interfaces/complex/Infobar.ts, packages/components/src/interfaces/complex/Infopic.ts
Some props appear on the form editor but do not affect how it is rendered on the preview, which can be confusing to the user.
**Bug Fixes**:
- Remove all the props that are only currently used in the classic theme from the schema, so it does not get rendered on the form builder inside Studio.
=> chore: remove props only used in classic from schema

apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx
Previously, the preview took up the whole area and had no discernible border between the sidebar/preview. In order to counteract this, the figma had shadows + padding that wasn't implemented
Add 2 `Box`s that sets the `padding` + the `shadow` on the component that uses the preview. Specifically this does:
- set bg to `gray.100`
- add `shadow="md"`
- add `borderRadius=8px`
- didn't set this inside the `Preview` component itself. didn't want to tie the styling too closely with the `Preview`, which is supposed to just be a thin wrapper over `RenderEngine`. this means there's some duplicated code between `Preview` and `PreviewLayout`
=> fix(preview): add shadows + padding

packages/components/src/templates/next/components/native/ListItem/ListItem.tsx, packages/components/src/templates/next/components/native/OrderedList/OrderedList.stories.tsx, packages/components/src/templates/next/components/native/UnorderedList/UnorderedList.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx
The numbering for ordered lists keeps skipping by 1 whenever there is a nested list.
**Bug Fixes**:
- Make the nested list be rendered properly (with `ol`, `ul` and `p` being siblings in a nested list).
- No schema changes is necessary because that was the original intent of the schema (which also matches what Tiptap provides), just that the way it was used is incorrect.
**BEFORE**:
**AFTER**:
=> fix: numbering for nested ordered lists

apps/studio/src/components/Svg/BlockEditingPlaceholder.tsx, apps/studio/src/components/Svg/index.ts, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
There is a missing placeholder when the editing drawer is empty.
**Features**:
- Add a placeholder when the editing drawer is empty.
**BEFORE**:
**AFTER**:
=> feat: add placeholder for empty editing drawer

apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsIntegerControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, packages/components/src/interfaces/complex/InfoCols.ts, packages/components/src/interfaces/complex/KeyStatistics.ts
There is no feedback to the user if there is a validation error.
**Features**:
- Display the validation error message to the user if the input does not satisfy the schema.
- For text input fields, if the input becomes empty, set the value to be undefined so that it is taken out of the JSON object (to trigger validation errors if the property is required).
- Also added a simple character counter if the schema has a `maxLength` property set.
=> feat: add validation error messages to form

apps/studio/src/features/editing-experience/components/form-builder/renderers/TipTapEditor.tsx
https://www.notion.so/opengov/markdown-shortcuts-for-header-don-t-work-properly-b452963fc6214704b8a439f0b848cfb3?pvs=4
extend the extension + add input rule so that we search on `level-1`. what this does is that it searches for the number of `#` between `1, level - 1` then maps it back to the correct `level`.
as an example, take a `h2` - we show it as `h1` but the capturing regex should be `#` (the level is 2, but number of capturing # is level - 1. this then gets mapped into the corresponding `Heading` component via `level`.
=> fix: heading extension

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsProseControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsRadioControl.tsx
using `schemaMatches` prunes away the `format` key, which is what we use to identify a `Prose` block and cause the tester to fail, resulting in the renderer not being shown. 
This a blocker on `callout/accordion` where they are not shown.
remove `schemaMatches` - see below ss for extended explanation
using `schemaMatches` and logging the received `resolvedSchema, rootSchema`, we get the following properties: 
note that this does **not** have the `format` key. in contrast, removing the `schemaMatches` function results in this object
note the inclusion of the `format` key here but not in the former screenshot.
`schemaMatches` performs a bunch of sanity checks before calling a `resolveSchema` function (see [here](https://github.com/eclipsesource/jsonforms/blob/d3ee13a059ff9e0bc6dc9282b8f0ca65 …
=> fix: remove `schemaMatches`

.vscode/settings.json, packages/components/src/presets/next/colors.ts, packages/components/src/presets/next/index.ts, packages/components/src/presets/next/typography.ts, packages/components/src/stories/foundation/Typography.stories.tsx, packages/components/tailwind.config.ts
This PR introduces new typography and semantic color tokens to `isomer-components`. Also updates the Tailwind configuration file to use TypeScript.
- Added new color presets to `packages/components/src/presets/next/colors.ts`
- Created a new `typography.ts` file and moved typography-related configuration there.
- Updated `packages/components/src/presets/next.ts` to improve module structure.
- Added Storybook stories to showcase typography styles.
- Updated Tailwind configuration to import plugins using ES module syntax instead of CommonJS.
Sync figma with eng
---
=> feat: add typography and semantic tailwind tokens to isomer component package

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
Previously, our save button was very high up and not pinned ot the bottom. this means the UI is very cramped. design has specified that hte save button should be pinned to the bottom and be sticky so that even when there are many items, it'll display correctly.
- use `Flex` + `Spacer` so that the `Box` containing the button is at the bottom
- add shadows so that the box containing the save button is visually distinct. this is done via tokens rather than palette + raw css values as we've done before
- ~take note that adding many items will still cause the save button **to be pinned to the bottom of the sidebar**; i think what design wants is for the save button to be pinned **to the bottom of the screen**. this is slightly trickier and might involve `pos: absolute` which might complicate …
=> chore: style fixes for save button

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx
At present, we have an optional `sectionIdx` prop that's already legacy (gg). This causes visual noise because it shows a little red `No applicable renderer found` text, which is distracting + useless.
Add a default fallthrough case with super low priority so that stuff that falls through (specifically this, note the `and` condition from json forms) gets caught and rendered as `null`, preventing the visual noise/
The ideal solution would be to jsut update the schema so section idx doesn't exist. however, i don't know if we can deprecate it yet so i'm still going with this solution for now
=> chore: remove render for fallthrough

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20240724082002_update_to_bigint/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/tests/msw/handlers/page.ts
This pull request updates the ID fields for the `Resource`, and `Blob` models to use `BigInt` instead of `Int`. Corresponding changes have been made to Prisma schema, migration files, TypeScript types, and various parts of the application code to handle this change.
This is in relation to introducing versions later!
- Updated Prisma schema to change ID types.
- Created migration script for the database schema changes.
- Modified TypeScript types to reflect new ID types.
- Updated application code to handle `BigInt` IDs.
Note: 
1. We still use `Number` in JS throughout, so we are technically limited by the max int support in JS which is 2^53 - 1. 
2. If you look at the generatedTypes, you will see that bigints are output as String. This requires a cast to and fro number and string. For …
=> update to use bigint for resourceId and blobId

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx, apps/studio/src/server/modules/page/page.router.ts
Previously, `Prose` wasn't saving to db. When `uat` added the save to db, there wasnt the query invalidation portion. This PR adds both functionality in
- use the `updatePageBlob` hook in `TiptapComponent`. 
- invalidate queries on save so that we see the new state
https://github.com/user-attachments/assets/cd4baed3-f3a8-4791-848b-0effee6dee25
=> feat(tiptap): save updates to db + invalidate queries

apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/DeleteBlockModal/DeleteBlockModal.tsx, apps/studio/src/features/editing-experience/components/DeleteBlockModal/index.ts, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx
We don't have the ability to delete blocks in the editor currently.
**Features**:
- Introduce new functionality to delete both a complex and native block.
- Note: The Hero component should be disabled, this will be done depending on whether this or #358 goes in first.
- Added a new modal to confirm with the user that we want to delete the block.
- Also fixed up the stick save button.
=> feat: introduce functionality to delete editor block

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/types/editorDrawer.ts, packages/components/src/schemas/index.ts, packages/components/src/schemas/main.ts
The page metadata editor cannot be changed currently.
**Features**:
- Introduce a new page metadata editor state to edit the page's metadata.
- Changed `previewPageState` and `savedPageState` to handle the entire page and not just the content block.
- Also adjusted the FormBuilder to be generic, so that it can be reused in multiple places.
- Also set the Hero component to be the first fixed block if it is the homepage layout.
=> feat: introduce page metadata editor

apps/studio/src/features/editing-experience/components/ActivateAdminMode.tsx, apps/studio/src/features/editing-experience/components/AdminModeStateDrawer.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/types/editorDrawer.ts
POEs want to use the Studio in its current state, and we don't have an admin mode to see the underlying source code.
**Features**:
- Add an admin mode to the editor to view the underlying JSON page state. Full credit goes to @pregnantboy [in report cards](https://github.com/opengovsg/report-card/blob/993c99783505956a2451463b029f86d806a17b67/src/app/%5B...card%5D/ActivateDraft.tsx).
- The admin mode can only be entered via the root state, so that we ensure the blocks are all valid first before allowing it to be copied.
https://github.com/user-attachments/assets/44dbdabb-058f-4edc-a4d7-d6e127d47b14
=> feat: add admin mode to editor

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
Slicing the blocks array makes everything more complicated and causes an off-by-one error.
**Bug Fixes**:
- Avoid doing a slice on the blocks array and handle the fixed first hero block explicitly.
=> fix: hero fixed block off by one error

packages/components/src/templates/next/layouts/Article/Article.stories.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.stories.tsx, packages/components/src/templates/next/layouts/Search/Search.stories.tsx
Updated the Storybook layouts to include fullscreen parameter and autodocs tags for template layouts that should be in fullscreen.
- Added `layout: fullscreen` parameter to the meta object for Article, Collection, Content, Homepage, NotFound, and Search story files.
- Added `tags: ['!autodocs']` to the meta object for the same story files.
- Updated the names of the default stories to match their corresponding layout names.
1. Run Storybook.
2. Verify that the specified stories are displayed in fullscreen.
3. Check that the tags for autodocs are present.
To ensure consistency across the Storybook layouts and make use of the fullscreen parameter and autodocs tags for better documentation and presentation.
=> feat: set fullscreen layout and remove autodocs for layout stories

apps/studio/tailwind.config.js, packages/components/src/index.css, packages/components/src/presets/index.ts, packages/components/src/presets/next/colors.ts, packages/components/src/presets/next/index.ts, packages/components/src/presets/next/site-theme.ts, tooling/template/data/config.json, tooling/template/tailwind.config.js
Migrated brand colors to CSS variables and introduced a new `isomerSiteTheme` plugin for (future) dynamic theme injection.
- Updated `colors.ts` to use CSS variables for brand colors.
- Introduced `isomerSiteTheme` in `site-theme.ts` to dynamically inject CSS variables.
- Removed the old MOH theme from `index.ts` and integrated the new `isomerSiteTheme` plugin.
Should have no changes for components that were already using the previously (more) hardcoded tokens. 
This change is motivated by the need for better theme management and dynamic theming capabilities using CSS variables.
=> feat: replace hard-coded color values with (hardcoded) CSS variables from site theme

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/DiscardChangesModal/DiscardChangesModal.tsx, apps/studio/src/features/editing-experience/components/DiscardChangesModal/index.ts, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx
We do not have a discard changes warning modal when users close the drawer with pending changes.
**Features**:
- Add a new discard changes warning modal when the user attempts to close the complex/native/metadata editing drawer when there are differences between the preview and saved states.
=> feat: introduce discard changes modal

apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx
After page creation, users are not able to navigate to the newly created page. 
use the `onSuccess` callback to navigate to the newly created page.
=> chore: autonav

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx
This PR fixes an issue where the user could be redirected to the dashboard before the save was completed. This could cause the user to lose their changes if they navigated away from the page before the save was completed.
Update the create page wizard so that the user is not redirected until the save is complete.
=> fix: prevent redir till save done

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, packages/components/src/interfaces/complex/Image.ts, packages/components/src/interfaces/internal/ArticlePageHeader.ts
We have some bugs - `articleSchema` -> `minItems: 1` causes block creation to fail validation without error message. 
image block is `required` but there's no error message set. additionally , the default is 100 but this isn't obvious from the UI
- set `minItems: 0` for `articleSchema`  **or** give some UI feedback (for uat, i just chose the easy fix, open to just removing this) 
- give default in schema + show error message
=> fix(schema): schema validation

packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx
Enhanced the ContentPageHeader and Content layout components to match new figma styles and refactored code for better readability and maintainability.
- Updated styles in `ContentPageHeader.tsx` for better layout and typography.
- Refactored Content layout in `Content.tsx` to use `tailwind-variants` for consistent styling.
- Removed unnecessary imports and cleaned up the code.
storybook
To improve the visual appearance and maintainability of the content page components.
=> feat: update ContentPageHeader and ContentLayout with new design

packages/components/src/presets/next/index.ts, packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.tsx
Unsure if we should call it "desktop" instead of xl. but maybe xl better. who knows.
This update modifies various screen size and max-width configurations across multiple files.
Also updates turbo config to prebuild tw when running dev/build
- Added new screen size breakpoints to the theme configuration, ensuring they are sorted correctly.
- Removed redundant screen size and spacing definitions.
- Updated the max-width utility classes in several components (ContentPageHeader, Masthead, Navbar, CollectionClient, ContentLayout, HomepageLayout, NotFoundLayout) to use `max-w-screen-xl` instead of `max-w-container`.
Stories
To be consistent with desktop breakpoint in design.
=> feat: update breakpoints for isomer components, prebuild tw when building studio

packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx
Siderail on first-level pages don't really make sense, and the table of contents broke after a previous schema update to the heading attributes.
**Bug Fixes**:
- Removed siderail for first-level pages.
- Fixed anchor ID generation for level 2 headings.
=> fix: remove siderail for first-level and fix TOC

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/features/editing-experience/components/CreatePageModal/PreviewLayout.tsx, apps/studio/src/features/editing-experience/components/PreviewIframe.tsx, apps/studio/src/features/editing-experience/data/articleLayoutPreview.json
Add PreviewIframe component to render Preview inside iframe, injecting built Tailwind CSS instead of runtime updates. Update preview-tw.css styles to enhance grid, margin, padding, border, background, text, and transition utilities. Add new utility classes for layout and responsiveness. Deprecate and replace some classes with updated names and variables for consistency with site theme.
=> feat: render layout preview in iframe too

packages/components/src/common/icons.ts, packages/components/src/templates/next/components/internal/TableOfContents/TableOfContents.tsx
- Added new minus icon for list item from BoxIcon
- Updated typography and semantic colour tokens
- Changed underline on hover with underline offset
=> feat: add new 'minus' icon and update TableOfContents component

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/migrations/20240805083439_add_collection_and_collection_page_resource_types/migration.sql, apps/studio/prisma/migrations/20240805090947_add_root_page_resource_type/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx, apps/studio/tests/msw/handlers/page.ts
This PR introduces support for two new resource types: `Collection` and `CollectionPage`.
1. Added `Collection` and `CollectionPage` to the `ResourceType` enum in Prisma schema and generated files.
2. Created a new migration file to update the `ResourceType` enum in the database.
3. Updated the `TitleCell` component to display appropriate icons for the new resource types.
1. Run the Prisma migrations to update the database schema.
2. Verify that the new resource types can be created and managed through the UI.
3. Check that the correct icons are displayed for the new resource types in the `ResourceTable`.
To enhance the feature set by introducing new resource types that allow better organization and categorization of content.
---
=> feat: add collection and collection page to resourcetype enum

packages/components/src/templates/next/components/internal/Filter/Filter.stories.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
This PR corrects the `itemIndex` check in the `updateAppliedFilters` function within `CollectionClient`.
=> fix: fix bug where first collection filter was unable to be unchecked

packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx, packages/components/src/templates/next/components/native/Table/Table.tsx, packages/components/tsconfig.json
Turn on `noUncheckedIndexedAccess` in component's tsconfig to prevent potential runtime errors caused by undefined index access.
Fix typecheck errors caused by the new setting.
=> feat: turn on noUncheckedIndexedAccess to remove class of bugs

packages/components/.storybook/preview.ts, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.stories.tsx, packages/components/src/templates/next/layouts/Search/Search.stories.tsx
Add chromatic modes support to Storybook preview configuration for better visual test coverage.
- Imported `withChromaticModes` from `@isomer/storybook-config`
- Modified the Storybook preview configuration to include chromatic mode settings.
- Updated documentation to guide adding chromatic mode in a per-story basis.
- Set default chromatic mode to 'desktop' with prefer-reduced-motion to 'reduce'.
1. Run Storybook
2. Verify the chromatic mode is applied correctly for stories.
To improve visual test coverage and ensure components behave correctly across different viewing modes.
---
=> feat(components): use desktop breakpoint as default chromatic snapshot

apps/studio/package.json, apps/studio/src/features/editing-experience/components/CreatePageModal/PreviewLayout.tsx, apps/studio/src/features/editing-experience/components/PreviewIframe.tsx, apps/studio/src/features/preview/hooks/useSiteThemeCssVars.ts, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/tests/msw/handlers/sites.ts, package-lock.json
This PR introduces the use of site theme CSS variables in the layout preview, ensuring that the site theme is accurately reflected in the preview.
- Added support for site theme CSS variables in `PreviewIframe`.
- Created `useSiteThemeCssVars` hook to fetch and flatten site theme CSS variables.
- Updated `PreviewLayout` component to use `Suspense` for loading previews.
- Updated site router and service to fetch site theme.
Stories
To ensure that the layout preview accurately reflects the site's theme, providing a more cohesive editing experience for users.
=> feat: inject site theme CSS variables when previewing in studio

packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx
Received some design crit that some of the design choices on Infocols wasn't as intentional (e.g., having rounded corners around the icons), so we had [a design iteration](https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/(New%2C-WIP)-Isomer-Next-Component-Library?node-id=1-14). 
This PR aims to implement said iteration items.
- Overall typography and colour tokens applied
- Overall spacing adjusted for less whitespace
- Adjusted breakpoint (was breaking at `xl` instead of `lg`)
- Hover effects applied to infobox title and icon
- Arrow twitches on hover
- Entire infobox is clickable
=> feat(components): Infocols styling change

packages/components/src/templates/next/components/internal/Footer/Footer.tsx
"REACH" should be in all caps
Closes [ISOM-1303](https://linear.app/ogp/issue/ISOM-1303/footer-reach-should-be-in-all-caps)
=> fix(footer): update title casing for 'Reach' to 'REACH' when isGovernment is true

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/index.ts, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/utils.ts, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/schemas/folder.ts, apps/studio/src/server/modules/folder/folder.router.ts
We need to create a base modal UI for creating folders. This PR adds this modal + updates the backend endpoint to actually do something
- use `useZodForm` to create schema for validation 
- simple modal UI following figma 
https://github.com/user-attachments/assets/a1e7295f-d13c-4fef-92f3-e29cd8f641b5
=> feat: add base modal ui

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/types.ts, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/tests/msw/handlers/page.ts
Consolidates the page listing functionality into the resource module and updates related components.
- Replaced `page.list` calls with `resource.list` calls in various components and modals.
- Updated `resource.router.ts` to include the `list` procedure previously in `page.router.ts`.
- Removed the `list` procedure from `page.router.ts`.
- Adjusted invalidation calls to use `utils.resource.list` instead of `utils.page.list`.
- Go to the base site page
- ensure that you can see pages/folders
- create a new page/folder
- the ui should be updated
This change aims to streamline the codebase by consolidating listing functionalities, reducing redundancy, and improving maintainability.
=> chore: shift page.list to resource

apps/studio/src/features/editing-experience/components/DeleteBlockModal/DeleteBlockModal.tsx, apps/studio/src/features/editing-experience/components/DiscardChangesModal/DiscardChangesModal.tsx
The modal title sometimes overflows to the close button.
**Bug Fixes**:
- Set a max width to the modal title to prevent it from overflowing to the close button.
**BEFORE**:
**AFTER**:
=> fix: prevent modal title from overflowing to close button

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/components/CmsSidebar/CmsSidebarContainer.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/src/stories/Page/SitePage.stories.tsx, apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/tests/msw/handlers/resource.ts, package-lock.json
This PR implements a new side navigation component (`CmsSideNav`) and integrates it into the CMS layout. The change updates the layout structure within the `CmsSidebarContainer`, adding support for a new sidebar section specifically for navigation purposes. Additionally, the PR includes the necessary modifications to the `AdminCmsSidebarLayout` to include the new side navigation.
=> feat: add new site side nav

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/components/Datatable/Datatable.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/server/modules/folder/folder.router.ts
- Updated focus rings in `CmsSideNav` component for better accessibility.
- Fixed pagination display issues in `Datatable` component.
- Added new route for folder details page under `/sites/[siteId]/folders/[folderId]/`.
- Adjusted button size in site page to maintain consistency.
- Updated `folder.router.ts` to include title and permalink in the response.
- Changed `p` to `m` in `CmsSideNav` component to ensure proper margin for focus ring.
- Removed unnecessary check on `totalRowCountString` in `Datatable` component.
- Added components and hooks for the new folder details page.
- Modified button size in `/sites/[siteId]/` from `xs` to `md`.
- Updated folder router to return title and permalink.
1. **Focus Ring**: Navigate to the CMS sidebar and check focus ring behavior on navigation …
=> feat: add folder views

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/index.ts, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/schemas/folder.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/folder/folder.select.ts, apps/studio/src/server/modules/page/page.router.ts
This PR introduces a folder settings modal in the folder page.
- Imported necessary components like `Modal`, `Input`, `FormControl`, etc.
- Added folder settings modal state management using `useDisclosure` hook.
- Created a new `FolderSettingsModal` component for folder settings.
- Utilized the `useZodForm` for form handling and validation.
- Implemented the mutation to save folder settings changes to the database.
- Updated schema and router to support editing folder's title and permalink.
1. Navigate to the folder page.
2. Click on the `Folder settings` button.
3. Update the title and permalink in the modal.
4. Click `Save changes` and verify if the changes are reflected.
This change adds the ability to edit the folder title and permalink directly from the folder page, enhancing the …
=> feat: add disclosure for settings

packages/components/src/presets/next/index.ts, packages/components/src/templates/next/components/complex/Accordion/Accordion.stories.tsx, packages/components/src/templates/next/components/complex/Accordion/Accordion.tsx, packages/components/src/templates/next/components/internal/BaseParagraph/BaseParagraph.tsx, packages/components/src/templates/next/components/native/Prose/Prose.tsx
Refactor Accordion component and stories for enhanced functionality and code cleanliness.
- Updated Accordion component to use local state to manage the open/close state of each accordion item.
- Replaced the `BiChevronDown` icon with a dynamic `BiMinus` and `BiPlus` icon for better UX feedback based on accordion state.
- Utilized the `tv` function for creating accordion styles for better maintainability.
- Modified `BaseParagraph` component to use `twMerge` for merging TailwindCSS classes more effectively.
- Improved `Prose` component to use a `ProseComponent` helper for cleaner JSX.
Storybook
To improve the readability, maintainability, and user experience of the Accordion component and related stories.
=> feat(components): update Accordion styling, use twMerge in Prose

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx
- we were refetching on every refocus and this led to the drawer state being reset.
- in order to avoid this, we have to avoid the refetch
- removed the fetch in drawers since it was never being used ._.
=> fix: remove fetch

packages/components/src/interfaces/internal/CollectionCard.ts, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
Make the 'lastUpdated' field optional in the 'CollectionCard' component implementations and stories.
- Updated the 'CollectionCard' interface to make 'lastUpdated' an optional field in `CollectionCard.ts`.
- Adjusted 'CollectionCard' component to conditionally render 'lastUpdated' if it's provided in `CollectionCard.tsx`.
- Updated storybook stories to test scenarios without 'lastUpdated' in `CollectionCard.stories.tsx`.
- Modified `CollectionClient.tsx` to accommodate optional 'lastUpdated' field in collection item processing.
1. Ensure the application builds successfully without any type errors.
2. Run the storybook and ensure the 'CollectionCard' component displays correctly with and without 'lastUpdated'.
3. Verify that the collection filtering and sorting functionalities work as …
=> feat(collection-item): allow dateless collection item in schema, render dateless variant

packages/components/src/templates/next/components/native/Table/Table.stories.tsx, packages/components/src/templates/next/components/native/Table/Table.tsx
Update table caption to be outside of table html tag, so the positioning is not affected by the table styles and overflow.
a11y is not compromised; it's an alternative as described in https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-aria-describedby-to-provide-a-table-summary
=> fix: table caption will scroll along with the table on horizontal scroll

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/features/dashboard/atoms.ts, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTableMenu.tsx, apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/dashboard/types.ts, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/pages/sites/[siteId]/settings.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/utils/resources.ts
This PR adds a feature to delete resources using a modal, refactors some related code for better structure, and ensures correct navigation behavior.
- Moved the `isAllowedToHaveChildren` function to `utils/resources`.
- Added a `deleteResourceModalAtom` to store the state of the delete resource modal.
- Created a new `DeleteResourceModal` component to handle the deletion of resources with confirmation.
- Updated `CollectionTableMenu` and `ResourceTableMenu` to use the new modal for deleting resources.
- Refactored routing logic to handle `RootPage` separately.
- Ensured that deletion of resources includes confirmation and proper state management.
- Added accompanying types and schemas.
1. Navigate to the resource table or collection table.
2. Attempt to delete a resource and observe the …
=> feat(studio): add delete resource functionality, update routing logic for RootPage

package-lock.json, packages/components/package.json
Got some issue with the DialogDrawer.
**Features**:
- Upgrade dependency for `@headlessui/react` for the components package.
=> fix: upgrade @headlessui/react to 2.1.2

package-lock.json, packages/components/package.json, packages/components/src/presets/next/index.ts, packages/components/tailwind.config.ts
Removed @tailwindcss/typography plugin and added tailwindcss-react-aria-components plugin to the Next.js preset instead.
- Removed @tailwindcss/typography dependency from package.json and package-lock.json
- Added tailwindcss-react-aria-components plugin to the Next.js preset configuration
- Updated the Tailwind configuration for Storybook, removing unnecessary plugins
1. Ensure that the project builds successfully without the @tailwindcss/typography plugin
2. Verify that the tailwindcss-react-aria-components plugin is working correctly in the Next.js preset
3. Check that Storybook still functions properly with the updated Tailwind configuration
The @tailwindcss/typography plugin was no longer needed, while the tailwindcss-react-aria-components was put in the wrong tailwind config.
=> fix(components): remove @tailwindcss/typography and add racPlugin inside Next preset

apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/types.ts, apps/studio/src/features/dashboard/components/RootpageRow/RootpageRow.tsx, apps/studio/src/features/dashboard/components/RootpageRow/index.ts, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/schemas/page.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/tests/msw/handlers/page.ts
- Added a new `RootpageRow` component to display root page information on the site dashboard.
- Updated the usage of the resource list query to the new `listWithoutRoot` endpoint to exclude root pages from the general resource list.
1. Introduced the `RootpageRow` component to show basic details of the root page, such as title and status (draft or published), on the site dashboard.
2. Modified the `FolderSettingsModal` to wrap `SuspendableModalContent` with a `Suspense` component using a `Skeleton` as a fallback.
3. Changed several instances of `resource.list` to `resource.listWithoutRoot` to exclude root pages from resource listings.
4. Added `getRootPage` query to the `page.router` to support fetching root page details.
1. Navigate to the site dashboard and verify that the root page …
=> fix: home styling

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/resource/resource.router.ts
Right now we don't have a `where` clause on `siteId`, leading to roto page queries being bugged and showing all pages across all sites.
add a `where` clause
=> fix: sidebar

packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx
Builds are failing when the `buttonLabel` and `buttonUrl` are not provided in the Infocols component, even though they are optional.
**Bug Fixes**:
- Conditionally render props that are optional in the Infocols component
=> fix: conditionally render props in infocols

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/schemas/collection.ts, apps/studio/src/schemas/common.ts, apps/studio/src/schemas/folder.ts, apps/studio/src/schemas/page.ts, apps/studio/src/server/modules/folder/folder.router.ts
Previously, we had a path traversal attack against us where the directory name was not generated correctly in the presence of `../..`.
to counteract this, we adopt a strict validation of only allowing alphanumeric + `-`, similar to pages.
1. use same validator throughout fe/be and for pages/collections/folder
2. for frontend, update so that disallowed characters (non alphanum) are automatically replaced with `-`
=> fix(vapt): update sanitization

tooling/build/scripts/publishing/index.ts
We have a reverse code execution issue as we allow arbitrary file writes. this fixes the problem by sanitizing the path passed to our build.
[normalize](https://nodejs.org/api/path.html#path_path_normalize_path) the filepath first so that only leading `..` is allowed. next, we strip the leading `../` because we'll be doing a `file.join` anyways. 
this still allows hidden files/folders: `/.git` is allowed, for example.
=> fix: update directory paths

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/components/Datatable/Datatable.tsx, apps/studio/src/components/Datatable/DatatablePagination.tsx, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/hooks/useTablePagination.ts, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/schemas/folder.ts, apps/studio/src/schemas/pagination.ts, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/src/stories/Page/SitePage.stories.tsx, apps/studio/tests/msw/handlers/page.ts, apps/studio/tests/msw/handlers/resource.ts
Implemented pagination for the Collection and Resource tables, improving performance and user experience for large datasets.
- Added a new `useTablePagination` hook to manage pagination state
- Updated `CollectionTable` and `ResourceTable` components to use pagination
- Modified the backend API to support offset-based pagination
- Added a new `count` endpoint for resources to get the total number of items
- Removed the `totalRowCountString` prop from the `Datatable` component
- Updated the `Datatable` component to use absolute positioning for the loading overlay
1. Navigate to a Collection or Resource table with more than 25 items
2. Verify that only 25 items are displayed initially
3. Use the pagination controls to navigate through the pages
4. Confirm that the total item count is …
=> feat: implement pagination for resource, collection, and getChildrenOf procedures

packages/components/src/interfaces/internal/Navbar.ts, packages/components/src/interfaces/internal/SearchSGInputBox.ts, packages/components/src/templates/next/components/complex/Image/Image.tsx, packages/components/src/templates/next/components/complex/Image/ImageClient.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, packages/components/src/templates/next/components/internal/SearchSGInputBox/SearchSGInputBox.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.tsx, packages/components/src/templates/next/layouts/Search/Search.tsx, packages/components/src/templates/next/layouts/Search/SearchSG.tsx, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
The `next/script` is optimised such that it will [only load once](https://stackoverflow.com/a/78479249) when the site is first loaded, then it will no longer load despite any route changes.
**Bug Fixes**:
- Force the SearchSG script to load again whenever there is a page route change.
- Add an initial height for the search results page (note that SearchSG will override this height when the script fully loads).
- Remove the search icon on the navbar if on the search results page (because the search bar is already on the page).
=> fix: force SearchSG to reload on page route change

packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx
Added z-index to the navbar dropdown menu for proper layering.
Added a `z-50` class to the dropdown menu container in the NavItem component. This ensures the dropdown appears above other page elements when opened.
1. Navigate to a page with the navbar.
2. Click on a dropdown menu item.
3. Verify that the dropdown menu appears above all other page content.
4. Check for any visual inconsistencies or layering issues with the dropdown.
This change improves the user experience by ensuring the dropdown menu is always visible and not obscured by other page elements. The z-index addition prevents potential layout issues where the dropdown might be hidden behind other components with higher z-index values.
=> fix: add z-index so navbar shows even on searchsg page

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx, packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/components/internal/Siderail/Siderail.tsx, packages/components/src/templates/next/components/internal/Siderail/SiderailList.tsx, packages/components/src/templates/next/render/render.tsx, packages/components/src/templates/next/render/renderPageContent.ts
Added missing `key` props to improve React rendering performance and resolve console warnings.
- Added `key` props to various components in multiple files:
- `KeyStatistics.tsx`: Added `key={index}` to the mapped div elements
- `ArticlePageHeader.tsx`: Changed `key={Math.random()}` to `key={index}` for list items
- `Siderail.tsx`: Added `key={index}` to the `li` element
- `SiderailList.tsx`: Moved `key={index}` from `SiderailLabel` to the parent `li` element
- Updated `renderComponent` function in `render.tsx` to accept and use an `elementKey` prop
- Modified `renderPageContent` in `renderPageContent.ts` to pass `elementKey={index}` to `renderComponent`
1. Run the application and navigate through pages with components like KeyStatistics, ArticlePageHeader, Siderail, and SiderailList
2. …
=> feat(components): add keys where required when mapping over

packages/components/src/templates/next/components/internal/Siderail/SiderailList.tsx
Removed `defaultOpen` prop from Disclosure component in SiderailList
The `defaultOpen` prop, which was set to `item.isCurrent`, has been removed from the Disclosure component in the SiderailList component.
1. Navigate to a page with a SiderailList component
2. Verify that the Disclosure component's initial state is not affected by the `item.isCurrent` value
3. Check that the Disclosure component opens and closes correctly when interacted with
Sidebar too scary when there are many children. Keep it collapsed by default and users can open if needed
=> feat: collapse all siderail sections by default

packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.stories.tsx, packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx, packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.tsx, packages/components/src/templates/next/components/internal/Link/Link.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/utils/getBreadcrumbFromSiteMap.ts
Enhanced Breadcrumb component functionality and improved sitemap navigation.
- Updated Breadcrumb component to use the Link component for consistent styling
- Added special handling for the last item in the breadcrumb, displaying it as plain text
- Modified getBreadcrumbFromSiteMap function to include the last segment of the permalink
1. Navigate to a page with a multi-level breadcrumb
2. Verify that all links except the last one are clickable
3. Confirm that the last item in the breadcrumb is displayed as plain text
4. Check that the breadcrumb accurately reflects the full path, including the current page
This change improves the user experience by:
1. Providing consistent link styling throughout the breadcrumb
2. Clearly indicating the current page as the last, non-clickable item in the …
=> feat: update breadcrumb a11y, show current path too

packages/components/src/stories/foundation/Typography.stories.tsx
Added Chromatic modes for Typography stories 
- Added Chromatic modes (desktop, tablet, mobile) to the Typography stories using `withChromaticModes`.
1. Run Storybook and navigate to the Typography stories.
2. Verify that the stories are now captured in desktop, tablet, and mobile modes in Chromatic.
- Adding Chromatic modes to Typography stories ensures consistent rendering across different device types, improving the overall design system consistency.
=> feat: capture responsive viewports for typography story

apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/server/modules/folder/folder.router.ts
Added support for creating subfolders within existing folders.
- Updated the `FolderCreateModal` component to accept a `parentFolderId` prop.
- Modified the `FolderPage` component to pass the current folder's ID as the `parentFolderId` when opening the folder creation modal.
- Removed an unused import (`ResourceType`) from the folder router file.
1. Navigate to a folder page in the studio.
2. Click on the "Create Folder" button.
3. Verify that the new folder is created as a subfolder of the current folder.
4. Check that the folder hierarchy is correctly maintained in the database and UI.
This change enhances the folder management functionality by allowing users to create nested folder structures. This improvement provides better organization capabilities for users managing complex site …
=> fix: properly create nested folder

packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx
Some of the auto-migrated pages do not have a summary so an empty string is used, but that causes a stray bullet to appear.
**Bug Fixes**:
- Only check if the summary is undefined instead of also checking if it is an empty string.
=> fix: remove stray bullet point in ArticlePageHeader

packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.stories.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx, tooling/build/scripts/generate-sitemap.js
oops forgot submit
Added a new `maxColumns` property to the InfoCards component, allowing for customizable grid layouts.
- Introduced a `maxColumns` property to the InfoCardsBaseSchema
- Updated the InfoCards component to support 1, 2, or 3 column layouts
- Modified the grid styling in the InfoCards component to accommodate the new `maxColumns` property
- Updated the IndexPage stories to use single-column layouts for InfoCards
- Adjusted the generate-sitemap script to set `maxColumns` to 1 for dangling directories
1. Review the InfoCards component in various layouts (1, 2, and 3 columns)
2. Check the IndexPage stories to ensure the InfoCards are displayed in a single column
3. Generate a sitemap and verify that dangling directories use a single-column layout for InfoCards
This change …
=> feat(InfoCards): add maxColumns styling prop

packages/components/src/templates/next/components/internal/PaginationControls/PaginationControls.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
Added an `onPageChange` callback to the PaginationControls component and implemented scrolling to top when changing pages in the Collection layout.
- Added an `onPageChange` prop to the PaginationControls component.
- Implemented the `onPageChange` callback in the Collection layout to scroll to the top of the article container when changing pages.
- Updated the PaginationControls component to call the `onPageChange` callback before changing the page.
- Adjusted the layout styles in the Collection component to improve spacing and consistency.
1. Navigate to a Collection page with multiple pages of content.
2. Scroll down the page and click on a pagination control (next, previous, or a specific page number).
3. Verify that the page scrolls to the top of the article container when changing …
=> feat: scroll to top of results on page change

packages/components/src/templates/next/components/native/Table/Table.tsx
Added tabIndex attribute to the table wrapper div for improved accessibility.
fixes https://dequeuniversity.com/rules/axe/4.8/scrollable-region-focusable a11y warning.
The `<div>` element wrapping the table now includes a `tabIndex={0}` attribute. This change allows the scrollable table container to receive keyboard focus.
1. Navigate to a page containing a table component.
2. Use the keyboard to tab through the page elements.
3. Verify that the table container can receive focus.
4. When focused, ensure that arrow keys can be used to scroll the table horizontally if it overflows.
This change enhances the accessibility of the table component. By making the scrollable container focusable, it allows keyboard users to interact with and navigate oversized tables more easily. This is …
=> feat: add tabindex to overflowing table

apps/studio/src/components/PageEditor/constants.ts, packages/components/src/interfaces/complex/Button.ts, packages/components/src/interfaces/complex/InfoCols.ts
The icons selection do not have any names to them.
**Bug Fixes**:
- Added names for the selection of icons.
- Also switch to using the placeholder image when creating new blocks.
**BEFORE**:
**AFTER**:
=> fix: add names to icons selection

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsLinkControl.tsx
rename button text from `external link` to `external` cos it was popping
=> fix: infocols

apps/studio/src/components/PageEditor/MenuBar.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/TipTapEditor.tsx
Removed blockquote functionality from the TipTap editor.
- Removed the "Quote block" option from the MenuBar component in the PageEditor.
- Removed the Blockquote extension from the TipTapEditor component.
- Removed an unused query for page content in the TipTapComponent.
1. Open the PageEditor in the studio app.
2. Verify that the "Quote block" option is no longer present in the text formatting menu.
3. Attempt to create a blockquote in the editor and confirm that it's not possible.
4. Ensure that existing content and other text formatting options still work as expected.
This change simplifies the text editor by removing the blockquote functionality. It may have been determined that this feature was not necessary for the current use case or was causing issues in the editor. Removing …
=> feat: remove blockquote functionality from editor

packages/components/src/templates/next/layouts/Collection/Collection.tsx
Updated the `getCollectionItems` function to include sorting functionality and added a new `rawDate` property to collection items so sorting can be done.
- Added a `rawDate` property to the `baseItem` object in the `getCollectionItems` function.
- Implemented a sorting mechanism for the transformed items based on the `rawDate` and `title` properties.
- Added type assertion for the `transformedItems` array to ensure it conforms to `CollectionCardProps[]`.
1. Navigate to a collection page in the application.
2. Verify that the collection items are sorted by their last updated date in descending order.
3. For items with the same last updated date, confirm they are sorted alphabetically by title.
4. Check that all collection items display correctly with their associated properties.
This …
=> feat: sort collection items by desc date (with title tiebreaker)

packages/components/src/templates/next/components/complex/Accordion/Accordion.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx
Added spacing to non-first Accordion items and included Accordion examples in the Content story.
- Updated the Accordion component's CSS to add top margin to non-first items.
- Added two Accordion examples to the Content story for demonstration purposes.
1. Run the storybook and navigate to the Content story.
2. Verify that the newly added Accordion items are visible and properly styled.
3. Check that non-first Accordion items have additional top margin.
4. Interact with the Accordion items to ensure they expand and collapse correctly.
This change improves the visual separation between Accordion items when they're not the first element in a group. It also provides concrete examples of Accordion usage within the Content component, making it easier for developers to understand and implement …
=> feat: add top margin to accordion "groups"

packages/components/src/templates/next/components/native/Table/Table.tsx
Added margin-top to non-first Table components.
Updated the Table component's outer div className to include a utility class that adds a top margin of 7 units to all Table components except the first one.
1. Render multiple Table components in a single view.
2. Verify that all Table components after the first one have a top margin of 7 units.
3. Confirm that the first Table component does not have an additional top margin.
This change improves the visual spacing between multiple Table components when they appear in sequence, enhancing readability and overall layout structure. The exclusion of the first child from this margin ensures proper alignment at the top of the container.
=> fix: add margin to table component if not first child

apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
Previously, we had unfinished scope on collections where we required breadcrumbs. Now, this PR adds said breadcrumbs in + updates folder breadcrumbs to correct styling too
1. add collection breadcrumb
2. update folder breadcrumb to have base `Home > ... > <cur folder>` styling
https://github.com/user-attachments/assets/2cbd13fc-7f00-440d-a8aa-10018d7fc9c4
=> feat: add breadcrumb to collections

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx
Change the double click flow to accordion dropdown flow as it's better for user. This change also prevents the accordion from appearing if collections/folders **do not have children**.
Closes ISOM-1340
Closes ISOM-1342
- Use a box as a wrapper element with `pos="relative"`. 
- Position the chevron (`AccordionButton`) absolutely inside the box
- reserve spacing for the chevron so that it doesn't look too weird
- add a **full width** link so on single click, we redirect that
- additionally, only show the chevon if 
- `isAllowedToHaveChildren(resourceType) === true` **and**
-  `isLoading` (we dk how many pages are in this folder, so potentially ambiguous - also disabled said chevron during load) **or**
- `pages.items.length > 0`
https://github.com/user-attachments/assets/3ec93b73-e87a-431c-b9 …
=> fix: accordion

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx
previously, we refetched on focus for the root drawer. this led to components rerendering when the window loses focus and then the user tabs back. 
in order to remediate this problem, we just remove the fetch on refocus totally. however, we do need to be sure that we do a revalidate and refetch when we know that our data is stale. (this part isn't quite done yet)
- set `refetchOnFocus: false` on the root drawer. compare hte behaviour in the 2 videos below
note the jump back
https://github.com/user-attachments/assets/6027552b-fece-42eb-b75a-429f2924f359
https://github.com/user-attachments/assets/e5366b20-59ab-4870-b11b-90d1ab6499a6
=> fix: don't refetch on focus

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx
We need to have collection settings, which is missing at present from our collections list page.
Reuse `FolderModal` and change some invalidation logic. The main chnage to invalidation logic is that we invalidate **specifically the resource id**. we also add invalidation of `collection.getMetadata` as this is what `CollectionsListPage` relies on to fetch.
- not a fan of this pattern, where we lump `collection + page` together ;--; 
- the copy needs some change too 
(if got time i'll chnage both)
https://github.com/user-attachments/assets/4d379076-d75a-46ad-8274-1dde38cc083d
=> feat: collection settings

apps/studio/src/features/editing-experience/components/form-builder/renderers/TipTapEditor.tsx
**single-words** could overflow and cause bad styling. (think like 100++ characters long **without white space**)
add a `maxW`
=> chore: add max-w

apps/studio/src/components/Datatable/Datatable.tsx
Previously, we showed an empty pagination when there are no items in the collection. To avoid this, we will do a conditional render only if `totalRowCount` is defined and greater than 0.
remove pagination if total row count is 0
=> fix: datatable

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/server/modules/resource/resource.router.ts
The three dots didn't do anything previously. This PR adds a new functionality to update teh 3 dots to go back to parent. This only works for folders >1 level deep (as if they're 1 level deep, the immediate parent is the root folder, so don't need 3 dots)
Closes ISOM-1433
1. add new endpoint (`Resource.getParentOf`) 
2. invalidate `move` endpoint. we only need to invalidate this because this is the only end point that can chnage the parent. 
https://github.com/user-attachments/assets/7cca9ce9-deab-487e-807b-ef6e7e37a34d
=> fix(ui): update three dots to go to parent

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/constants/formBuilder.ts, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
Component is called Prose component now.
**Bug Fixes**:
- Rename "Prose component" to "Text component"
=> chore: rename prose component to text component

apps/studio/src/features/editing-experience/components/PublishButton.tsx, tooling/build/scripts/publisher.sh, tooling/build/scripts/publishing/.env.template, tooling/build/scripts/publishing/README.md, tooling/build/scripts/publishing/index.ts, tooling/build/scripts/publishing/package-lock.json, tooling/build/scripts/publishing/package.json, tooling/build/scripts/publishing/queries.ts, tooling/build/scripts/publishing/tsconfig.json
Add a new script (`publisher.sh`) and supporting TypeScript code to clone the `isomer` repo, fetch site data, and build schemas.
- Added `publisher.sh` to handle the publishing workflow, including cloning the repository, building the components, fetching from the database, and generating the site.
- Script includes a step to run preBuild and build scripts from remote.
- Created supporting TypeScript files to fetch and write site data (navbar, footer, config) and process resources from the database.
- Added `.env.template` for environment variables.
- Added `package.json` and `package-lock.json` for dependencies.
- Configured `tsconfig.json` for TypeScript settings.
1. Set up the required environment variables in `.env` based on `.env.template`.
2. Run `publisher.sh` and verify that it …
=> ISOM-1111: add publishing scripts

apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/resource/resource.router.ts
We previously did a simplified UI for our breadcrumbs, which was merged in as a baseline. This PR adds more comprehensive states to our breadcrumb + simplifies # of queries from 2 -> 1
1. use expression builder from kysely to do a nested `SELECT` statement. this allows us to flatten the query into a single one. 
2. we previously had only 2 states, `Home -> ... -> Current` and `Home -> current`. now, we have expanded the number of states to 3: 
- `Home -> .. -> parent -> current` 
- `Home -> parent -> current`
- `Home  -> current` 
We do this by going from. most specific (top case) to bottom and via checkign of the grandparent. If the grand parent exists, we know it is the first case cos `Home` is indicated via `parentId === null` …
=> refactor(breadcrumbs): display more states + single query fetch

apps/studio/src/components/PageEditor/MenuBar.tsx, packages/components/src/interfaces/native/Table.ts
Enhanced tiptap editor perf using useMemo.
Allow table column headers.
- Added toggle options for header column and header row in the table menu
- Implemented useMemo for performance optimization of menu items
- Updated TableContentRowSchema to allow header cells within table rows
- Added new icons for table header toggles (RiLayoutColumnFill, RiLayoutRowFill)
1. Open the page editor and insert a table
2. Verify that new options for toggling header column and header row are available in the table menu
3. Test the functionality of these new toggle options
4. Create a table with mixed regular and header cells in a single row
5. Ensure that the editor correctly handles and displays the mixed cell types
This change improves the flexibility and usability of tables in the page editor. By …
=> feat: perf improvements to tiptap menu, allow column headers in table

.github/workflows/chromatic.yml, .github/workflows/ci.yml
Integrated Graphite CI Optimizer to improve CI workflow efficiency.
Also save some money rerunning chromatic stuff on rebases
- Added a new `optimize_ci` job in both `chromatic.yml` and `ci.yml` workflows.
- Modified the `ui` and `studio` jobs in `chromatic.yml` to depend on the `optimize_ci` job.
- Updated the `test` job in `ci.yml` to depend on the `optimize_ci` job.
- Added conditional checks to skip jobs based on the Graphite CI Optimizer output.
1. Push a commit or create a pull request to trigger the CI workflows.
2. Observe the `optimize_ci` job running first in both workflows.
3. Verify that subsequent jobs are skipped or executed based on the Graphite CI Optimizer's output.
4. Ensure that the existing functionality of the CI pipelines remains intact.
This change aims to optimize …
=> chore(ci): add graphite ci optimisation

apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
There was a missing folder id in the page creation modal, so pages being created were being created at root. 
add the folderId back in
**BEFORE**:
**AFTER**:
=> fix: add missing folder id

packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
Adjusted padding breakpoints for improved responsive design in Masthead and Navbar components.
- In the Masthead component, changed the `lg:px-10` class to `md:px-10` for the RestrictedHeaderBar.
- In the Navbar component, updated the `lg:px-10` class to `md:px-10` for the navbar container.
1. Open the application and navigate to pages containing the Masthead and Navbar components.
2. Resize the browser window to various widths, particularly focusing on the transition between mobile and tablet views.
3. Verify that the padding adjusts correctly at the medium (md) breakpoint instead of the large (lg) breakpoint.
4. Ensure the layout looks consistent and properly aligned across different screen sizes.
This change aims to improve the responsive behavior of the Masthead and Navbar components. …
=> fix: update tablet px of masthead and navbar

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx
adding a block to our state and then exiting the editor without doing anything cause a wrong block to be created. this leads to issues later when dragging and dropping as the editor will attempt to update the blob/resourceid of a block that doesnt exist
this is a pretty complicated fix so i'll try to explain as much detail as possible. 
1. the root cause of the bug is because we preemptively update the page state in our base `ComponentSelector`. This is to allow our components to use the page state to update the block. because of this, however, when we exit editing, we reset to the state **with the block**. ie, the sequence of events is as follows:
- page state initially: []
- page state after clicking on add component: [[]], where the inner array denotes teh initial empty state of the …
=> fix(ui): adding a new block and exiting without saving causes a block to be wrongly created

packages/components/src/hooks/useBreakpoint.ts, packages/components/src/templates/next/components/internal/PaginationControls/Pagination.tsx, packages/components/src/templates/next/components/internal/PaginationControls/PaginationControls.stories.tsx, packages/components/src/templates/next/components/internal/PaginationControls/PaginationControls.tsx
Improved pagination controls responsiveness and added mobile/tablet view testing.
- Adjusted gap spacing in pagination content for better mobile display
- Added mobile and tablet view testing for the "ManyPages" story
- Implemented responsive sibling count for pagination range based on screen size
1. Run the Storybook for PaginationControls
2. Check the "ManyPages" story in mobile and tablet views
3. Verify that the pagination controls adjust appropriately for different screen sizes
4. Ensure that fewer sibling pages are shown on mobile compared to tablet/desktop views
To enhance the user experience on mobile devices by optimizing the pagination controls for smaller screens. This change ensures that the pagination component remains functional and visually appealing across various device …
=> feat: show less pagination siblings in mobile

.github/workflows/deploy_staging.yml, .github/workflows/deploy_vapt.yml
There is a desync on the OIDC role ID that GitHub uses to authenticate with AWS.
**Bug Fixes**:
- Fix the OIDC role ID that we are currently using in Pulumi.
=> fix: update AWS GitHub OIDC role

apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
previously, clicking on the menu items to delete resources did not do anything inside folders. 
Closes ISOM-1486
1. add the delete resource modal in
https://github.com/user-attachments/assets/87097d71-a3d3-4c66-b431-c1def4ea2a88
=> fix: add delete resource modal in folders

apps/studio/src/lib/routes.ts
we removed the `/dashboard` page previously but was still directing users there. 
Closes ISOM-1455
update the constant to `/`
https://github.com/user-attachments/assets/0ab634f0-fcc5-4fb2-9aa8-59f24455e061
=> fix: update dashboard route

apps/studio/src/pages/sites/[siteId]/settings.tsx
1. bad contrast of infobox bg against base bg
2. smaller widths causes the settings text to be squished against the side
Closes ISOM-1530
Closes ISOM-1528
1. change to `warning`
=> fix: change infobox to warning

apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx
see ticket for a description of the problem
1. invalidate the query that the sidebar uses to fetch children
2. invalidate the count so that pagination updates
https://github.com/user-attachments/assets/e26ff969-33db-4f1c-b2d5-ec26b6316418
=> fix: invalidate collections

apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx
previously, we did not invalidate the query that our sidebar used to fetch children of a folder when we created a folder. this led to the sidebar not updating whenever we created another folder.  
1. invalidate the query used to fetch the children of a folder whenever we create another folder
2. invalidate the `count` query used for pagination whenver we create a folder. this is so that the count gets updated correctly and the pagination will update to show the newest index if required
https://github.com/user-attachments/assets/0772bfbe-66dd-48fe-8037-9486ceff3b76
=> fix(folders): invalidate queries on creation 

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
previously, the save wasnt disabled when the state of the field was invalid. 
1. restrict the 2 fields to their respective max length, so that they cannot exceed the given length
2. for permalink, we already transform every invalid input to `-` so we know that the field's value will always be valid
because of this, we dont need to disable save as the permalink and title will always be of a valid length and the permalink will consist only of alphnumeric characters and `-`
https://github.com/user-attachments/assets/9631c306-571a-423b-8104-5e413fb30328
=> fix(folder settings): restrict input fields to max length

apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx
see ticket
1. add max length property on `Input` so it will auto coerce to the appropriate length for us
https://github.com/user-attachments/assets/68bd65b7-36bb-4bd8-802a-5dd6d02dd5cd
=> fix: add max length property on input 

packages/components/src/templates/next/components/native/Paragraph/Paragraph.stories.tsx, packages/components/src/utils/getTextAsHtml.ts
There is an issue with how the HTML is generated by components when it comes to nested marks.
Closes ISOM-1532
**Bug Fixes**:
- Change the way we generate the HTML from the JSON prose content so that we are able to combine multiple text nodes with the same link mark.
=> fix: HTML generation from prose JSON content

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/server/modules/resource/resource.router.ts
Right now, we can move collections from the dashboard. this should not be allowed as only pages and folders can be moved.
1. Filter the `resource.type` on the frontend
2. add a `where` clause on the backend so we only allow move on `Page/Folder`
https://github.com/user-attachments/assets/22515214-e3e3-4adf-a7d0-c676b0d0b8e0
=> fix: filter for page and folder

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/types.ts, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/tests/msw/handlers/page.ts
currently, the invalidation logic is wrong for moving items. this results in the ui not updating after we move an item from 1 folder to another. 
Closes ISOM-1483
Closes ISOM-1461
1. retrieve parent id from backend and pass it into the table so that each initial click will have access to the parent id
2. update the type of the atom and set parent id on each click of destination so that the move item knows the (original) parent id of the move item 
3. invalidate both destination and origin folder queries so that the ui will appear correct. the origin folder is `moveItem.parentId` and the destination is given by `moveDest.resourceId`
https://github.com/user-attachments/assets/73d6d807-8844-4b11-b7dd-a3c96a39b1ce
https://github.com/user-attachments/assets/5073218a-f844-4bf7-b4b6-3f74d9f12533
=> fix(move): perform UI invalidations correctly

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapComponent.tsx
Previously, deletes weren't persisted to the db at point of deletion - the users had to drag and drop for it to persist to db.
- write to the db on delete
- add a toast saying `Changes saved` for both updates + delete 
https://github.com/user-attachments/assets/14fefec2-e751-48af-ac69-3e2fe511801a
- confirming w @sehyunidaaa  on final wording/settings for toast
=> fix: save changes to db after delete

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20240909103759_cascade_deletions_for_resource/migration.sql, apps/studio/prisma/schema.prisma
**THIS IS A ONE LINE PR!!! autogen code cause the extra lines**
Previously, our deletes are not cascaded - this means that when we delete a folder, for example, the child pages and folders are not deleted. 
1. add a constraint to the table's relation so that it does a `CASCADE` on delete
(note, after running migration)
https://github.com/user-attachments/assets/2e30b61e-4719-44e9-bb12-d20b8f3fc916
i **did not** delete the blob as we want to archive it presumably and also for auditing purposes
=> fix(cascades): update schema so that deletes are cascaded

apps/studio/src/features/editing-experience/hooks/useTextEditor.ts
(elaborating on ticket)
Previously, when we paste something containing a `hardbreak` into `Heading`, this causes our schema to crash because our schema doesn't accept hardbreaks in heading but tiptap does
```html
Heading
|_ br
````
now that we've split up the editor into different hooks, the only one that accepts `Heading` is `useTextEditor` so we configure this to accept `Hardbreak` 
To ensure that this problem doesn't occur again, we need to check that other components in the schema that don't accept `hardbreak` will also disallow the `hardbreak` from being a child of these other components in the tiptap editor itself
1. ensure that the content for `Heading` is only `text*`
2. i did the check for other components as well (see attached video) 
```            
Type.Ref(DividerSchema), …
```
=> fix: crashes when we paste hardbreak into heading

packages/components/src/interfaces/native/Text.ts
Previously, we disallowed `target=""` in our schema. This causes a crash when pasting links which contain such a target.
1. relax component schema to allow this
https://github.com/user-attachments/assets/c619ce23-8414-42be-8edc-7950fdc31f6c
=> fix: allow self links

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx
Improved layout and scrolling behavior of editor drawers.
- Updated the layout of ComplexEditorStateDrawer, HeroEditorDrawer, MetadataEditorStateDrawer, and TipTapProseComponent
- Replaced fixed height with flex layout and added overflow scrolling to content areas
- Removed sticky positioning from bottom action bars
1. Open various editor drawers (Complex, Hero, Metadata, and TipTap Prose)
2. Verify that the content area scrolls independently when content exceeds the drawer height
3. Ensure the bottom action bar remains visible and doesn't overlap content
4. Check that all functionality (editing, saving, deleting) works as expected
=> fix: sticky bottom overflows in edit resource drawers

.github/workflows/ci.yml
Updated the GitHub Actions upload-artifact action to version 4. v2 is [deprecated](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/).
The CI workflow file has been modified to use the latest version of the `actions/upload-artifact` action. Specifically, the version has been updated from v2 to v4.
1. Trigger the CI workflow by pushing a commit or creating a pull request.
2. Verify that the "Upload test results" step completes successfully.
3. Check that the test results artifact is uploaded and accessible.
v2 is deprecated
=> ci: update upload-artifact action to version 4

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx
we were previously using the wrong property for the `Switch` causing UI errors
use correct property
https://github.com/user-attachments/assets/af232e2e-88bd-4465-8fce-f89ecb56d2b3
=> fix(switch): add the property correctly

apps/studio/src/components/PageEditor/MenuBar/TableMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/TextMenuBar.tsx
When we lose focus at present, the dropdown goes to the default title, which is `Heading options` at present. This isn't ideal because it takes up 2 lines
Change copy to `Text styles` (cleared with @sehyunidaaa)
=> chore: update naming

tooling/build/amplify/create-app.js
Due to the switchover of all links to use LinkComponent (which is essentially Next.js Link), it has resulted in PDF links being unable to be opened due to the way we set up the redirect rules on Amplify.
**Bug Fixes**:
- Update Amplify's 404 redirect rule to exclude `.txt` files.
- This is a special file that Next.js uses to perform pre-fetches and if it encounters a 404, the link is treated as per normal.
- However, Amplify's 404 redirect means a 302 response is returned instead, which Next.js misinterprets to be a valid internal page (and not resource) and brings the user to the actual path (which would be /404.html in this case, because that is the path that was returned during the pre-fetching).
- The /404.html comes about due to the way we original set up the …
=> fix: prevent 404 redirects for prefetches of assets

apps/studio/src/components/PageEditor/constants.ts, packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.stories.tsx
The max columns property for the InfoCards component does not specify a title and uses numbers instead of strings, which causes issues in rendering for the form builder.
**Bug Fixes**:
- Added a title for every option in the `maxColumns` property, which is displayed for the user in the form builder.
- Switch number to string, as we don't actually support using numbers as part of an `anyOf` selector (no real benefit of using numbers here anyway, since this is really a variant).
- Added the default value to the `DEFAULT_BLOCKS` constant so the value is defined on the form builder.
- Moved the `SingleCardNoImageSchema` to before the image fields, as the first field (title) is used as the title of the card. Otherwise, the URL to the image is used instead, which can be …
=> fix(InfoCards): use string union and add title for maxColumns

CODE_OF_CONDUCT.md, CONTRIBUTING.md
As Isomer prepares for use in production, we have to prepare also for code contributions to our public codebase.
Add Code of Conduct and Contributing guides to provide clarity on how contributions can be made
=> docs(legal): add CoC and Contributing guide

apps/studio/src/components/PageEditor/ComponentSelector.tsx, apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/EditPagePreview.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/icons/Contentpic.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/templates/layouts/PageEditingLayout.tsx, apps/studio/tests/msw/handlers/page.ts
Redesigned the component selector for adding new blocks to pages, improving the user interface and experience.
- Restructured the ComponentSelector component to use a more organized layout
- Introduced new constants for allowed blocks based on page type (homepage, content, article)
- Updated the UI to display blocks in a vertical list with improved visual hierarchy
- Added more detailed descriptions and usage information for each block type
- Implemented context-aware block selection based on page type
- Created new icons and components for better visual representation of blocks
- Updated the EditPagePreview component to use the new EditorDrawerProvider
- Added new stories for testing different page types (article, content) in edit mode
1. Navigate to the edit page for different page …
=> feat: redesign ComponentSelector and add page-specific block options

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/Drawer/DrawerHeader.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx
Introduced a new DrawerHeader component and refactored existing drawer components to use it.
- Created a new `DrawerHeader` component in `Drawer/DrawerHeader.tsx`
- Refactored `ComplexEditorStateDrawer`, `HeroEditorDrawer`, `MetadataEditorStateDrawer`, and `TipTapProseComponent` to use the new `DrawerHeader`
- Removed redundant imports and simplified code in the refactored components
- Replaced lodash imports with specific function imports to optimize bundle size
1. Open the editing experience for various components (Complex, Hero, Metadata, and Prose)
2. Verify that the drawer header appears consistent across all components
3. Test the back button functionality in each drawer
4. Ensure that the discard changes modal appears when appropriate
This change improves code consistency and …
=> refactor: extract DrawerHeader component

apps/studio/src/server/modules/resource/resource.router.ts
Previously, when moving children, we got all resources but omitted a `where` clause for `site`. This allows us to move resources from 1 site to another
add a `where` clause
=> fix: select only children of current site

apps/studio/src/components/AppNavbar.tsx
There's a link to edit the user profile in the app navbar but that page does not exist currently.
- Remove the link to edit the user profile.
=> chore: remove edit user profile link in navbar

apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx
Added `updatedAt` to the EditorDrawerContext and simplified the PageEditingView component.
- Extended the DrawerContextType to include `updatedAt`
- Added `updatedAt` as a prop to EditorDrawerProvider
- Removed unnecessary props from PageEditingView component
- Updated PageEditingView to use context for `permalink`, `siteId`, and `updatedAt`
- Removed `page` prop from Preview component in PageEditingView
1. Navigate to the page editing view for a site
2. Verify that the page loads correctly and all functionality remains intact
3. Check that the preview updates properly when changes are made
4. Ensure that the `updatedAt` information is correctly displayed and updated
This change simplifies the component structure by moving more data into the EditorDrawerContext. It reduces prop drilling …
=> feat: use page state from context instead of from query

apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/Preview.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/schemas/site.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/utils/sitemap.ts
The sitemap is not being dynamically generated right now, so our preview's siderails are incorrect.
**Features**:
- Add the ability to generate a sparse sitemap that only includes resources that revolve around the current page that the user is editing.
- For other types of previews (e.g. when creating pages), we show a basic version for now but we can potentially expand to provide a sparse sitemap but with the resource itself being dynamically updated upon user inputs.
- The permalink passed to the preview is also updated to provide the full path from root, instead of only providing the slug of the page.
**BEFORE**:
**AFTER**:
=> feat: dynamically generate the sitemap for preview

apps/studio/src/features/editing-experience/components/LinkEditor/LinkHrefEditor.tsx, apps/studio/src/features/editing-experience/components/LinkEditor/LinkTypeRadioCard.tsx, apps/studio/src/features/editing-experience/components/LinkEditor/LinkTypeRadioContent.tsx, apps/studio/src/features/editing-experience/components/LinkEditor/constants.ts, apps/studio/src/features/editing-experience/components/LinkEditor/index.ts, apps/studio/src/features/editing-experience/components/LinkEditor/utils.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsLinkControl.tsx
Preparing to abstract out this functionality so that we can support adding links inside the Tiptap editor.
- Abstract out the link adding functionality to a separate component. No change in actual functionality.
=> ref: separate out link type selection functionality

apps/studio/prisma/seed.ts
Updated the permalink for the home resource in the seed data.
Changed the permalink value for the home resource from "home" to an empty string ("") in the seed.ts file.
1. Run the database seeding process
2. Check the Resource table in the database
3. Verify that the home resource has an empty string as its permalink
This change ensures that the home page has an empty permalink, which is typically the expected behavior for the root page of a website. It allows the home page to be accessed at the root URL (/) rather than at /home, improving URL structure and SEO.
=> fix seed permalink for root page

apps/studio/src/schemas/auth/email/sign-in.ts, apps/studio/src/server/context.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/utils/email.ts
Updated email validation to accept all valid email addresses instead of only .gov.sg emails.
- Modified `emailSignInSchema` to use `isValidEmail` instead of `isGovEmail`
- Updated error message for invalid email addresses
- Added `isValidEmail` function to validate any valid email address
- Removed unused import of `generateUsername` in email router
- Added `disableCache: true` to GrowthBook context initialization
1. Attempt to sign in with various email addresses:
- A valid .gov.sg email
- A valid non-.gov.sg email
- An invalid email address
2. Verify that all valid email addresses are accepted, regardless of domain
3. Confirm that invalid email addresses are rejected with the new error message
This change allows for a broader user base by accepting all valid email addresses, not just …
=> Remove .gov.sg email restriction and update email validation

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/utils/resource.ts
The edit page breadcrumb currently is using dummy data.
**Features**:
- Fetch the correct data for the edit page breadcrumb (which is the current page title)
- If the page's parent folder is not the root folder, show the immediate parent of that page as a link (this is mainly for collections).
**BEFORE**:
**AFTER**:
=> feat: fetch proper data for edit page breadcrumb

packages/components/src/templates/next/components/internal/Notification/Notification.tsx, packages/components/src/templates/next/components/native/Heading/Heading.tsx, packages/components/src/templates/next/components/native/Paragraph/Paragraph.tsx, packages/components/src/templates/next/components/native/Prose/Prose.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx, packages/components/src/utils/getTextAsHtml.ts
Hard breaks are being rendered in headings.
**Bug Fixes**:
- Add a flag to prevent the empty hard break from being rendered in the heading.
=> fix: omit hard breaks when rendering headings

apps/studio/src/components/PageEditor/MenuBar/AccordionMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/ProseMenuBar.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/TipTapEditor/TiptapProseEditor.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAccordionTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsProseControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/index.ts, apps/studio/src/features/editing-experience/hooks/useTextEditor.ts
Currently, our contentpic has no applicable renderer as it's using the default `Prose` schema and now, the various editors have been split up into their own specialised editor
1. define a **default** editor (this will be used when we use something with `prose` as the format)
2. add the testers into `FormBuilder`
1. add another specialised editor - i think we'd rather have classes of editor than specialised editor for each component. all our previous components have had no overlap so far so it's been pretty annoying...
https://github.com/user-attachments/assets/6074a46d-e2b5-472b-8a34-46b04c94f0e9
=> fix(contentpic): add a renderer

apps/studio/public/assets/css/preview-tw.css, packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/Hero/Hero.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx, packages/components/src/templates/next/components/complex/Infobar/Infobar.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.tsx, packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx, packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.tsx, packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx, packages/components/src/templates/next/layouts/Collection/CollectionPageHeader.tsx
Titles in our components and headers are overflowing without breaking the words.
Fixes ISOM-1519.
- Added validation to set maximum number of cards in the InfoCards component to be 6.
**Bug Fixes**:
- Add `break-words` for headers.
- Standardise all component-level headers to be `<h2>`.
=> fix: break words on overflow for titles and use h2

apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/tests/msw/handlers/page.ts, apps/studio/tests/msw/handlers/resource.ts, apps/studio/tests/msw/handlers/sites.ts
Storybook tests failing due to missing msw handlers for newly added procedures. This PR adds those missing mocked procedures in.
=> fix(studio): add missing msw handlers for edit page stories

apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx
The tab labels were not centered. This PR centers it.
=> feat: center tab labels in SiteEditNavbar

apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/server/modules/auth/email/email.router.ts
previously, we swapped the method for determining the permalink. unfortunately, this method fetches the full permalink which contains invalid characters (`/`). this led to the save being disabled until the field is typed.
additionally, `isDirty` wasn't quite fitting our use case and we have to check against the `dirtyFields` of the `formState` instead. this showed up as edits not working until the second blur.
1. change the api of the component to accept a `prefix`. this is the front portion of hte `permalink`
2. update the full permalink retrieved to be 2 portions, the prefix and the current url
3. updat the component so that input edits only the last portion 
https://github.com/user-attachments/assets/b826990e-9be4-4089-a3c0-70a0d43b85ec
=> fix(page-settings): change field generation

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx
currently, the four modals for creation of pages/folders don't have a standardised way of treating input. this PR fixes that.
1. input now has `maxLength` set so users cannot go beyond `maxLength`
2. input now auto transforms illegal characters
because of #2, if users have illegal characters in the middle, they'll add the characters there, then their cursor will move to the end (eg: aaa -> a<space>aa, cursor at index 1 -> a-aa<cursor>, cursor at ending position)
ok with this trade-off because it standardizes all input field treatment and we don't have error message atm for the input fields hwen illegal characters have been entered.
=> chore(modals): standardise input field

apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
previously, titles and breadcrumbs can overflow, which blocks off content, leading to bad ux
Closes ISOM-1468
Closes ISOM-1480
1. define overflow styling and a max width for breadcrumbs so that on overflow, the last breadcrumb will truncate nicely
2. set overflow styling on the container for the title
https://github.com/user-attachments/assets/9acdcdb1-662e-40e2-ac0b-c67e8bdb5636
=> fix(overflow): breadcrumbs and titles can overflow leading to bad ux

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/constants.ts
Fixes ISOM-1561.
**Bug Fixes**:
- Omit placeholder_no_image.png asset when uploading images.
=> fix: omit uploading of placeholder image

apps/studio/src/components/PageEditor/LinkEditorModal.tsx, apps/studio/src/components/ResourceSelector/ResourceItem.tsx, apps/studio/src/components/ResourceSelector/ResourceSelector.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/resource/resource.router.ts
When selecting the link in the link selector, it will always reset to the root folder.
**Bug Fixes**:
- Retrieve the ancestry information about the selected resource, so that we can construct the parentId stack on load.
- Add feedback to the user about the actual page permalink that is being selected.
- Add a maximum height and an overflow for the resource selector.
=> fix: directly jump to link parent folder in selector

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
previously, we crashed because we tried to read from undefined. this resulted because we did a bad `setState` when we failed.
we should not set the whole page state because it is the whole blob. since we send only the `content` (ie, the blocks) over to the backend, we should set only that key.
1. set only the `content` key when we fail the mutation. this allows the toast to show and for the users to not lose data
https://github.com/user-attachments/assets/77d3ce32-2c4e-4a9c-9380-7bf2d8876bf0
=> fix: crashes when there are other edits

apps/studio/prisma/seed.ts, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsAnyOfControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsBooleanControl.tsx, apps/studio/src/features/editing-experience/data/articleLayoutPreview.json, apps/studio/src/features/editing-experience/data/collectionPdfPreview.json, apps/studio/src/server/modules/collection/collection.service.ts, apps/studio/src/server/modules/page/page.service.ts, packages/components/src/templates/next/layouts/Article/Article.stories.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.stories.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.stories.tsx, packages/components/src/templates/next/layouts/Search/Search.stories.tsx, packages/components/src/types/page.ts, tooling/template/app/not-found.tsx
we want to update the copy for both components and also, set `noIndex` to becoming required
1. update schema for pages so that `noIndex` is now a required property
2. various changes in our app so that we default to `noIndex: false` (previously was undefined)
3. update `ajv` instance to use `default`
=> chore(noIndex and meta): update copy and set noIndex to required

apps/studio/src/components/PageEditor/MenuBar/AccordionMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/MenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/TextMenuBar.tsx
took this up w/ sehyun separately because our table ui looks bad. in order to save space and avoid overflowing into 2 rows, our table is now a vertical list (similar to the ol/ul options)
1. change the huge list of table into a vertical list for `Text` and `Accordion`. the other editors **do not** have tables allowed as a legal extension, so this doesn't apply.
https://github.com/user-attachments/assets/a27dfad4-bc53-4c2d-a732-ce255dd2aa8d
it looks better but each click now causes the dropdown to disappear. guess here is that users use this rarely, so we're ok with the dropdown menu but we'd benefit from testing this w/ our users
=> refactor(table): use dropdown list for table

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx
- Removed unnecessary `onRejection` callback from the image upload component
=> fix: remove error toast on rejection

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsArrayControl.tsx
Currently, when we have an article, theere is no applicable renderer for the heading as it is an array of primitives.
1. add a or statement so that object or primitive arrays are both caught by this tester.
https://github.com/user-attachments/assets/b28cdb7c-9b27-42d3-b81c-e244ef6ee671
pending design to confirm if this is what they want...
=> chore(arraycontrol): add extra tester so we have a renderer

apps/studio/src/components/TabLink.tsx, apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/CollectionTable/CollectionTableMenu.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/dashboard/components/ResourceTable/TitleCell.tsx, apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditPageSettings.stories.tsx, apps/studio/src/utils/resource.ts, apps/studio/tests/msw/handlers/page.ts
Added a new page settings view and improved navigation between edit and settings pages.
- Created a new `TabLink` component for consistent tab-like navigation
- Added a new `/settings` page for editing page settings
- Moved page settings form from the edit page to the new settings page
- Updated the `SiteEditNavbar` to use `TabLink` for navigation between edit and settings views
- Implemented `getResourcePermalinkTree` and `getPermalinkTree` API endpoints
- Updated resource utility functions for better link generation
1. Navigate to a page editing view
2. Verify that the "Edit" and "Page Settings" tabs are present and functional
3. Click on "Page Settings" to access the new settings page
4. Test editing page title and URL on the settings page
5. Verify that changes are saved and reflected …
=> feat: add page settings route and separate edit/settings views, link to page in dashboard

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx
previously, we didnt do a filter on the data retrieved from backend, which led to self-moves being possible (ie, i move a folder to itself)
1. filter by `resourceId` on the frontend
- this is safe to do because the method invoked on the backend returns strictly `folder`
- so for pages, the condition will be `false` by default (this is paginated so run time isn't an issue)
- for folders, we disallow move to self (and children) and because we start move from `root`, we'll never to able to get to the folder and its associated children
2. backend already has an error message here for self moves so it's still disallowed but this error message wouldn't be seen by law abiding citizens who use our frontend
https://github.com/user-attachments/assets/8bcd295f-6ce8-4cc3-b3a0-416b02dbce81
=> chore: add filter so that we cannot do self-moves

packages/components/src/types/page.ts
We use `format: image` to determine if the image control should be rendered for Studio, but that is missing for article page header and the ref items.
**Bug Fixes**:
- Add the `format: image` key in the schema for the article page header and the ref items schema.
=> fix: add missing format image for articles

apps/studio/package.json, apps/studio/prisma/custom/install.ts, apps/studio/prisma/custom/migration.sql, apps/studio/prisma/migrations/20240917043702_add_resource_indexes_and_unique/migration.sql, apps/studio/prisma/migrations/20240917045344_custom_migration/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.router.ts
Has breaking changes!!!!
Also closes ISOM-1559
May fail to apply on any databases that has duplicate permalinks. 
- Added indices to the Resource table in the database schema to optimize query performance
- Created a unique constraint on the `siteId` and `permalink` columns of the Resource table
=> feat: add first cut indices for resource table, unique constraint on permalinks

apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, apps/studio/src/server/modules/page/page.service.ts, packages/components/src/utils/isExternalUrl.ts
Closes ISOM-1569.
**Bug Fixes**:
- Ensure that we set `undefined` rather than empty string, as an empty string is a valid value for the schema whereas undefined isn't.
- This also applies to the content/article page summary, otherwise the schema validation of the page will fail.
=> fix: prevent empty image URL string

apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/trpc.ts
Note: This whitelist via GB is a temp measure till we get permissions model rolled out
Prevent local dev from being coupled with growthbook
This PR modifies the email authentication process to only check for whitelisted users in production environments.
- Email authentication now only checks for whitelisted users in production environments
- Improved security by restricting access in production while allowing easier testing in non-production environments
- Test email login functionality in both production and non-production environments
- Verify that whitelisted user checks are only performed in production
- Ensure unauthorized users are still blocked in production
- Removed test case for non-government email addresses
=> Restrict whitelist check to production environment

packages/components/src/interfaces/internal/CollectionCard.ts, packages/components/src/templates/next/components/complex/Contentpic/Contentpic.tsx, packages/components/src/templates/next/components/complex/Hero/Hero.tsx, packages/components/src/templates/next/components/complex/Image/Image.stories.tsx, packages/components/src/templates/next/components/complex/Image/Image.tsx, packages/components/src/templates/next/components/complex/Image/ImageClient.tsx, packages/components/src/templates/next/components/complex/Image/index.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.tsx, packages/components/src/templates/next/components/complex/index.ts, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
Not all the components that use image is aware of the `assetsBaseUrl`.
**Bug Fixes**:
- Make all image usages aware of the `assetsBaseUrl`.
=> fix: make all images aware of assetsBaseUrl

apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, packages/components/src/engine/metadata.ts, packages/components/src/schemas/components.ts, packages/components/src/schemas/index.ts, packages/components/src/schemas/main.ts, packages/components/src/schemas/meta.ts, packages/components/src/schemas/page.ts, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.stories.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.stories.tsx, packages/components/src/templates/next/layouts/Search/Search.stories.tsx, packages/components/src/types/index.ts, packages/components/src/types/meta.ts, packages/components/src/types/page.ts, packages/components/src/types/schema.ts, tooling/template/app/not-found.tsx
The page object is mixed with some page metadata, which is difficult to separate on the Studio.
- No schema changes are needed because the new `meta` object is optional and hence, backward compatible.
- Refactor all page metadata into a new `meta` object, which is exposed by `getLayoutMetadataSchema`. This object is set to be optional for all page layouts for now to minimise the need to upgrade existing schemas.
- The remaining `page` object is exposed by `getLayoutPageSchema`, which replaces the one currently used in MetadataEditorStateDrawer.
- Additionally, if the page meta description is not provided, the article/content page summary is used for those layouts.
**Notes**:
- At this stage, the page metadata cannot be edited. They will need to be …
=> ref: separate metadata from page object

packages/components/src/interfaces/internal/Navbar.ts, packages/components/src/schemas/meta.ts, packages/components/src/schemas/page.ts, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx, packages/components/src/templates/next/components/internal/Breadcrumb/Breadcrumb.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx, packages/components/src/templates/next/components/internal/Siderail/Siderail.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx, packages/components/src/templates/next/layouts/NotFound/NotFound.tsx, packages/components/src/templates/next/layouts/Search/Search.tsx, packages/components/src/templates/next/render/render.tsx, packages/components/src/templates/next/render/renderPageContent.ts, packages/components/src/types/schema.ts, packages/components/src/types/sitemap.ts
We don't provide layout information to the components currently, but there is a growing need to render components slightly differently depending on the layout that it is being rendered in (e.g. homepage vs content page.
**Features**:
- Provide layout information to the components so they are aware of the layout context they are rendering in.
- Standardised all LinkComponent and ScriptComponent to not provide a fallback value, and leave it to `renderLayout` to provide one.
=> feat: provide layout info to components

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
Fixes ISOM-1581.
**Features**:
- Add the "Add a new block" big button when the page state is empty.
=> feat: introduce big add block button when empty

apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/schemas/page.ts, apps/studio/src/server/modules/page/page.router.ts, packages/components/src/types/page.ts
The page metadata cannot be edited anywhere.
Fixes ISOM-1582.
**Features**:
- Add page metadata editing to the page settings page.
=> feat: add page metadata to page settings

.github/workflows/deploy_production.yml
currently, we release using a label. this is not ideal because we have to raise a pr with no meaningful changes and then attach a label.
update so that we now deploy to production on release rather than using a pr label. this is preferred because we don't have to make empty commits and a fake pr to create a release.
removed the action to comment on pr because no easy out of the box functionality was found. we can add it back next time if we feel that it's needed
chose `released` over `published.` see here: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release for the differences but i think both are fine, just that it's more semantic to publish releases as a version bump rather than attaching to the draft release. this means that we'll only deploy to …
=> chore: update workflow for production

.github/actions/setup/action.yml, .github/workflows/chromatic.yml, .github/workflows/ci.yml, apps/studio/package.json, apps/studio/turbo.json, package-lock.json, tooling/github/package.json
This PR refactors the CI workflow to separate unit/integration tests from end-to-end tests, improving the overall testing process.
- Separated unit/integration tests from end-to-end tests in the CI workflow
- Added a specific job for unit and integration tests
- Created a dedicated job for end-to-end tests
- Updated caching strategy for Next.js
- Improved artifact retention for test results
**Bug Fixes**:
- Fixed the cache key generation to include all relevant file types
- Updated the CI workflow to run unit and integration tests separately from end-to-end tests
- Added Playwright installation step specifically for Chromium
- Updated the build and test commands to use Turbo for better performance
- `test-ci:e2e` : Runs end-to-end …
=> feat(ci): separate e2e tests from unit/integration tests

packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx, packages/components/src/utils/getTailwindVariantLayout.ts
The not found page is classified as a content page, but it is actually a homepage variant.
**Bug Fixes**:
- Classify the not found page as a homepage variant.
- Sync the design of the index page with the content page.
**BEFORE**:
**AFTER**:
=> fix: classify not found layout as homepage

apps/studio/src/hooks/useUploadAssetMutation.ts
We no longer are doing any PDF rendering component, so we need to encourage browsers to display PDF files in-line rather than download.
- Add the `Content-Disposition` header to the file upload so that we can hint to the user to show the PDF in the browser instead of downloading it.
=> chore: add content disposition header for assets

apps/studio/src/components/CmsSidebar/CmsSideNav.tsx, apps/studio/src/components/CmsSidebar/CmsSidebarContainer.tsx, apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx
- Enhanced layout consistency across multiple pages
- Improved scrolling behavior in the CMS sidebar and content areas
- Removed unnecessary Spacer import in CmsSideNav component
Storybook
- Verify that the CMS sidebar and content areas scroll independently
- Check that the layout remains consistent across different pages (collections, folders, site home)
=> feat: make cms sidebar scroll independent of resource table

packages/components/src/templates/next/components/complex/Image/Image.tsx
Image caption is left-aligned on Tablet, which is incompatible with how we provide image sizing options (smaller vs. original). Specifically, the smaller image size aligns the image to the center of the page, so the caption gets misaligned.
Closes [ISOM-1546]
Image caption is center aligned from the md breakpoint
Before:
After:
=> fix(components): image caption should be center-aligned on tablet as well

packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx
Closes [ISOM-1357]
Currently, all links with arrows on the Isomer Next template share an interaction where the arrow inches by 4px to the right with an ease-in transition. The megamenu was the only place where this interaction was different. This causes an inconsistency in interactions which impacts usability of the site.
Changed megamenu item interactions from underline to nudging the arrow and getting an interaction-hover colour. This won't take effect on external links.
- Details ...
- [x ] No - this PR is backwards compatible
**BEFORE**:
https://github.com/user-attachments/assets/191e54af-58d6-438d-8e32-e8e3127302ca
**AFTER**:
https://github.com/user-attachments/assets/6a14db76-afe0-4b1a-9cd3-94fa99329644
=> fix(components): standardise hover interactions for links with arrows on megamenu

packages/components/src/templates/next/components/internal/TableOfContents/TableOfContents.tsx
Previously, the ToC ("On this page") lacked background colour which made it look floaty. 
This PR adds a background to the component so that all the links under a ToC seem like they are in the same group. This should bring more attention to the ToC, helping site visitors to find the exact subtopic they want.
The component also has an 8px rounded corner to make the component look modern and softer, which is the same value that we use for callouts.
- Details ...
**BEFORE**:
Previously, the ToC was floating around, and top-alignment with the siderail was off:
**AFTER**:
View chromatic.
=> fix(components): add background to On this page/ToC for visual balance and cohesion

.vscode/settings.json, tooling/prettier/index.js
Saving takes forever due to Tailwind plugin. This PR attempts to simplify the amount of regex that the plugin has to parse. Remove unused regex patterns.
- Simplified the Tailwind CSS class regex configuration in VS Code settings
- Removed unused regex patterns for `cva`, `cx`, and `classNames`
- Retained only the regex pattern for `tv` function
=> chore: update tailwind vscode plugin settings

apps/studio/src/features/editing-experience/components/EditPagePreview.tsx, apps/studio/src/features/editing-experience/components/IframeToolbar.tsx, apps/studio/src/features/editing-experience/components/PreviewIframe.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx
Closes ISOM-1512
This PR introduces a new viewport control feature for the page preview in the editing experience.
**Features**:
- Added a new IframeToolbar component with viewport control options (desktop, mobile, tablet, responsive)
- Implemented viewport switching functionality in the EditPagePreview component
- Enhanced the PreviewIframe component to support different viewport sizes
- Refactored the EditPagePreview component to include the new IframeToolbar
- Updated the page editing layout to use the new EditPagePreview component
See storybook
- Test the new IframeToolbar component
- Verify that viewport switching works correctly for all options
- Ensure that the preview renders correctly in different viewport sizes
- Check that the …
=> feat(studio): allow admins to change preview viewport size

.github/workflows/ci.yml
`import-in-the-middle` v1.11.0 release broke datadog's vitest test visibility tracing. 
This PR temporarily disables the visibility harness for unit tests (playwright not affected) until it's fixed.
Related:
* https://github.com/DataDog/dd-trace-js/pull/4732
* https://github.com/nodejs/import-in-the-middle/pull/155
This change disables the Datadog Test Visibility configuration and tracing in the CI workflow for the isomer-studio project.
- Removed Datadog Test Visibility configuration step from the CI workflow
- Commented out Datadog-related environment variables for the test run
No new tests are required for this change. Existing tests should continue to run without Datadog tracing.
=> fix(ci): temporarily disable dd test visibility for unit tests

packages/components/src/interfaces/complex/Accordion.ts
The accordion title content length of 100 characters is too limiting.
- Increase the max length limit from 100 to 300 characters.
=> chore: increase accordion title content length

packages/components/src/templates/next/components/internal/Footer/Footer.stories.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.tsx
This PR addresses some styling and copy enhancements for footer.
Previously, the footer wasn't collapsing right on the tablet-small desktop breakpoints. It had a larger x-padding which made the footer contents misaligned with the rest of the homepage content.
Also we had comments from migration sync that the capitalisation for "Contact Us" was inconsistent, and the term "Reach us" clashes with "REACH". 
Closes ISOM-1356
- Changed padding to be consistent at the lg-xl breakpoint at 40px. 
- Also minimised some minor gaps that were very glaring between sections.
- Copy changes.
**BEFORE**:
Notice the footer contents are misaligned with the side rail:
https://github.com/user-attachments/assets/bbd33e6e-c1cd-4122-88fe-dc3291afade0
**AFTER**:
Footer collapses consistently with homepage …
=> fix(components): footer enhancements

packages/components/src/templates/next/layouts/Article/Article.stories.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx
- The article page was designed for articles with a summary, so without the summary, there is an odd gap which looks very janky.
- Regardless of whether article summaries are mandated, this should be fixed to keep components and layouts flexible.
Closes [ISOM-1593]
- Adjusted gap in article to be smaller overall. This way, when an element is removed (e.g., summary), the gap between elements isn't as jarring
- Added new stories to test for above situations
An article without summary:
Mobile:
=> fix(component): remove awkward gap in articles

packages/components/src/templates/next/components/native/Table/Table.tsx
- Making last column fill up the width of a table was an assumption that was not applicable to many use cases we saw; we decided to remove this feature and let site admins decide the width of a column on their own
- When multiple rows were spanned, the bottom border would disappear; example on: https://staging.dorwsv8lwiupx.amplifyapp.com/lifestage/5-seniors/
Closes [ISOM-1594]
- Added border to table
- Removed max-w-full on the last column of a table
=> feat(component): Table enhancements and border fixes

packages/components/src/utils/getReferenceLinkHref.ts
I forgot we don't have `document` until we actually invoke DOMPurify.
**Bug Fixes**:
- Pass a string directly to DOMPurify instead and get it to return the DocumentFragment, rather than crafting the element ourselves using `document`.
=> fix: avoid using document to create element

.github/workflows/ci.yml, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/utils.ts
1. we disabled dd tests previously due to `import-in-the-middle` failing, now that it has been fixed, we're allowing the action again
2. the pr to change the `identifier` from `email` to a concat of `email, ip` broke the email router tests. this pr fixes the failing tests
1. enable dd tests
2. update the tests to use the new identifier
=> fix(tests): enable dd tests + fix failing tests 

packages/components/src/templates/next/components/complex/Infobar/Infobar.tsx
- Infobar didn't have margin-top when used in content pages, so there was zero space between its previous elements
- Infobar's buttons were not aligning to the left in smaller viewports
Closes [ISOM-1596]
- Added a margin-top to infobar when it's not a first child (moved `outercontainer` to the outer `<section>` and removed the extra `div`)
- Specified how buttons should align in smaller screens
Infobar gets a margin-top when it's not a first child
No margin-top when it's at the top of the page (first child)
Infobar buttons align left on content page
and align center on Homepage
=> fix(component): Infobar top margin and button alignment

apps/studio/README.md
Reference the Starter Kit on-prem deploy instructions, so that users may know how to use Isomer without cloud
=> docs(readme): add ref for on-prem

package-lock.json, packages/components/package.json, packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.tsx, packages/components/src/utils/getFormattedDate.ts
The way we display dates on the site is very different, and can lead to date parsing issues.
**Bug Fixes**:
- Standardise the way we display dates on the site, and provide a range of date formats to parse the date string using dayjs.
=> fix: standardise date formats displayed on site

packages/components/src/templates/next/components/complex/Infopic/Infopic.stories.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.tsx
The [infopic looks fine](https://storybook-next.isomer.gov.sg/?path=/story/next-components-infopic--default) on all viewports when a title, description, and CTA are used properly. However, it doesn't look as good when some elements are omitted or when the elements have odd dimensions/lengths.
Mainly, the issues were:
- When an infopic doesn't have a long enough title and/or description, the image doesn't fill up the height and leaves an awkward grey space.
- When title is used without a description, it is not vertically centered in the content container (for desktop only)
- Images that are horizontally long look odd on mobile, because there is no min-height specified. It's better to take the risk of cutting off images by assigning a min-height
View screenshots of the issues on [the …
=> feat(component): enhance Infopic component to look nice in edge cases

packages/components/src/templates/next/components/complex/Iframe/Iframe.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx
Embed/iframes don't have a margin-top when placed into pages, so it sticks to the element previous like the following: 
Closes [ISOM-1595]
- Add top margin (28px, standard that we use for most elements) when the iframe is not a first child
- Added an iframe to the Content page story to test it out
Mobile:
=> fix(component): add margin-top to iframe/embeds when it's not a first child

packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx
The default placeholder copy on Collections search was too specific with a piped text, so it read weirdly depending on the page title.
Closes [ISOM-1611]
Change copy to say "Start typing to search"
=> fix(component): change placeholder copy on collections search to be more generic

apps/studio/src/components/Datatable/Datatable.tsx
Closes [#1469](https://linear.app/ogp/issue/ISOM-1469/my-pages-main-table-styling)
- Add a `Divider` component when rows count is at least 1
- Details ...
**Bug Fixes**:
- Fixed visual inconsistencies in the table styling.
=> isom-1469 - fix: add divider in datatable

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx
Closes https://linear.app/ogp/issue/ISOM-1484/move-modal-overflowing-titles-have-extra-spacing
- add textalign left
- Details ...
**Bug Fixes**:
=> isom-1484 - fix: remove extra spacing for move modal overflowing titles

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveItem.tsx
The item in the move modal has a height that's inconsistent with the height in figma
Closes https://linear.app/ogp/issue/ISOM-1489/move-modal-move-item-has-wrong-height
Added the size "xs" to the `Button` parent component to resolve the height issue.
- Details ... 
**Bug Fixes**:
- Fixed the wrong height of the move item modal by applying size "xs".
=> fix: add size "xs" to fix moveitem wrong height

apps/studio/src/components/PageEditor/LinkEditorModal.tsx, apps/studio/src/components/PageEditor/TableSettingsModal.tsx, apps/studio/src/components/VersionWrapper/VersionModal.tsx, apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/DeleteBlockModal/DeleteBlockModal.tsx, apps/studio/src/features/editing-experience/components/DiscardChangesModal/DiscardChangesModal.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/components/UnsavedSettingModal.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsLinkControl.tsx
ModalCloseButtons have inconsistent styling with Figma
Closes https://linear.app/ogp/issue/ISOM-1479/all-modals-modal-close-buttons-should-be-lg
Add `lg` size to all of them
- Details ...
=> isom-1479 - fix: use `lg` for all ModalCloseButton

package-lock.json, package.json
- Upgraded Turbo from version 2.0.5 to 2.1.2
- `turbo`: Upgraded from ^2.0.5 to ^2.1.2
=> chore(deps): upgrade turborepo to v2.1.2

apps/studio/public/assets/css/preview-tw.css, packages/components/src/interfaces/complex/InfoCards.ts
right now, when we delete the card, it uses the schema default, resulting in the delete not going through and showing the default. 
1. remove `default` from the schema 
- by right, the schema should tell us what the default is. at present, this is being done by studio. another alternative _could_ be to just use the schema default and remove the constants in studio but the drawback is that it doesnt add much value as of now, is quite some drudgery and teh behaviour changes (see below):
- if we use `schema.default`, what happens is that when you clear the input, it'll use the default value from the schema leading to potentially unintuitive behaviour. (tbh, i'm ok with this but we need to check if this is obvious to the user)
- [relevant …
=> fix(cards): remove default from components package

apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/editing-experience/components/DeleteBlockModal/DeleteBlockModal.tsx
Closes https://linear.app/ogp/issue/ISOM-1491/delete-modal-wrong-spacing-between-text-and-title
- Details ...
**Bug Fixes**:
- fix the font style inconsistency with figma
=> isom-1491 - fix: delete modals textstyle

apps/studio/src/components/PageEditor/LinkEditorModal.tsx, apps/studio/src/components/PageEditor/TableSettingsModal.tsx, apps/studio/src/components/VersionWrapper/VersionModal.tsx, apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/DeleteBlockModal/DeleteBlockModal.tsx, apps/studio/src/features/editing-experience/components/UnsavedSettingModal.tsx
Closes https://linear.app/ogp/issue/ISOM-1477/edit-folder-title-eats-into-close-modal-button
- add a 3.5rem margin-right to the ModalHeader
- or margin-left if the close button is on the left
- don't add if there's no close button e.g. details modal
Note: 
- as not be 8px for everything for now due to wrong close button size, but that's fixed independently in https://github.com/opengovsg/isomer/pull/744
- Details ...
=> isom-1477 - fix: add `mr` 3.5rem to ModalHeader

apps/studio/src/features/editing-experience/components/LinkEditor/LinkHrefEditor.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/layouts/JsonFormsGroupLayout.tsx
Closes https://linear.app/ogp/issue/ISOM-1511/homepage-hero-banner-has-wrong-styling-for-h3
- Details ...
**Bug Fixes**:
- add the necessary margin so that it's consistent with Figma
- update text styling of the header
=> isom-1511 - fix styling of homepage hero banner editor drawer

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/schemas/folder.ts
1. folder titles were allowed to be empty but we want to disallow that so we need more stringent validation
1. update the validation mode to `onChange` - this is because validation (by [default](https://react-hook-form.com/docs/useform#mode)) for react hook form starts **after** submit, which won't be true for our modal (we close after a successful submit) 
2. don't show the permalink box if there is an error 
https://github.com/user-attachments/assets/92278e35-56fb-4799-85c0-5fcb69e32603
=> fix(folder): update the folder title to not be empty

tooling/build/scripts/generate-sitemap.js, tooling/build/scripts/publishing/index.ts
We use a simple alphabetical sorting for the title but this does not account for numbers.
**Bug Fixes**:
- Enable numeric comparison of strings so we can handle sorting of titles with numbers in them
=> fix: use numeric sorting for sitemap generation

packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
Closes https://linear.app/ogp/issue/ISOM-1612/add-extra-12px-gap-between-first-item-and-logospace
add mr-3 to logo class (except if its mobile view)
- Details ...
=> fix: add mr-3 (12px) to navbar logo (except mobile)

apps/studio/src/features/editing-experience/components/PublishButton.tsx, apps/studio/src/server/modules/aws/codebuild.service.ts, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/version/version.service.ts
We don't currently do any site publishes for implicit actions.
**Features**:
- Perform publishes for implicit actions such as:
- Creates: Folder/Collection
- Updates: Renaming of folder, moving of folder/pages
- Deletes: Pages/Folder/Collection
- A new build is not triggered if there is a currently running build that was started within the last 60 seconds of the time of publish.
- Reason: CodeBuild doesn't have the functionality to queue builds, so if we want to avoid the starvation of builds, we will have to implement our own queueing system which would be quite an involved effort. For context, starvation of builds happen because we originally kill off the existing running build when starting new ones.
- 60 seconds is a number decided based on tests, whereby the …
=> feat: perform publish of site for implicit actions

apps/studio/.storybook/preview.tsx, apps/studio/package.json, package-lock.json, packages/components/package.json, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/utils.ts, packages/components/src/types/utils.ts, packages/components/src/utils/getFormattedDate.ts, packages/components/src/utils/getParsedDate.ts, packages/components/src/utils/index.ts
Some of the dates in collections show up as invalid date because the allowed date format is very specific.
**Bug Fixes**:
- Improve the date parsing of collection items.
=> fix: improve date parsing for collection items

apps/studio/.env.test, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/tests/integration/helpers/seed/index.ts, apps/studio/tests/msw/handlers/page.ts, tooling/eslint/base.js
Second part of the PR. This PR adds tests for `resource.router`
Blocked by #729
=> feat: add more validation to resource.router and add test cases

apps/studio/.storybook/preview.tsx, apps/studio/src/components/CmsSidebar/CmsSidebarContainer.tsx, apps/studio/src/components/CmsSidebar/CmsSidebarOnlyContainer.tsx, apps/studio/src/features/dashboard/components/DirectorySidebar/DirectorySidebar.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/LayoutScreen.tsx, apps/studio/src/features/editing-experience/components/SiteEditNavbar.tsx, apps/studio/src/hooks/useBanner.ts, apps/studio/src/lib/growthbook.ts, apps/studio/src/pages/404.tsx, apps/studio/src/pages/_app.tsx, apps/studio/src/pages/sign-in/select-profile.tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/pages/sites/[siteId]/settings.tsx, apps/studio/src/stories/Page/DashboardPage.stories.ts, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditPageSettings.stories.tsx, apps/studio/src/stories/Page/SitePage.stories.tsx, apps/studio/src/stories/components/VersionModal.stories.tsx, apps/studio/src/stories/utils/growthbook.ts, apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/src/templates/layouts/AdminLayout.tsx, apps/studio/src/templates/layouts/AdminSidebarOnlyLayout.tsx, apps/studio/src/templates/layouts/DefaultLayout.tsx, apps/studio/src/templates/layouts/PageEditingLayout.tsx
This PR addresses layout issues related to scrolling and height calculations across multiple components in the studio app when the banner is visible.
- Updated height calculations in various components to use `height={0}` and `minH="100%"` instead of fixed `100vh` values
- Improved scrolling behavior in modal screens, sidebars, and page layouts
- Enhanced responsiveness of layout components
**Bug Fixes**:
- Fixed potential overflow issues in CmsSidebar components
- Resolved layout inconsistencies in CreatePageModal screens
- Corrected height calculations in various page templates
Should be no different in snapshots, but scrolling behaviour should now be consistent.
- Test scrolling behavior in CmsSidebar components
- Verify layout consistency in …
=> feat: improve scrolling behavior and layout consistency with banner

apps/studio/prisma/seed.ts, apps/studio/src/components/PageEditor/FileAttachment.tsx, apps/studio/src/components/PageEditor/LinkEditorModal.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/constants.ts
Users should be able to upload their pdf to the page.
1. add a `FileAttachment` component that does the attachment. I used a `Skeleton` and set the string to `""` so that we are disabling the save
2. we add a validation mode of `onChange` so that we'll start validation immediately. this is because the default mode is `onSubmit`, which won't trigger until we try to submit the form (and we'll have no error messages) 
https://github.com/user-attachments/assets/dd7c35c2-a171-41e6-ae8d-5e5314f7c3af
=> feat(file-upload): implement file uploads on tiptap 

apps/studio/src/components/Datatable/Datatable.tsx
datatable has very long divider due to noob implementation in https://github.com/opengovsg/isomer/pull/741/files of using Divider
replace Divider with `borderBottomWidth="1px"`
- Details ...
=> fix - replace Divider with borderBottomWidth

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx, apps/studio/src/features/editing-experience/components/constants.ts
RE: https://opengovproducts.slack.com/archives/C06R4DX966P/p1728885261758369
add the new copywriting as a constant + import it to be used instead
- Details ...
Note: ignore the disabled Publish button - it's irrelevant to this ticket as it's currently hardcoded
https://github.com/user-attachments/assets/d476ff04-e272-4716-ad38-0cfa6fa7a872
=> Improve copywriting for saved changes toast

tooling/build/scripts/generate-sitemap.js
https://opengovproducts.slack.com/archives/C07CWUNUL68/p1728886592310259
Manually input of summary is Array instead of string - no validation here
https://github.com/isomerpages/moh-prepare-next/blob/ddb9aa2a32c55af3a4603917c5606747898487df/schema/events-highlights/inaugural-workshop-to-strengthen-regional-collaboration-in-detection-technologies-for-surveillance-and-diagnostics-during-peacetime.json#L212-L214
check for array and join if it is
- Details ...
=> fix - generate sitemap check for summary being an array

apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx
right now, when we create a empty tiptap block, the component is `undefined` which fails validation when we click the back button
1. add a default state if the component is undefined. we just add an empty paragraph block which looks identical to what we have atm 
2. also add validation so that if `component` is `undefined`, we return an empty `div`. note that this case will **only ever appear on initial creation** (tiptap will set content of paragraph to `undefined`) and in all other cases, an initial block will have a paragraph node with `content: [""]`
=> fix: prevent page from crashing when we go back

packages/components/src/templates/next/components/internal/Masthead/Masthead.tsx
The current SG govt masthead in Isomer Next uses large font sizes, dark font colour, and a dark background. This makes the masthead too prominent and breaks the visual balance by drawing too much attention to the masthead.
Closes [ISOM-1613]
Adjustments to:
- Background colour
- Font size
- Gap
- Text colour,
using Isomer tokens, to meet changes on Figma. 
This PR does not touch any elements inside the "How to identify" accordion. We've observed that the content under the accordion is usually left similar to the original implementation by SGDS ([Example](https://redeem.gov.sg/disbursing), [Another example](https://www.moe.gov.sg/)), although the banner design itself is often altered for better visual harmony.
Before:
After:
=> fix(components): masthead styling changes

.github/workflows/ci.yml
previously, the index pages PR was merged it but it had a failing build due to a dynamic import, which wasn't caught. this cuold have been solved w/ a build step
1. add build step to ci
=> chore: add build step to ci

tooling/build/scripts/generate-sitemap.js, tooling/build/scripts/publishing/index.ts
We don't get the collection subtitle as the page summary, which results in index pages being unable to show them.
**Bug Fixes**:
- Capture the collection subtitle as the page summary inside the sitemap.
=> fix: get the collection subtitle as the page summary

packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx
During migration, we observed enhancement opportunities to the CollectionCard:
- We clamp the title and description at 2 lines, which results in critical content becoming obscured (especially when there is an image or the screen is small) 
- There is a gap that appears when there is no summary (`description` field) in an article because a `<span>` is created regardless of whether the field is empty
- Image is too wide, so content is obscured even further
Closes [ISOM-1600]
- Change line clamping of title to line-clamp-3
- Change description <span> to only show when there is a description present
- Change width of image to be responsive (25% of card in desktop) and have a minimum height on tablet
- Add a story that shows CollectionCards with image
CollectionCard with image, desktop:
No …
=> fix(components): collectionCard spacing and line truncation enhancements

apps/studio/prisma/migrations/20241018013545_resource_remove_overlapping_indexes/migration.sql, apps/studio/prisma/migrations/20241018091821_resource_add_type_index/migration.sql, apps/studio/prisma/schema.prisma
Closes https://linear.app/ogp/issue/ISOM-1286/add-indexes-for-tables
- Details ...
- Removed 2 composite indexes from `Resource` as they are already covered and overlapping with another index
- Added index on `type` for `Resource`
=> isom-1286 add indexes for tables

tooling/build/scripts/publishing/index.ts
RDS password is an encoded URI component.
**Bug Fixes**:
- Decode the URI component RDS password.
=> fix: decode RDS password when retrieving from SSM

packages/components/src/templates/next/components/complex/Hero/Hero.tsx
The buttons on the colour block hero variant weren't getting a focus visible state when navigated using the Tab key.
Added `isWithFocusVisibleHighlight` to the buttons
=> fix(component): colour block hero variant is missing focus visible state

packages/components/src/templates/next/components/internal/Button/Button.tsx
Inverse buttons were missing their hover states, so the affordance on these were lacking. 
Closes [ISOM-1614]
Added a hover colour to inverse buttons. Uses existing tokens at the moment, but the intention is to create new semantic tokens for this purpose post initial launch.
=> fix(component): update hover colour for inverse buttons

apps/studio/src/server/modules/page/__tests__/page.router.test.ts
currently, we have no test descriptions for publishing. just adding this here so next time we're clear on what we have to verify for publishing
add tests for publishing
=> chore(tests): add test descriptions for publishing

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/generated/selectableTypes.ts, apps/studio/prisma/migrations/20240923090529_add_resource_perms/migration.sql, apps/studio/prisma/migrations/20240924045858_make_resource_optional/migration.sql, apps/studio/prisma/migrations/20240924051641_add_unique_for_resource_perms/migration.sql, apps/studio/prisma/migrations/20241018152737_add_created_updated_at/migration.sql, apps/studio/prisma/schema.prisma
we have no resource schema for permissions.
add a db schema for resouce permissions. we track the `(siteid, userid, resourceid)`. this returns a `role`, which can be one of `publisher, editor, admin`. 
at present, we will take `resourceId === null` as meaning that this user has site wide permissions
=> feat: add db schema for resource permissions

packages/components/src/templates/next/components/internal/DatadogRum/DatadogRum.tsx
Storybook Layout section breaks when datadog is loaded (re: https://github.com/opengovsg/isomer/pull/790)
Datadog is using `process.env` which is unavailable for client side
- Details ...
**Bug Fixes**:
- check for `process` is defined first (not ideal but Datadog RUM is a launch thing which will be removed soon)
**BEFORE**:
=> fix - datadog RUM check for process first

apps/studio/package.json, apps/studio/prisma/schema.prisma, apps/studio/src/server/modules/permissions/__tests__/permissions.service.test.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, package-lock.json
this pr adds tests and logic (using casl) for basic resource permissions for editors and admins
1. use `casl` to define permissions for admin and editors
- for editors, they can perform every action on non-root pages but are unable to create/delete root pages. editors can stiil r/w on root pages 
- for admins, they can perform read/writes on root pages.
how this is implemented is non-overlapping, so at run time, we will construct the permission based on what access the user has to the resource.
=> feat(resource): basic implementation and tests

packages/components/src/presets/next/colors.ts, packages/components/src/templates/next/components/internal/Notification/Notification.tsx
Site notification was blending with the masthead after we changed the masthead colour
Closes [ISOM-1630]
Landed at a subtle blue colour as a background colour. See [explorations on Figma].(https://www.figma.com/design/G7kZTNhgm6V5VeI9yEE6rS/Template-Explorations?node-id=299-1814).
- Why not saturated blue? Saturated blue is too visible and eye-catching. Our strategy is to roll out a subtle notification first, and introduce "stronger" variant in the future when we need more attention-grabbing ones
- Why not darker blue? Contrast issue.
- Why not some variant of a brand colour? It's possible for a brand/theme colour to be green, yellow, or red. This would add a semantic meaning to the notification banner.
- Why not grey? Looked disable and didn't catch enough attention.
=> fix(component): update site notification background so it doesn't blend in with masthead

packages/components/src/utils/getTextAsHtml.ts
We are using `document` on the server-side component, but `document` won't be available
- Details ...
**Bug Fixes**:
- replace with server-safe DOMPurify
=> fix- replace dom manipulation with DOMPurify to make it server-safe

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
CI and build fail because of missing args passed into `getReferenceLinkHref` for KeyStats in https://github.com/opengovsg/isomer/pull/794 due to outdated branch and a newer commit from https://github.com/opengovsg/isomer/pull/752
- Details ...
**Bug Fixes**:
- add in missing arg
=> fix - add missing args for KeyStats getReferenceLinkHref call

packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx
Closes https://linear.app/ogp/issue/ISOM-1639/infocards-on-homepage-have-a-short-image-height-when-in-2-column
- Details ...
- if `layout` is `homepage`, then show h-60 above md
- also - refactor stories to generate args in a more scalable and less-repetitive manner
=> isom-1639 infocards on homepage have a short image height when in 2

apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/utils/sitemap.ts, tooling/template/app/robots.ts
We are not retrieving the parent resource correctly for collection pages.
**Bug Fixes**:
- Include Collection in the allowed types when retrieving ancestors.
- Also fixed robots.txt not being disallowed for staging environments.
=> fix: retrieve collection as resource ancestor

apps/studio/src/server/modules/resource/resource.router.ts
our query now only cares about folders and omits collections/root pages, which leads to collections being expandable but showing nothing
1. i think i updated this elsewhere too but just set the query to include folders/collections/rootpage
https://github.com/user-attachments/assets/b8d166c1-5732-4e2c-a075-ebd85a54f96b
=> fix: add correct types for getting children

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/permissions/__tests__/permissions.service.test.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/permissions/permissions.util.ts, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts
we need to add permissions checking for moving items between folders. 
add initial permissions check. this allows editors to freely move **non-root** items between **non-root** resources. we allow admins to freely move items between folders.
https://github.com/user-attachments/assets/666f286a-efbe-4be3-b3d1-0fbd36f5d6e6
=> feat(perms): add permission checking for moving resources

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/permissions/PermissionsContext.tsx, apps/studio/src/features/permissions/index.ts, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx, apps/studio/src/pages/sites/[siteId]/index.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts
we need a ui for permissions for moving items. specifically, we need to disable certain functionality when the user **is not allowed** to move items.
For editors, they can only move resources that **are not at root**. For admins, they can move resources freely regardless of where the resources might be.
1. add a `Context` for permissions so that inner components can call it and we have no need to prop drill. **not** using `jotai` here because i want the component tree to re-render in the event that this changes 
2. UI-wise, buttons are removed if they fail the check for permissions. additionally, the ui for move modals have been very slightly updated. previously, we relied on the resource id being present (or not) to disable the button. now, this is done via a …
=> permissions(move): add ui for moving items

apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts
This pr adds permissions checking for permissions on folders and collections **on the backend**. do note that this is only a backend change because the user is restricted from creating/deleting the folder/collectoin already on frontend as the `ability` restricts them.
1. shift shared permissions check out to `permission.service` . this is not done for `move` yet, because the api is slightly different. i will aim to get behaviour correct first before shifting to another implementation (via `experimentalMiddleware`)
2. add permissions check to the methods on `collection.router` and `folder.router`
=> feat(permissions): folder permissions

.github/workflows/deploy_vapt.yml, apps/studio/package.json, apps/studio/src/features/editing-experience/components/PublishButton.tsx, apps/studio/src/features/permissions/PermissionsContext.tsx, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/permissions/__tests__/permissions.service.test.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/permissions/permissions.type.ts, apps/studio/src/server/modules/permissions/permissions.util.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditPageSettings.stories.tsx, apps/studio/src/templates/layouts/PageEditingLayout.tsx
This PR adds in permissions for site-wide actions such as viewing sites, retrieving navbar etc. This PR also adds in publishing permissions. 
- in similar fashion to what's been done previously, add in more resource types and actions
- define a helper to check the permissions of the user after retrieval of their role from teh db
- going to refactor abit in subsequent PRs. i think the commonality is clearer here and we'll probably define a helper to retrieve roles for db that can be shared across all + extract into a `experimentalMiddleware`. 
- another thing we're oging to change is that `move` is going to be updated to `delete` on original resource + `create` on destination resource
=> permissions(settings/publishing): add site level permissions and publishing permissions

apps/studio/package.json, apps/studio/prisma/migrations/20241015055654_change_name_to_link/migration.sql, apps/studio/prisma/migrations/20241015073853_add_enum/migration.sql
1. we didn't squash our migrations so what happened was that we get migrations that were erroneous and being ran in prod
1. squash the link migration as it was previously added, removed and then re-added which led to conflictss
=> chore(migrations): fix migrations from prisma

apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/PreviewLayout.tsx, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/stories/Flows/CreateCollectionItemFlow.stories.tsx
1. duplicate permalinks error weren't being shown on link
2. permissions prevented people from creating collection pages 
3. double render on initial load
1. shift the suspense out so that on initial loda, it's not doubly rendered (the modal doesn't close and reopen) 
2. update resource id for permisisons
3. conditionally; set error message on `title` when duplicate permalink
=> fix(collection-pages): misc fixes

packages/components/src/engine/metadata.ts, tooling/template/app/sitemap.ts, tooling/template/data/config.json
Our sitemap.xml file is invalid because it does not include the site's domain in the entries.
**Bug Fixes**:
- Add the site base url to the sitemap.xml generation function.
=> fix: add site base url to sitemap entries

packages/components/src/interfaces/complex/InfoCards.ts
We have users complain that 6 cards is insufficient.
- Increase the maxItems for InfoCards from 6 to 12.
=> chore: increase maxItems for InfoCards from 6 to 12

packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Collection/useCollection.ts
Currently `filters` are generated on client side. If there's huge number of records or users are using poorly supported browsers/low-end devices, the experience won't be ideal
- Details ...
- move it from client side to server rendered
=> improvement (perf) - move filters to server side

apps/studio/public/assets/css/preview-tw.css, packages/components/src/engine/metadata.ts, packages/components/src/interfaces/internal/SkipToContent.ts, packages/components/src/interfaces/internal/index.ts, packages/components/src/templates/next/components/internal/SkipToContent/SkipToContent.tsx, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
The skip to content button appears on mobile when clicking on a link in mobile.
**Bug Fixes**:
- Move the masthead, notification banner, navbar, unsupported browser banner and the skip to content button inside a `<header>` tag.
- This is because the Next.js link always does a `document.body.focus()` as part of the scroll to top functionality, and the skip to content button is the first element inside the `<body>` tag, which causes it to appear when clicking on a Next.js link (which is effectively all our links on the site).
- Live demo is on togetherforbetter.gov.sg.
=> fix: hide skip to content button on mobile

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
- Didn't pen down design specs properly, so the gaps in homepage variant were slightly off.
- KeyStatistics block on content page missing a mt-0 when it's the first child.
Closes [ISOM-1649]
- Adjusted gap for homepage variant
- Adjusted mt for content page variant
- Checked locally, didn't write new stories for now
=> fix(components): adjust gap and margin on keystatistics block

packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx
Closes https://linear.app/ogp/issue/ISOM-1650/old-browser-iphone7-keystats-mobile-design-broken
- Details ...
**Bug Fixes**:
- only set width on tablet (`md`) beyond since default is 1 column on smaller screen size
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/dd768610-9eea-4890-a4e5-657fda3d3cdb) | ![image](https://github.com/user-attachments/assets/f818262e-80f0-4156-bb77-f6e48d2aba39) |
=> isom-1650 - Old browser (iphone7) keystats mobile design broken

packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx
The sorting of collection items is incorrect, as the date is being parsed incorrectly by the default Date object.
**Bug Fixes**:
- Use a proper date parsing function to get the date.
=> fix: get proper parsed date for collection items

packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, tooling/build/scripts/publishing/index.ts, tooling/build/scripts/publishing/queries.ts
We are not fetching the CollectionLink blob contents, causing it to not be rendered in the final site output.
**Bug Fixes**:
- Add the CollectionLink type in the SQL query when fetching all resources.
=> fix: include content for CollectionLink resources

apps/studio/src/instrumentation.ts
not entirely sure why using `env.NODE_ENV` doens't work. looking at [activesg](https://github.com/opengovsg/activesg/blob/f89843a059b74926f1fd8e5383269a64ff6e08e6/apps/admin/src/instrumentation.ts#L4) + ks code, they both use `NEXT_RUNTIME` instead 
use `NEXT_RUNTIME`?!
=> fix: instrumentation

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx, apps/studio/src/server/modules/aws/codebuild.service.ts
We are spinning up multiple CodeBuild builds which is quite wasteful.
**Features**:
- Ensure that there are only a maximum of 2 CodeBuild builds running at any time.
- Case 1: If there are no running builds at all, start 1 build.
- Case 2: If there is already 1 existing running build, and this running build is started more than 1 minute ago, start a new build.
- Case 3: If there is already 2 existing running builds, and the latest running build is started more than 1 minute ago, stop the latest build and start a new one.
- Otherwise, don't do anything.
**Bug Fixes**:
- Invalidate the `readPage` procedure when saving changes to the page so the publish button becomes active after save.
=> feat: only have a maximum of 2 CodeBuild running

apps/studio/src/components/PageEditor/FileAttachment.tsx
Closes https://linear.app/ogp/issue/ISOM-1651/inform-users-that-only-pdfs-are-supported
- Details ...
- add a copywriting text
**AFTER**:
=> isom-1651 - add acceptable file type messages

tooling/build/scripts/publisher.sh
We are always using the latest main branch to build our components and templates, which can be dangerous.
**Features**:
- Fetch the latest release tag from the repository and use that release tag for the site builds.
- NOTE: We still retain the ability to set a custom branch to build from using the `ISOMER_BUILD_REPO_BRANCH` env var.
**BEFORE**:
**AFTER**:
=> feat: use latest release tag instead of main for publish

apps/studio/src/server/modules/collection/collection.service.ts, apps/studio/src/server/modules/page/page.service.ts
Our dates is not using the correct format when creating pages with dates.
**Bug Fixes**:
- Fix to use `dd/MM/yyyy` format as the date when creating pages with dates in them.
=> fix: use dd/MM/yyyy for article dates

packages/components/src/utils/validation.ts
We added the link pattern restriction on our schema, which resulted in migrators being unable to use internal links on their GitHub sites.
**Bug Fixes**:
- Allow the legacy permalink format which starts with a `/`.
=> fix: allow legacy internal permalinks

tooling/build/scripts/publisher.sh
We currently do a complete invalidation on CloudFront, which has some race condition issues and causes visitors to encounter an irresponsive website.
**Bug Fixes**:
- Update the publisher script such that when we upload the files to S3, we set all page content to have a low cache of 10 minutes, whereas all JS and CSS files inside the `_next` folder has a much longer cache duration of 24 hours.
- Remove the need to perform a distribution invalidation as the cache control setting now takes precedence.
=> fix: set cache control for only _next folder

apps/studio/src/features/editing-experience/components/PreviewWithoutSitemap.tsx, apps/studio/src/features/editing-experience/constants.ts, apps/studio/src/features/editing-experience/hooks/useTextEditor.ts, apps/studio/src/features/editing-experience/utils.ts, apps/studio/src/utils/link.ts
We had an issue where users can be overwhelmed with multiple text components in a page, so in an attempt to consolidate them into a single text component, they copy-pasted from the preview into the Tiptap editor.
This caused issues with rendering links, as all links in the preview are transformed to the `#` value, which gets published to the actual site.
**Bug Fixes**:
- Remove the transformation to the `#` value in the FakeLink, as the `e.preventDefault()` is sufficient to prevent links from being clickable in the Preview.
- Add a ProseMirror plugin to the link extension to handle reference links being copied.
- This is needed as links inside the HTML copied from the preview is transformed to the absolute link (e.g. `[resource:1:2]` becomes …
=> fix: preserve reference links when copy-pasting from preview

.aws/deploy/task-definition.json, apps/studio/next.config.mjs, apps/studio/src/server/modules/tracer.ts
Currently, we don't have tracing on our backend which hinders troubleshooting
1. remove db monitoring for now so dd doesn't get stuck on the connection phase to db 
2. add tags to tracer init (i'm pretty sure we don't need this cos we have env var tags but why not)
3. add instrumentation option to next js config (nextjs needs this option to be enbaled otherwise in the compiled output, they won't call the register hook)
see traces on staging [here](https://ogp.datadoghq.com/apm/traces?query=service:isomer-next&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service,core_resource_name,log_duration,log_http.method,log_http.status_code&fromUser=false&historicalData=false&messageDisplay=inline&query_translation_version=v0&sort=desc&spanType=all&storage=hot&view=spans&start=1730803137793&end …
=> fix(dd): add tracing to backend

tooling/build/scripts/publisher.sh
Hoping to leverage the concurrent uploads stated in https://docs.aws.amazon.com/cli/latest/topic/s3-config.html to speed up `aws s3 sync`
partially closes https://linear.app/ogp/issue/ISOM-1661/optimise-site-build-times
- Details ...
- set a higher S3 `max_concurrent_requests` based on the number of cores (arbitrary 4x multiplier since file size is small)
- We set a floor (20, which is higher than the default 10) and a ceiling (re: https://jasonralph.org/?p=791)
- experimented with 10x multiplier with no cap (which means 320 concurrency with 32 CPU core, but value is the same). Likely due to resource bottleneck beyond a certain point
- benchmarking
- before: 140s to 240s
- after: 80s to 90s 
- improvement: 50s to 160s reduction
=> speed up codebuild - aws s3 sync higher concurrency

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/generated/selectableTypes.ts, apps/studio/prisma/migrations/20241107033200_add_whitelist_table/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/modules/whitelist/__tests__/whitelist.service.test.ts, apps/studio/src/server/modules/whitelist/whitelist.service.ts, apps/studio/src/server/trpc.ts, apps/studio/tests/integration/helpers/auth.ts, apps/studio/tests/integration/helpers/growthbook/mockFeatureFlags.ts, apps/studio/tests/integration/helpers/seed/index.ts
Our email whitelist lives in Growthbook, which makes adding new users a little difficult as it involves both updating the database and updating the Growthbook feature flag.
Fixes ISOM-1668.
**Features**:
- Create a new Whitelist table that can take the email and expiry date.
- Enhance the whitelisting logic to allow for domain whitelists and domain suffix whitelisting.
- Added tests for the whitelist check logic.
=> feat: move to whitelist database table from growthbook

packages/components/src/types/meta.ts
The `ref` key is inside the `meta` object inside collection items, which is incorrect.
- Checked through all the schema files in GitHub + DB, none of the schema files have this pattern, so we are safe.
- Removed the `ref` key inside the `meta` object, as it should be inside the `page` object instead. The `meta` object is for page/item settings that do not require the editing preview.
- Our `generate-sitemap.js` and publishing scripts also use `page.ref` rather than `meta.ref`, so this removal makes the behaviour more correct.
=> chore: remove ref from meta in collection items

tooling/build/amplify/create-app.js, tooling/build/scripts/build.sh, tooling/build/scripts/preBuild.sh, tooling/build/scripts/publisher.sh
Sites on GitHub are using a separate location to obtain the components package, which causes them to be on a different release cadence from Studio and actual live sites.
**Features**:
- Adjust the build scripts of Amplify apps to pull from the central repo's latest release tag, and to build the components from there.
- This allows performing of releases from a single location, which is this repo.
=> feat: use central repo for building Amplify apps

tooling/build/scripts/build.sh
GitHub repos built using Amplify have their assets stored together in the same repo, but that was not accounted for in the updated build script.
**Bug Fixes**:
- Move the `public` folder to the template folder together with the schema and data before the site is being built.
=> fix: move assets folder when building GitHub repos

apps/studio/src/features/dashboard/SiteList.tsx, apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts
We currently display all sites in the database, rather than only the sites that the user has access to.
**Bug Fixes**:
- Filter for only the sites that the user has a role for.
=> fix: only display sites that the user has permissions for

packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
When users use the "Skip to main content" button and press enter then continue pressing Tab, the focus reverts back to the masthead.
**Bug Fixes**:
- Set the `tabindex` of the main content anchor tag to be `-1` so that the Tab focus continues from this point, rather than reverting back to the masthead.
- Also removed the outline on focus.
**BEFORE**:
https://github.com/user-attachments/assets/6cddb96e-a9cd-41a0-8156-265ef1a07273
**AFTER**:
https://github.com/user-attachments/assets/176defd7-ee4d-45ab-93b3-f1420e8967e2
=> fix: set tabIndex -1 and no outline for content anchor

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/components/PageEditor/MenuBar/AccordionMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/CalloutMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/MenubarItem/Factory.tsx, apps/studio/src/components/PageEditor/MenuBar/MenubarItem/OverflowList.tsx, apps/studio/src/components/PageEditor/MenuBar/MenubarItem/types.ts, apps/studio/src/components/PageEditor/MenuBar/ProseMenuBar.tsx, apps/studio/src/components/PageEditor/MenuBar/TextMenuBar.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx
Our Tiptap editor menu bar is a little crowded.
Also, this is preparation for adding the divider component back into Tiptap.
**Features**:
- Hide some of the less commonly used functions inside a dropdown menu. Currently, this is the superscript and subscript functions.
**BEFORE**:
**AFTER**:
=> feat: hide less used functions in overflow dropdown

apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts
The list of sites can be duplicated when the user has multiple ResourcePermissions for the same site.
**Bug Fixes**:
- Add a group-by condition for the list of sites accessible by the user.
=> fix: group by the sites when returning list of sites

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
We don't allow adding of blocks to index pages currently, but the add blocks button leads to an empty page, which can be confusing.
**Bug Fixes**:
- Prevent the Add block button from appearing for index pages.
=> fix: add placeholder info box for index page editing

.github/workflows/aws_deploy.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml, .github/workflows/deploy_vapt.yml
The Growthbook client ID is currently using the `production` environment, regardless of the actual deployment environment.
- Make the Growthbook client ID be an input for the AWS deploy workflow, so that each environment can define their own client IDs.
- Note: Both staging and vapt are using the staging client, hence they are the same.
- Also made Intercom take inputs the same way as standardisation.
=> chore: make growthbook client ID env-specific

apps/studio/src/components/AuthWrappers/EnforceLoginStatePageWrapper.tsx, apps/studio/src/components/Intercom.tsx, apps/studio/src/server/modules/me/me.select.ts
Currently intercom is implemented but does not take in user's information. However Intercom stores information in browser cookie (might be wiped out), thus conversations not preserved across devices and sessions
- Details ...
- pass in information into IntercomSDK after retrieving from `getMe()`
- extract into a standalone component to abstract away logics
=> Intercom - Add user info

tooling/build/scripts/publisher.sh
Currently cloudfront bill can be over $100 per day. A sizable portion comes from `_next` content being served from CF
- Details ...
- a low hanging fruit to cache `_next` content on the user's browsers indefinitely to reduce cloudfront egress on repeated visitors
=> update _next to be cached indefinitely

packages/components/src/engine/metadata.ts
We are not pulling the meta description of the homepage from the hero banner subtitle.
**Bug Fixes**:
- Pull the meta description from the hero banner subtitle, which we guarantee to exist on homepages.
=> fix: set hero subtitle as meta description of homepage

packages/components/src/interfaces/internal/GoogleTagManager.ts, packages/components/src/interfaces/internal/index.ts, packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerBody.tsx, packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerHeader.tsx, packages/components/src/templates/next/components/internal/GoogleTagManager/index.ts, packages/components/src/templates/next/components/internal/GoogleTagManager/utils.ts, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx, packages/components/src/types/site.ts, tooling/template/app/[[...permalink]]/page.tsx, tooling/template/app/not-found.tsx
Closes https://linear.app/ogp/issue/ISOM-1675/implement-google-analytics-for-all-sites-on-next
- Details ...
**Features**:
Read through google documentation and it seems like one can add their GA into their GTM and use that too. Given that agencies might want to add other form of tracking e.g. social media pixel, supporting GTM is a more generic approach with better overall support. 
With strong reference to `https://developers.google.com/tag-platform/tag-manager/datalayer`
- Added `GoogleTagManagerHeader` - this is the main one that should run
- Added `GoogleTagManagerBody` - this is the backup in case user has disabled JS
- As per documentation above, `Only one dataLayer object is supported per page`. This means tracking are shared between both agency' GTM and …
=> isom-1675 - add GTM components

packages/components/src/interfaces/complex/Image.ts, packages/components/src/templates/next/components/complex/Image/Image.stories.tsx, packages/components/src/templates/next/components/complex/Image/Image.tsx
The image component is not supposed to have a `href` attribute, as it is not obvious that it is a link.
**Features**:
- Removed the `href` attribute from the image component.
```
Checking repository: ipos-corp-next
Schema patterns found in /schema/about-ip/patents/how-to-register/national-security-clearance.json
Schema patterns found in /schema/about-ip/trade-marks/how-to-register/how-to-register.json
Schema patterns found in /schema/about-ip/trade-marks/how-to-register/trade-marks-step-2.json
Schema patterns found in /schema/about-ip/patents/managing-patents/resolve-disputes/revoking-a-granted-patent.json
Checking repository: ncss-corp-next
Schema patterns found in /schema/campaigns-and-events/Beyond-the-Label.json
Schema patterns found in …
```
=> feat: remove href attribute in image component

apps/studio/package.json, apps/studio/src/features/editing-experience/hooks/useTextEditor.ts, package-lock.json, packages/components/src/interfaces/internal/AttrsDir.ts, packages/components/src/interfaces/internal/index.ts, packages/components/src/interfaces/native/Heading.ts, packages/components/src/interfaces/native/Paragraph.ts, packages/components/src/templates/next/components/internal/BaseParagraph/BaseParagraph.tsx, packages/components/src/templates/next/components/native/Heading/Heading.stories.tsx, packages/components/src/templates/next/components/native/Heading/Heading.tsx, packages/components/src/templates/next/components/native/Paragraph/Paragraph.stories.tsx, packages/components/src/templates/next/components/native/Paragraph/Paragraph.tsx, packages/components/src/templates/next/components/native/Prose/Prose.tsx
Closes https://linear.app/ogp/issue/ISOM-1683/arabic-auto-right-to-left-rtl-display
- Details ...
**Features**:
- Add tiptap editing support using the `tiptap-text-direction` extension
- Update `Heading` and `Paragraph` schema to accept `attrs: { dir }` + Update the display to show them
Text from MUIS
--
--
https://github.com/user-attachments/assets/4d5a37e3-dd70-4c51-ba86-d84b0c444656
---
- `tiptap-text-direction` : for studio
=> isom-1683 arabic auto RTL display

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/generated/selectableTypes.ts, apps/studio/prisma/migrations/20241126162857_drop_preferred_name_column/migration.sql, apps/studio/prisma/migrations/20241127035129_drop_site_member_table/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/src/components/Intercom.tsx, apps/studio/src/server/modules/me/me.select.ts, apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/msw/handlers/me.ts
Closes https://linear.app/ogp/issue/ISOM-1685/cleanup-unused-tables-and-columns-in-database
Currently we have both `name` and `preferredName` columns in `User` table. However,
- they serve the same purpose and is overlapping
- it overcomplicates the name being used for Intercom
- Details ...
- drop `preferredName` from `User` table 
- logic for intercom's name is "name" -> "email" username
FYI: have did a cleanup of the PROD database to ensure `name` column that will be used is beautified
=> intercom drop preferredname

packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/interfaces/complex/Infopic.ts
previously, our image alt text had no max length. 
1. add a max length of 120 - same as our other components and close enough to wcag recommendation of 125
=> chore: add max length for alt text

apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx
no ticket but came across this issue where the "move resource" modal does not have spacing between the cross button and the title
- Details ...
**Bug Fixes**:
- add a margin right (similar to linkeditor modal)
**BEFORE**:
**AFTER**:
=> fix - no spacing between title and cross button for movemodal

apps/studio/src/features/editing-experience/components/ActivateRawJsonEditorMode.tsx, apps/studio/src/features/editing-experience/components/AdminModeStateDrawer.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/RawJsonEditorModeStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/hooks/useIsUserIsomerAdmin.ts, apps/studio/src/lib/growthbook.ts, apps/studio/src/types/editorDrawer.ts
The migrators need to be able to edit certain pages directly and Studio may not be able to support their editing use cases at the moment.
**Features**:
- Allow editing and saving of the raw JSON content inside the admin mode.
- NOTE: This is still a safe operation as entering the admin mode is a hidden feature, and there is both frontend and backend schema validation to ensure that the data sent via this mode conforms to the schema. Hence, even if agency users find out about this, there is no way to corrupt the page data.
- Also renamed "admin mode" to "raw JSON editor mode" to differentiate with the future God mode feature.
**BEFORE**:
**AFTER**:
https://github.com/user-attachments/assets/752428c7-e0c6-451f-817f-b4b57b80f649
=> feat: introduce raw JSON editor mode to replace admin mode

apps/studio/src/components/Searchbar/CommandKey.tsx, apps/studio/src/components/Searchbar/SearchModal.tsx, apps/studio/src/components/Searchbar/Searchbar.tsx
The base search bar does not have the command key UI and makes it confusing when users see the command key in the modal
Add the command key to the base modal
=> chore: add command key to base search bar

apps/studio/src/components/AppNavbar.tsx, apps/studio/src/components/SearchableHeader.tsx, apps/studio/src/constants/layouts.ts, apps/studio/src/features/dashboard/SiteList.tsx, apps/studio/tests/msw/handlers/sites.ts
Addresses the quick style fixes in https://opengovproducts.slack.com/archives/C06R4DX966P/p1733101118649869?thread_ts=1732149974.756949&cid=C06R4DX966P
- Details ...
**Features**:
- Details ...
- Site name label should be subhead-1
- Site name label should allow up to 2 lines and then truncate
**Bug Fixes**:
- Header padding-y (spacing left of Isomer symbol, right of avatar) should be 20px to be consistent with Dashboard
=> minor style fixes to site dashboard page

apps/studio/src/components/Searchbar/SearchModal.tsx, apps/studio/src/components/Searchbar/SearchModalBodyContentStates.tsx, apps/studio/src/components/Searchbar/SearchResult.tsx, apps/studio/src/components/Searchbar/SearchResultHint.tsx, apps/studio/src/hooks/useResourceLocalViewHistory.ts, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/index.tsx, apps/studio/src/schemas/resource.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/stories/Page/Search.stories.tsx, apps/studio/tests/msw/handlers/resource.ts
Improve global search based on https://opengovproducts.slack.com/archives/C06R4DX966P/p1732866658371749
- Details ...
**Features**:
- added `useResourceLocalViewHistory` to store user recently viewed history (based on site) on their localstorage
- add to view history when opening and viewing a resource (only page, not folder or links)
- added a hint component that will show during
- no search result
- searching on the 3rd search query everytime the modal open (resets on close) 
- added stories 
https://github.com/user-attachments/assets/370dd08c-4601-4cdd-8da8-300a06c92b01
note: adjusted to be after the 3rd one since 2nd one might be a bit annoying IMO during development
https://github.com/user-attachments/assets/fad2972e-4b4c-4611-9f64-dff54570d4bb
=> Global search improvement (text hint + display personalized recently viewed)

apps/studio/src/server/modules/resource/resource.router.ts
https://github.com/opengovsg/isomer/pull/912 introduces `searchWithResourceIds` endpoint but the endpoint throws 500 error code when empty array passed in for `resourceIds`
this PR aims to reduce the error and false positive noise in our logs
- Details ...
**Bug Fixes**:
- return empty array if `resourceIds` is empty array
=> quick fix - searchWithResourceIds returns 500 error if empty array

apps/studio/public/assets/css/preview-tw.css, packages/components/src/templates/next/components/complex/Accordion/Accordion.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx
Closes https://opengovproducts.slack.com/archives/C07CWUNUL68/p1733212670307009
> I think it's cos we applied a margin-top only when an accordion is :first-of-type. So when you have groups of accordions, only the first groups gets a top margin.
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- update to use `mt-7` by default and only `mt-0` if preceeded by another `<details>` (accordion)
**BEFORE**:
**AFTER**:
- added a story in Content layout
=> Fix multi accordion top margin

apps/studio/Dockerfile, apps/studio/prisma/schema.prisma
```
Unable to require(`/app/apps/studio/node_modules/.prisma/client/libquery_engine-linux-musl.so.node`).
The Prisma engines do not seem to be compatible with your system. 
Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
Details: Error loading shared library [libssl.so](http://libssl.so/).1.1: 
No such file or directory (needed by /app/apps/studio/node_modules/.prisma/client/libquery_engine-linux-musl.so.node)
```
More: https://opengovproducts.slack.com/archives/CK9GGK6EP/p1733812366391449
- Details ...
**Bug Fixes**:
- fix alpine image to version 3.20 (https://github.com/prisma/prisma/issues/25817#issuecomment-2529926082)
- reason: since there's a PR in `prisma` for this issue, i'm **assuming** this will be …
=> fix prisma linux-musl loading issue

apps/studio/public/assets/css/preview-tw.css, packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
Closes https://linear.app/ogp/issue/ISOM-1688/add-view-all-articles-link-to-infocards
- Details ...
**Features**:
- add hidden `url` and `label` to Infocards schema
- add UI for infocards (inspiration from KeyStatistics)
https://www.loom.com/share/ba385efc529f46adac234ebd07cdfd42?sid=ec9dc6bd-9148-4dec-987e-7f4d9b2dee9e
```
"label": "This is a CTA",
"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
```
=> isom-1688 add view all articles link to infocards

apps/studio/src/components/PageEditor/FileAttachment.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/constants.ts
Previously there's an arbitrary limit of 5mb, which is insufficient for some agencies' use cases
- Details ...
- allow different file sizes
- allow up to 20mb
https://www.loom.com/share/a9dd8151f00d47ad92a6d82b58ad2212?sid=5b27a564-c0f0-434b-b369-cb69f4c5ef94
| test case | sample doc |
| - | - |
| .csv | https://github.com/datablist/sample-csv-files |
| .xls | https://community.tableau.com/s/contentdocument/0694T000001GnpUQAS |
| .xlsx | https://examplefile.com/file-download/564 |
| .tsv | https://getsamplefiles.com/download/tsv/sample-1.tsv |
| over 20mb | https://examplefile.com/document/pdf/30-mb-pdf |
=> Increase file attachment to 20mb

packages/components/src/templates/next/components/complex/Infobar/Infobar.stories.tsx, packages/components/src/templates/next/components/complex/Infobar/Infobar.tsx
Came across this issue where infobar has an additional div when there's no CTA at all
- Details ...
**Bug Fixes**:
- do not render the CTA parent div if there's no primaryCTA or secondaryCTA
**BEFORE**:
**AFTER**:
review the "No CTA" story for infobar on storybook
=> Fix - infobar additional div when there's no CTA

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/components/PageEditor/constants.ts, apps/studio/src/features/editing-experience/constants.ts, packages/components/src/interfaces/complex/LogoCloud.ts, packages/components/src/interfaces/complex/index.ts, packages/components/src/schemas/components.ts, packages/components/src/templates/next/components/complex/LogoCloud/LogoCloud.tsx, packages/components/src/templates/next/render/render.tsx, packages/components/src/templates/next/render/renderComponentPreviewText.ts
logo cloud requires an update in `renderComponent` so that it can be rendered successfully from the `content` of the page
1. add the associated schema over to schemas
=> feat(logo cloud): add schema for rendering 

apps/studio/src/lib/logger.ts
the default starter kit logger uses `NODE_ENV` for env and automatically injects it, which causes wrong parsing on dd logs as it should always be set to `production` - see [here](https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production)
use our `NEXT_PUBLIC_APP_ENV` instead
=> chore: fix env

apps/studio/src/features/dashboard/components/DirectorySidebar/useIsActive.ts
we were previously using the wrong property, leading to collections not having the correct state in side bar when we are already in the collection
update to correct property 
1. Click into a collection
2. the sidebar should be highlighted for the collection
=> fix: collections active state

apps/studio/src/server/modules/collection/collection.service.ts
Collection (article page header) can be saved when article summary is required. 
This is because we set it to be an empty string by default, which technically passes the validation
However, this is not aligned with the gold standards as we want users to provide this value
- Details ...
**Bug Fixes**:
- set a default non-empty string value
**BEFORE**:
**AFTER**:
=> add placeholder for article summary

apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/src/templates/layouts/AdminSidebarOnlyLayout.tsx
isomer guide v4 not out yet and existing guide is about CMS - can be misleading to users
- Details ...
**Bug Fixes**:
- remove guide icon
=> hotfix - remove isomer guide from sidebar

packages/components/src/interfaces/internal/CollectionCard.ts, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/Tag/Tag.tsx, packages/components/src/templates/next/components/internal/Tag/index.tsx
We need to support tagging in our collections for the CLS use case. this PR adds the initial collection tags in 
1. Add an internal `Tag` component for use
2. Add this `Tag` to the `CollectionCard`
=> feat(collection tags): frontend changes for tags in collection

packages/components/src/interfaces/internal/CollectionCard.ts, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/layouts/Collection/Collection.stories.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/utils.ts, packages/components/src/templates/next/types/Filter.ts, packages/components/src/types/page.ts, packages/components/src/types/sitemap.ts, tooling/build/scripts/publisher.sh, tooling/build/scripts/publishing/index.ts, tooling/build/scripts/publishing/package-lock.json, tooling/build/scripts/publishing/package.json, tooling/build/scripts/publishing/tsconfig.json, tooling/build/scripts/publishing/types.ts, tooling/build/scripts/publishing/utils/getIndexPageContent.ts
This PR adds filtering to collections through the use of tags. 
1. add `Tags` to the schema on `CollectionPagePageSchema`
- note that in our publishing script, we explictly check for whether it's a `PAGE_RESOURCE_TYPE`, which means that even though the schema can only expose it on page items. we might want to expose it on files, which would necessitate a slight change inhow we generate hte `SitemapEntries`. not too sure if this is what we want, so i omitted it for now. need to think abit more here
2. add tags to `publishing/index.ts` so that it gets written to the sitemap entry (and hence, to disk)
3. in `Collection`, extract the `tags` from the `Sitemap`. add filtering logic onto our collection so that it will display the correct cards on filter click. take note that the logic here can …
=> feat(multi-tags): add filtering to collections

packages/components/src/interfaces/internal/ArticlePageHeader.ts, packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.stories.tsx, packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/layouts/Article/Article.stories.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx, packages/components/src/types/page.ts, tooling/build/scripts/publishing/index.ts
we need to add tags to article pages
1. add the prop to `Article` - specified as props **and not on schema** because we don't want users to be able to add this on studio yet
2. pass the props down to `ArticlePageHeader` and render it
=> feat: add tags to articles

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/dashboard/components/PageSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/CreateCollectionPageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx
Some places don't show the full UI but we should always show the full UI everywhere. this also fixes a bug with the page settings modal where we were calling the wrong function for the close button
1. update the creation modal to fetch the full permalink from the backend and show it
2. update the **pagecreationmodal** so that it uses a grid. this is because removing the left adornment makes the left section squished and shorter than required. 
3. update the folder settings modal to use the full url also (similar fashion as ^) 
4. update the box to use a `Suspense` so that we can load in the folder setings modal quickly
1. create a page in both folder and collection 
2. the page should show the full url on the details screen
3. type an extremely long url 
4. click on settings for a nested …
=> fix(url): show full urls everywhere in UI

apps/studio/src/features/editing-experience/components/CreatePageModal/CreatePageWizardContext.tsx
Loading state for button on root page was stuck in loading
1. set the `isLoading` state to be preferentially from `isLoading` and fallback to `isLoadingPermalink` only if `folderId` is defined
1. create a page at root
2. make sure that you can create such a page
=> fix: isloading

tooling/build/scripts/publisher.sh, tooling/build/scripts/publishing/package.json
last week we did a hotfix (https://github.com/opengovsg/isomer/pull/948, https://github.com/opengovsg/isomer/pull/949) due to PROD deployment failure
it's safe to revert it back after https://github.com/opengovsg/isomer-next-infra/pull/49 since we will be referencing the latest tag
in fact, this is stopping us from building on staging as `tooling/build/scripts/publishing/index.ts` is using referencing from `import { ResourceType } from "~generated/generatedEnums"`
- Details ...
**Bug Fixes**:
- update back to use `tsx`
=> add back tsx

apps/studio/prisma/constants.ts
currently prisma constants say @alexanderleegs email is `alex` which creates email `alex@open.gov.sg`
however that's incorrect so he won't be having access to sites, which can be important/required for on call
- Details ...
**Bug Fixes**:
- change name
=> replace "alex" with "alexander"

apps/studio/src/pages/sites/[siteId]/collections/[resourceId].tsx, apps/studio/src/pages/sites/[siteId]/folders/[folderId]/index.tsx
Currently breadcrumbs are not using `next/link`, thus causing long load time between pages
- Details ...
**Bug Fixes**:
- add `next/link` to make use of nextjs's prefetching to reduce load time and improve UX
=> fix - use next/link for breadcrumbs for folders and headers

apps/studio/src/components/CmsSidebar/CmsContainer.tsx
Pagination in collection are cut-off if there's too many items in the page
- Details ...
**Bug Fixes**:
- replace parent's overflow from `hidden` to `auto`
**BEFORE**:
**AFTER**:
=> fix collection pagination hidden

packages/components/src/templates/next/components/complex/LogoCloud/LogoCloud.stories.tsx
storybook has intermittent issue with placeholder for logo cloud rendering
on local, seems like `via.placeholder.com` is not very fast and thus can be causing the error (sometimes not rendering on chromatic)
- Details ...
**Bug Fixes**:
- switch to placehold.co - align with the other stories we use
=> logocloud storybook - replace placeholder.com with placehold.co

packages/components/src/interfaces/complex/LogoCloud.ts, packages/components/src/templates/next/components/complex/LogoCloud/LogoCloud.stories.tsx, packages/components/src/templates/next/components/complex/LogoCloud/LogoCloud.tsx
1. logocloud requires `assetsBaseUrl` for relative links but `site` already has this - we should account for this and just derive it from `site` 
2. studio uses `title` to render so now for logocloud it's showing `Title` (see SS)
1. update logocloud from using `assetsBaseUrl` to using `site.assetsBaseUrl`
2. update `title` in the schema to `Logocloud component`
1. open up studio
2. add a logocloud component
3. add a relative url
4. the image shuold render without issue
5. for the title, it shuold display logocloud component
- none -> because now it's no longer picking up the property post release and it's isntead deriving from sites.
https://github.com/user-attachments/assets/1101fb41-e89e-48dc-89f6-cc997230502d
=> refactor: logocloud

apps/studio/public/assets/css/preview-tw.css, packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx
Closes https://linear.app/ogp/issue/ISOM-1646/infocards-and-infocols-should-behave-consistently-when-something-opens
- Details ...
**Bug Fixes**:
add check if it's external URL, and if so:
1. rotate the icon if it is (couldn't find a corresponding diagonal arrow of similar styles)
2. opens in new tab
1. Go to a page and add a Infocards component
2. [ ] By default, the default endpoint is "https://www.google.com" so it should show right-up arrow
3. [ ] Update the link of one of the cards to link to one of the internal page - it should show right arrow 
4. [ ] Save and publish, and check if the external link on the new site opens in a new url
1. Go to a page and add a Infocols component
2. [ ] Add an external link for one of the cols - it should show right-up arrow
3. [ …
=> isom-1646 - infocards and infocols should behave consistently when opens in a new link

packages/components/src/templates/next/components/internal/FontPreload.tsx, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
Closes https://linear.app/ogp/issue/ISOM-1710/lighthouse-performance-preconnect-to-google-font
Currently we are using google font but not preconnecting thus causing latency between 80ms to 200ms, which impact Lighthouse Performance score
- Details ...
**Features**:
- Add `FontPreload` component and pass it into `Skeleton`
screenshot of `<head>` for local build
Trigger a new codebuild and verify that these two can be found in the `<head>`
```
<link
rel="preconnect"
href="https://fonts.gstatic.com"
crossOrigin="anonymous" // required when making requests to a different origin
/>
<link
rel="dns-prefetch"
href="https://fonts.gstatic.com"
/>
```
Run a lighthouse on the page and the red warning should not show under Performance section too
=> isom-1710 lighthouse performance preconnect to google font

apps/studio/prisma/scripts/FileLogger.ts, apps/studio/prisma/scripts/moh-tosp/README.md, apps/studio/prisma/scripts/moh-tosp/backupCollectionById.ts, apps/studio/prisma/scripts/moh-tosp/createCollectionFromLocal.ts, apps/studio/prisma/scripts/moh-tosp/deleteCollectionById.ts, apps/studio/prisma/scripts/moh-tosp/publishDraftCollection.ts
Needed scripts to manage collection resources in the database for content migration.
Closes ISOM-1700
**Features**:
- Added script to backup collections and their resources to JSON files
- Added script to create new collections from local JSON files
- Added script to safely delete collections and their associated resources
- Added script to publish draft collections and their child resources
- `backupCollectionById.ts`: Backs up a collection and its resources to JSON files
- `createCollectionFromLocal.ts`: Creates a new collection from local JSON content
- `deleteCollectionById.ts`: Safely deletes a collection and all associated resources
- `publishDraftCollection.ts`: Publishes a draft collection and its child resources
Scripts should be tested with: …
=> Add collection management scripts for MOH TOSP

packages/components/src/templates/next/components/complex/Image/ImageClient.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.tsx
Partially closes https://linear.app/ogp/issue/ISOM-1697/huge-images-on-next-sites
- Details ...
- lazy load image on sites by default
- except for Navbar since it will always be above the fold
- hero is using backgroundUrl and not ImageClient so not affected 
1. trigger a codebuild
2. open the newly built site 
3. check dev console and that images have `loading: lazy` attribute
=> isom-1697 huge images on next sites (lazy loading)

apps/studio/src/stories/Flows/CreateCollectionItemFlow.stories.tsx, apps/studio/src/stories/Flows/CreateNewPageFlow.stories.tsx, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditCollectionLink.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditHomePage.stories.tsx, apps/studio/src/stories/Page/SitePage.stories.tsx, packages/components/src/templates/next/components/internal/Filter/Filter.stories.tsx
`waitFor` causes inconsistent behaviour on
- development _(might be my setup, but i don't think so?)_ and
- sometimes production (re: https://github.com/opengovsg/isomer/pull/968 storybook failing intermittently but working fine when manually trigeering it in storybook online)
This made it rather hard to trust/use storybook locally to debug and test certain interactions
https://github.com/user-attachments/assets/759f437d-774e-42de-b5d5-43ff88928b8f
- Details ...
- given that most of our "wait" is for UI elements to update, we can simply replace `waitFor` and `get*` with `findBy*`. This also reduce the code complexity and improve readability
=> remove waitFor in storybook

apps/studio/public/assets/css/preview-tw.css, packages/components/src/templates/next/components/internal/Navbar/NavItem.tsx
Closes https://linear.app/ogp/issue/ISOM-1709/[lighthouse-seo]-non-dropdown-link-in-navbar-does-not-have-descriptive
- Details ...
- do not wrap non-dropdown navbar item in `<span>`
=> isom-1709 - chore: do not wrap link text in span

.github/workflows/ci.yml, packages/components/src/utils/__tests__/getParsedData.test.ts, packages/components/src/utils/getParsedDate.ts
date in collection preview is one day behind on studio
- Details ...
**Bug Fixes**:
- add a 8h addition to date to account for SG timezone
**BEFORE**:
**AFTER**:
1. create a link in a collection
2. select a date
3. the date in the date selector and that in the preview should be the same
=> fix getParsedDate - add 8h to account for timezone

tooling/build/scripts/publishing/index.ts, tooling/build/scripts/publishing/types.ts, tooling/build/scripts/publishing/utils/getResourceImage.ts
Not all collection has images in their `page.image`, which can result in ugly-and-inconsistent looking display on Collection layout
Closes https://opengovproducts.slack.com/archives/C07CWUNUL68/p1735799689732969?thread_ts=1735799448.795359&cid=C07CWUNUL68
- Details ...
- fallback to the first `image` component (`src` and `alt`) if `page.image` is undefined
**Note: tested to work on staging**
1. create a collection item and use raw editor json mode to display
```json
{
"page": {
"date": "27/12/2024",
"title": "asdf",
"category": "Feature Articles",
"lastModified": "2024-12-29T18:17:09.452Z",
"articlePageHeader": {
"summary": "A concise summary of the main points regarding this article."
}
},
"layout": "article",
"content": [
{
"alt": "my alt text", …
```
=> pass in first image "src" if page.image is undefined

tooling/build/scripts/generate-sitemap.js
The image thumbnail for collection is not applying for GitHub sites.
**Bug Fixes**:
- Duplicate the image thumbnail logic to generate-sitemap.js which is used for GitHub sites.
=> fix: duplicate image thumbnail logic for GitHub sites

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsProseControl.tsx
When users type in tiptap, the cursor will jump. This is caused by the `useEffect` we have which was necessary to ensure data is repopulated back when user dismisess the "are you sure you want to drop changes" modal
RE: https://opengovproducts.slack.com/archives/C07CWUNUL68/p1736426201036129
- Details ...
**Bug Fixes**:
- to note the cursor position and add it back
1. on studio, create a Callout component with some text. Save the component
2. open the component again. Put your cursor in the middle of the text and start typing - your cursor should not jump to the end of the text
=> fix - set selection on update for tiptap

packages/components/src/templates/next/components/internal/BlogCard/BlogCard.stories.tsx, packages/components/src/templates/next/components/internal/BlogCard/BlogCard.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
The collection blog variant has a couple of design issues that were raised by CSA.
**Bug Fixes**:
- Removed the `capitalize` function to respect the original capitalisation of the tag category provided by the user.
- Added a small gap between different tag categories.
- Added `whitespace: pre-wrap` so that newlines can be handled properly in the collection card description. Also switched Text back to the `p` tag for simplicity.
=> fix: adjust design for collection blog variant

apps/studio/src/features/dashboard/components/DeleteResourceModal/DeleteResourceModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/components/PublishButton.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsImageControl.tsx, apps/studio/src/pages/sites/[siteId]/pages/[pageId]/settings.tsx, apps/studio/src/pages/sites/[siteId]/settings.tsx
We have a migrator that complained that the publish toast message is blocking the search bar, and valuable productive time is lost waiting for the toast message to disappear.
- Make the publish toast message dismissable.
https://github.com/user-attachments/assets/8d4860e7-0690-47a6-956e-2b6a04374489
=> chore: make publish toast message dismissable

packages/components/src/templates/next/components/internal/FontPreload.tsx, packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerPreload.tsx, packages/components/src/templates/next/components/internal/GoogleTagManager/index.ts, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/components/internal/utils/PreloadHelper.tsx, packages/components/src/templates/next/components/internal/utils/index.ts, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
Similar to https://github.com/opengovsg/isomer/pull/966, we can preload GTM to improve loading speed
- Details ...
- preload GTM
- refactor into `PreloadHelper`
=> improve lighthouse performance score - preload GTM 

packages/components/src/interfaces/internal/Vica.ts, packages/components/src/interfaces/internal/index.ts, packages/components/src/templates/next/components/internal/Vica/Vica.tsx, packages/components/src/templates/next/components/internal/Vica/index.ts, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx, packages/components/src/types/site.ts
Add integration for VICA
- Details ...
**Features**:
Refer to this slack message for installation guide: https://opengovproducts.slack.com/archives/C087MUEJAMA/p1736330772752669?thread_ts=1736245461.677389&cid=C087MUEJAMA
**_note: decided to follow vica's way of specifying the keys and values as will be easier to port over from agency_**
- Add Vica stylesheet and widget component
- Add vica props to siteprops
- todo - clarifying with VICA on usage of props to pass in colour config (installation guide wasn't clear). In the meantime, we can manually pass it in via the props
note: slightly tricky to test as we will need to get the app-id and app-name from agencies
1. add the necessary vica config in `site` in the Site table 
2. rebuild and see if it shows up
=> feat: vica integration

packages/components/src/engine/index.ts, packages/components/src/engine/metadata.ts, tooling/template/app/[[...permalink]]/page.tsx
Closes https://linear.app/ogp/issue/ISOM-1719/test-sites-can-be-indexed-by-search-engine
while staging sites have `disallow` in `robots.txt`, according to [google](https://developers.google.com/search/docs/crawling-indexing/robots/intro)
> A page that's disallowed in robots.txt can still be indexed if linked to from other sites.
While Google won't crawl or index the content blocked by a robots.txt file, we might still find and index a disallowed URL if it is linked from other places on the web. As a result, the URL address and, potentially, other publicly available information such as anchor text in links to the page can still appear in Google search results. To properly prevent your URL from appearing in Google search results, [password-protect the files on your …
=> isom-1719 non-prod sites can be indexed by search engine

packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx
Visual jank, the no results message should be center-aligned to the entire results area. Currently it's on the left column.
After:
Storybook screen capture for blog layout story:
=> fix: empty results message is at a wrong position in blog layout 

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx
Previously, we were using the `title` of the folder to show in the folder settings modal
pass the current `permalink` in so it shows the permalink in the modal
1. create a folder at root
2. update the folder `permalink`
3. it should show the new `permalink` rather than the title
4. create a folder inside the previous folder
5. repeat steps 2-3
=> fix: use permalink for folder settings and not title

packages/components/src/interfaces/complex/Contentpic.ts, packages/components/src/interfaces/complex/Image.ts, packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/interfaces/complex/LogoCloud.ts, packages/components/src/templates/next/components/complex/Contentpic/Contentpic.tsx, packages/components/src/templates/next/components/complex/Image/Image.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/complex/LogoCloud/LogoCloud.tsx, packages/components/src/templates/next/render/doesComponentHaveImage.ts, packages/components/src/templates/next/render/render.tsx, packages/components/src/templates/next/render/renderPageContent.ts
_**Note: not urgent, good-to-have improvement**_
Follow up enhancement of https://github.com/opengovsg/isomer/pull/967. 
We followed next.js convention and lazy loaded all images. While the overall sites' lighthouse performance score has shown improvement, there are further rooms for improvement for certain pages.
For example, some pages have images above the fold being lazy loaded, thus having poor lighthouse score
- Details ...
**Tested to be working on STG**
- use `doesComponentHaveImage` to determine which component has images
- in `renderPage`, pass in `shouldLazyLoad` into the components (true if they are the first component, and false otherwise)
1. go to a page in Studio and add multiple different components with images
2. publish the page and …
=> improve lighthouse performance - do not lazyload above-fold image

packages/components/src/interfaces/complex/KeyStatistics.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.tsx, packages/components/src/templates/next/components/internal/ScrollToTop.tsx, packages/components/src/templates/next/components/internal/index.ts, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
Closes https://linear.app/ogp/issue/ISOM-1714/bug-scroll-position-doesnt-reset-for-internal-links
related issue: https://github.com/vercel/next.js/issues/45187 (still happening with nextjs in next 14)
- Details ...
**Bug Fixes**:
- adding a `ScrollToTop` component to `Skeleton`
- update KeyStats and Infocards to use `LinkComponent` (currently left out)
**Tested on staging to work**
1. trigger a new build on codebuild
2. scroll down and click on any internal link. It should scroll user to the top of the page instead of retaining their existing scroll position
=> isom-1714: Fix missing autoscrolling for next/link

apps/studio/public/assets/css/preview-tw.css, package-lock.json, packages/components/.storybook/main.ts, packages/components/.storybook/preview.tsx, packages/components/package.json, packages/components/public/mockServiceWorker.js, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.stories.tsx, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBanner.tsx, packages/components/src/templates/next/components/complex/DynamicDataBanner/DynamicDataBannerClient.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
New UI requirement to reduce screen estate on desktop and mobile
- Details ...
- replace `storybook-addon-mock` with `msw` and `msw-storybook-addon` (consistent with Studio)
- update UI based on new requirements in Figma
- add loading state
- shifted the position in homepage stories to above the hero since that's the real world use case
(refer to storybook)
1. add the dynamic data banner component via raw json mode (since its not supported in studio)
```json
{
"type": "dynamicdatabanner",
"apiEndpoint": "https://isomer-user-content.by.gov.sg/muis_prayers_timetable_2025.json",
"title": "hijri_date",
"data": [
{
"label": "Subuh",
"key": "subuh"
},
{
"label": "Syuruk",
"key": "syuruk"
},
{
"label": "Zohor",
"key": "zohor"
},
{
"label": "Asar",
"key": …
```
=> Chore tweak dynamicdatabanner UI

apps/studio/src/features/editing-experience/components/ActivateRawJsonEditorMode.tsx, apps/studio/src/features/editing-experience/components/EditLinkPreview.tsx, apps/studio/src/features/editing-experience/components/LinkEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/RawJsonEditor.tsx, apps/studio/src/features/editing-experience/components/RawJsonEditorModeStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
The raw JSON editor mode is not available for collection links, which adds ops load to engineers when migrators need to change tags (e.g. for REACH).
**Features**:
- Extended the existing raw JSON editor mode to the collection links editor. This involved:
- Small refactor of ActivateRawJsonEditorMode.tsx to allow the consumer to determine the action to take after a successful activation (removed the dependency on the EditorStateDrawer context).
- Refactored RawJsonEditorModeStateDrawer.tsx by extracting out the UI from the business logic, so that the UI can be reused by the LinkEditorDrawer.
- Extended LinkEditorDrawer to handle two states - root and rawJsonEditor states. Also split the existing page state into a saved and preview version, so that the raw JSON editor …
=> feat: enable raw JSON editor mode for collection links

apps/studio/src/server/modules/collection/collection.router.ts
Published collection links do not have a draftBlobId, which causes an error in saving published collection links.
**Bug Fixes**:
- Use the correct function to update the blob (updateBlobById), as that function handles creating the draftBlobId if it is not present.
=> fix: allow editing of published collection links

packages/components/src/templates/next/components/internal/BackToTopLink.tsx, packages/components/src/templates/next/components/internal/utils/PreloadHelper.tsx, packages/components/src/templates/next/layouts/Collection/CollectionClient.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx
Closes https://linear.app/ogp/issue/ISOM-1720/bug-back-to-top-doesnt-work-on-template
- Details ...
Findings
- Bug occured after https://github.com/opengovsg/isomer/commit/b7f73e2d298826b16e7d8d5e0677bb89ea4bb668
- doesn't seem to be anything relating to next/link directly, and couldn't find anything online about how adding <link> will break nextjs
- [nextjs provides a way to add preconnect and dnsprefetch](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#link-relpreconnect). However, it did not state that it must be done this way. In addition, this is only available in React19 which we aren't on.
- Decided to not spend more time on this issue
**Bug Fixes**:
- hotfix: replace next/link with pure <a>
1. publish a new build
2. go to a collection and …
=> isom-1720 bug back to top doesnt work on template

apps/studio/next.config.mjs
Isomer Studio lacks the Strict Transport Security header.
- Add the Strict Transport Security header to Next.js list of headers.
=> chore: add strict transport security header

tooling/build/scripts/publishing/index.ts
Nested folder resources are not properly retrieved, which causes the casing in the index page to not be correct for those cases.
**Bug Fixes**:
- Correctly retrieve the folder resource using the full permalink instead.
- Repeat #1000 but for nested folders.
=> fix: properly retrieve nested folder resources

apps/studio/src/features/editing-experience/components/LinkEditorDrawer.tsx
The publish button is not shown as active when a collection link is updated.
**Bug Fixes**:
- Invalidate the `readPage` procedure upon a successful save of the collection link.
=> fix: invalidate publish button on link save

apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/user/__tests__/user.service.test.ts, apps/studio/tests/integration/helpers/seed/index.ts
Deleted users were still able to access the system and view sites they previously had access to.
Closes ISOM-1701
Added checks to prevent deleted users from logging in and viewing sites they previously had access to.
**Breaking Changes**:
**Features**:
- Added user deletion status check during login
- Filtered out sites where user permissions have been deleted
- Removed debug console log from user deletion check
- Added test for login attempt with deleted user
- Added test for site listing with deleted permissions
- Added user service tests for checking deletion status
- Added helper function for setting up test users with deletion status
None
None
None
=> add tests and handling for deleted users

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20241220130729_add_deletedat_user_perms/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/seed.ts, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/user/__tests__/user.service.test.ts, apps/studio/src/server/modules/user/user.service.ts, apps/studio/src/server/trpc.ts, apps/studio/src/utils/email.ts, apps/studio/tests/integration/helpers/auth.ts, apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/integration/helpers/seed/index.ts, apps/studio/tests/msw/handlers/me.ts
Closes ISOM-1701
**Features**:
- Added soft delete functionality for Users and ResourcePermissions via `deletedAt` column
- Added user deletion check during email authentication flow
- Enhanced permission queries to exclude soft-deleted records
- Added filtering for deleted users in ongoing sessions
**Bug Fixes**:
- Fixed potential security issue where deleted users could still access the system with active sessions
- Verify soft delete functionality for Users, by setting deletedAt to any valid timestamp
- Users with deletedAt in the User table should not be able to login
- Users who are already logged in with an active session should be logged out when the deletedAt is set in User table
- Users can have Resource Permissions to several sites. If a …
=> add soft delete for users and permissions

apps/studio/src/components/ResourceSelector/ResourceItem.tsx, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/resource/resource.router.ts
index pages display in the sidebar but not in the main view - we should **not** be showing such index pages for reasons outlined [here](https://opengovproducts.slack.com/archives/C06R4DX966P/p1736932453085539)
1. update typing using `Exclude` in router method
2. add filter for `IndexPage`
1. add a custom index page in db
2. verify that this cannot be seenin the sidebar
=> fix: show index page

packages/components/src/utils/__tests__/getReferenceLinkHref.test.ts, packages/components/src/utils/getReferenceLinkHref.ts, packages/components/src/utils/validation.ts
The regex used to identify asset links is too general, which can give false positives when the root folder's permalink is just numbers.
**Bug Fixes**:
- Properly detect asset links by including the UUID v4 portion as part of the asset links regex.
=> fix: refine regex used to identify asset links

apps/studio/src/pages/sites/[siteId]/admin.tsx, apps/studio/src/schemas/site.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/src/templates/layouts/AdminSidebarOnlyLayout.tsx
Ops load on engineers is quite high for editing the site config, navbar and footer.
**Features**:
- Add a new `/admin` route for Isomer Admins to directly modify the site's config, theme, navbar and footer items.
- Access to this feature is gated for just Isomer Admins, all other users will not know of its existence and even if they do, they will not have the permission to access the form to edit.
**View for Isomer Admins**:
**View for unauthorised users**:
=> feat: introduce temporary admin mode for site config

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/public/assets/css/preview-tw.css, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/PublishButton.tsx, apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsCategoryControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/index.ts, apps/studio/src/features/editing-experience/schema.ts, apps/studio/src/server/modules/page/page.router.ts, package-lock.json, packages/components/src/types/page.ts
Add dropdown for collections, see ticket for deets
1. use a db query to get all the category values - this takes the draft blob if it is there, otherwise it orders by the publishedAt and takes the latest one 
2. render this on the frontend as a dropdown of the values
3. Add a `Suspense` + `Skeleton` so there's a nice loading state
=> feat: dropdown for collections

packages/components/src/templates/next/components/internal/ArticlePageHeader/ArticlePageHeader.tsx, packages/components/src/templates/next/layouts/Article/Article.stories.tsx
- The article layout wasn't using the right tokens, it was using the old tailwind tokens. So the typography was a little off from other layouts.
- The title in the article layout is smaller than the Section Title.
Closes [ISO-161]
This is with the section title:
- Use the right tokens to match designs here https://www.figma.com/design/rsKQdmtyoOWawyAv1LkJJK/Isomer-Next-Component-Library?node-id=584-18886&t=mOp7e01PcMxtGaj3-1
- [Caveat] Using display-md for the title. This means that the article title and Section Title are the same size, but we can't fix it without rejigging the entire typographic scale.
=> Article layout is not using Isomer Next colour and type tokens

apps/studio/src/features/editing-experience/components/form-builder/FormBuilder.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsCategoryControl.tsx, apps/studio/src/lib/growthbook.ts, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditCollectionLink.stories.tsx, apps/studio/src/stories/Page/EditPage/components/JsonFormsCategoryControl.stories.tsx, apps/studio/src/stories/Page/EditPage/components/formBuilder.tsx, apps/studio/src/stories/utils/growthbook.ts, apps/studio/tests/msw/handlers/page.ts
We want to gate the dropdown for collections to hfpg only (siteId = 29) 
1. add growthbook feature key
2. retrieve key at runtime 
3. depending on feature key, render either text control (old) or the dropdown (new) 
1. go to site id = 7 
2. create a collection
3. create a page in the collection
4. the article category should be a dropdown
5. go to any other site id 
6. repeat steps 2-3 
7. the article category should be a free text field
=> chore: add gb

apps/studio/src/server/modules/page/page.router.ts
hotfix for https://github.com/opengovsg/isomer/pull/1048 - `getCategories` are used by folders too instead of only collections, and this query throw an error as it assumes theres only collections
- Details ...
**Bug Fixes**:
- remove conditional check for resource types
=> fix - remove conditional check for resoucetype

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextAreaControl.tsx
Closes https://linear.app/ogp/issue/ISOM-1504/page-editing-error-message-when-title-is-empty
- Details ...
**Bug Fixes**:
- wrap in custom error message wrapper
1. go to a content page (or create one)
2. click to edit "content page header"
3. remove the content of "content page summary". It should NOT say `Content page summary is a required property` but `Content page summary cannot be empty`
=> fix - add custom error message for JsonFormsTextAreaControl

apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditCollectionLink.stories.tsx
storybook failing intermittently - suspected its due to growthbook initialization taking more than the default timeout of `findByRole` of 1000ms
e.g. https://www.chromatic.com/test?appId=66543928751c844d159a31ef&id=67a050ef4c2883649ed2a658
- Details ...
**Bug Fixes**:
- explicitly overwrite the timeout to be 5000ms instead
=> fix - add explicit 5000ms timeout for growthbook

apps/studio/src/features/dashboard/components/CollectionTable/CollectionTable.tsx, apps/studio/src/features/dashboard/components/ResourceTable/ResourceTable.tsx
Closes https://linear.app/ogp/issue/ISOM-1723/table-on-studio-overflows-horizontally-so-buttons-disappear-on-smaller
there's a minwidth 1000px
- Details ...
**Bug Fixes**:
- remove minwidth
| before | after |
| - | - |
| <img width="1038" alt="image" src="https://github.com/user-attachments/assets/7d24e9d9-b632-4a7c-abcd-ce181cbb37ce" /> | <img width="1038" alt="image" src="https://github.com/user-attachments/assets/234deb4c-8583-436d-a52f-6f98ea3ca300" /> |
1. adjust screen size viewport to be smaller horizontally - the buttons should always be reasonably there
=> isom-1723 - fix studio table buttons disappear on smaller screen

apps/studio/src/components/Datatable/Datatable.tsx
Closes https://linear.app/ogp/issue/ISOM-1574/dashboard-each-row-should-have-hover
datatable missing hover colour as per figma design
- Details ...
**Bug Fixes**:
- add hover color to row
https://github.com/user-attachments/assets/60a6322e-9171-40e7-a0d7-b7cf84790cd5
- hover across the different rows - it should have colour. 
- note: as per figma design, only the name should be clickable
=> isom-1574 - fix: add hover color for datatable

packages/components/src/interfaces/internal/Vica.ts, packages/components/src/interfaces/internal/index.ts, packages/components/src/templates/next/components/internal/Vica/VicaWidget.tsx, packages/components/src/templates/next/components/internal/Vica/VicaWidgetClient.tsx, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx, packages/components/src/types/site.ts
currently
- we don't support image asset url from isomer assets bucket (unless we explicitly include the base url)
- colors are hardcoded (because VICA didn't get back to us)
- vica disappears in between navigation
- Details ...
- preprocess image url during build time and then pass into a client widget component (to prevent passing entire site to client side)
- pass in colors based on site config directly
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
=> vica: support asset URL + use site color + fix disappearing between navigation

packages/components/src/interfaces/complex/Image.ts, packages/components/src/types/page.ts
Allow custom thumbnail title and improve description copy
Updates the image schema to support custom titles and clarifies the thumbnail description text to be more user-friendly.
=> add configurable title for image schema

apps/studio/src/pages/sign-in/index.tsx
- Details ...
**Bug Fixes**:
- add width 100%
| before | after |
| - | - |
| ![Screenshot 2025-02-05 at 1 37 37 AM](https://github.com/user-attachments/assets/df98c0b3-af5a-4cb0-a9e6-12e4e23cbd3a) | ![Screenshot 2025-02-05 at 1 38 14 AM](https://github.com/user-attachments/assets/150b1a99-25b8-4935-8b14-01c6d3de6a97) |
1. go to login page on a wide screen - the page should be centralized (masthead should be entirety of the screen)
=> fix - sign in page not full width

.github/workflows/aws_deploy.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml, .github/workflows/deploy_uat.yml
- we have 2 unused variables for datadog, which are both removed here
- removed the variables, cross checked against `task-def` to make sure we weren't using them
=> chore: remove unused variables

apps/studio/src/features/editing-experience/components/LinkEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsDateControl.tsx, apps/studio/src/schemas/collection.ts, packages/components/src/types/page.ts
The collection item dates are currently required, but they should be optional because we already support the dateless variant for collections.
**Bug Fixes**:
- Set the date field to be optional for collection items (links and articles).
- Go to Studio and enter any collection.
- Edit any article page in the collection, remove the article date and save the page. Verify that the page can be saved.
- Edit any collection link in the collection, remove the item date and save the item. Verify that the page can be saved.
=> fix: set collection item dates to be optional

apps/studio/prisma/constants.ts
Rachel is not part of the Isomer admins when creating new sites.
- Add Rachel as Isomer admin, so she's automatically added as an admin for new sites.
=> chore: add rachel as Isomer admin user

tooling/build/scripts/generate-sitemap.js
The page ordering functionality that we have for Studio is not available for GitHub sites.
**Bug Fixes**:
- Duplicate the page ordering functionality that Studio has to GitHub sites.
=> fix: respect page ordering for GitHub sites

packages/components/src/templates/next/layouts/Article/Article.tsx
collection pages don't have back to top button
add back to top button below the content 
https://github.com/user-attachments/assets/eb75df60-b2dc-4d60-83db-b4b49ccc8ba0
1. open up a article page in a folder
2. scroll to bottom
3. click back to top
4. it should work
5. repeat steps 1-4 but for an article page inside a collection
=> chore: add back to top for article

apps/studio/src/features/dashboard/components/ResourceTable/ResourceTableMenu.tsx
index pages should not need to be updated - currently, isomer admins can update either name/permalink but the index page should have a fixed permalink and use the name of the containing directory (folder/collection), so this is wrong too
1. remove capability for isomer admins to update title/permalink
1. sign in as isomer admi
2. go to a collection
3. create index page
4. click the menu button
5. should not see an option to update the settings
6. repeat setps 2-5 but for folders
=> chore: prevent users from updating index page wrongly

apps/studio/eslint.config.mjs, apps/studio/src/components/PageEditor/TableSettingsModal.tsx, apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextAreaControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, apps/studio/src/features/sign-in/components/EmailLogin/VerificationInput.tsx, packages/components/eslint.config.mjs
we have a few imports that should be banned - this adds eslint rules to prevent them
1. add eslint rule to ban chakra imports that have duplicates in ogpds
2. add eslint rule to ban `next/navigation` in components
=> chore: add eslint rule

apps/studio/src/features/editing-experience/atoms.ts, apps/studio/src/features/editing-experience/components/LinkEditNavbar.tsx, apps/studio/src/features/editing-experience/components/LinkEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/PublishButton.tsx
1. users can publish empty links 
1. add a `ref` atom that we use **ONLY** to validate to see if a user can publish
2. this is only updated `onSave` - so we know it's accurate
3. we cannot use the other `linkAtom` as that's required for updating our UI
https://github.com/user-attachments/assets/6554f0fb-49da-47c3-8e05-27179477410d
1. create a new collection link 
2. ensure that publishing is blocked
3. add a ref
4. publishing shuold still be blocked
5. click save
6. publishing should be allowed
7. go back to the collection
8. repeat steps 1-2
=> chore: fix publishing for empty links

apps/studio/src/features/editing-experience/components/form-builder/components/LinkErrorBoundary.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/BaseLinkControl.tsx
Currently, when we delete a link and go back to an item that is referencing it, we will see an error page with no way for the user to self resolve; this isn't ideal
1. add error boundary and use it in `BaseLinkControl`
2. the error stems from `getWithFullPermalink` - at present, only this method throws an error for the children of the error boundary, so we won't display this error boundary for an unrelated error
3. for other call sites of `getWithFullPermalink`, the precondition (at least on frontend) is that hte resource exists 
- link editor modal, where we click on an item 
- folder settings modal (for full permalink of folder) 
- create page (full permalink of parent) 
hence, i didn't add on those places
https://github.com/user-attachments/assets/d35f38b1-4e1b-4ad7-a82e-13351dbc3271 …
=> fix(bug): link editor throws an error when the referenced item has been deleted

apps/studio/src/features/editing-experience/components/Block/BaseBlock.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/TipTapEditor/components.tsx, apps/studio/src/stories/Page/EditPage/EditArticlePage.stories.tsx, apps/studio/src/stories/Page/EditPage/EditContentPage.stories.tsx, apps/studio/tests/msw/handlers/page.ts
1. right now we are using `break-all` in tiptap, which causes wordbreak to be annoying.
1. update to `break-word` - however, the preview text can now overflow (very long word, no space) so i had to add `overflow: auto` 
https://github.com/user-attachments/assets/5db726c1-987a-4f73-bba1-b8a5555b6a14
1. create a new page
2. add a new text block
3. go into the text block
4. type out a sentence with a long word (like: supercalifragilisticexplalidicious) at the end
5. the long word should not be randomly truncated in the middle but reflow to the next time
6. type out a huge chunk of words without space (eg: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest) 
7. click save
8. the preview text should be automatically hidden rather than overflowing
=> chore: break word and resolve overflow

apps/studio/src/components/ErrorBoundary/DefaultFallback.tsx, apps/studio/src/components/ErrorBoundary/DefaultTrpcError.tsx
See ticket
Closes ISOM-1716 (hopefully)
- removed the full screen spinner and instead, return null since we're redirected out to `/` 
- i tested this via setting the redirect in `/:page/settings`; previously, it showed teh spinner **even after** redirection but now, it displays only the expected content
- i think this happens because we wrap our app in a default error boundary, so this spinner displays **even after** redirection out to the new page
1. give yourself access to some site 
2. go to that site 
3. now, delete your access to the site
4. refresh teh page
5. you should get redirected out to `/`
6. there shuold not be a loading spinner
=> chore: fix infinite login spinner

apps/studio/src/server/modules/resource/resource.router.ts
folder items shouldn't be movable into collection
add another check to prevent folder items from being moved into a non folder
1. create a folder
2. create a page inside the folder
3. create a collection
4. try to move the page into the collection
5. this should fail
6. try to move the folder itself into the collection
7. this should fail
8. create another collection
9. repeat steps 1-7 but with the move destination as the new folder
10. they should all succeed
https://github.com/user-attachments/assets/f216528f-f055-4e95-ac19-bcd999134791
=> fix: prevent folder items from moving into collection

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20250218133951_add_user_last_login_at/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/src/components/ErrorBoundary/DefaultTrpcError.tsx, apps/studio/src/features/editing-experience/components/PublishButton.tsx, apps/studio/src/features/editing-experience/components/form-builder/components/LinkErrorBoundary.tsx, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/modules/auth/sgid/__tests__/sgid.service.test.ts, apps/studio/src/server/modules/auth/sgid/sgid.service.ts, apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/msw/handlers/me.ts
Track user login timestamps by adding a `lastLoginAt` field to the User model.
This change is essential for improving user authentication tracking and analytics.
**Features**:
- Added `lastLoginAt` field to the User model.
- Updated authentication logic to set `lastLoginAt` during user login.
The following tests have been added to confirm functionality:
- Tests for setting `lastLoginAt` to null when creating a new user.
- Tests for updating `lastLoginAt` when a user logs in.
1. Login into studio with a new email -> `lastLoginAt` should be current timestamp
2. Log out and login again -> `lastLoginAt` should be a new timestamp
=> isom-1740 backend user management service (tracking last login)

apps/studio/src/schemas/user.ts, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/permissions/permissions.type.ts, apps/studio/src/server/modules/user/__tests__/user.router.test.ts, apps/studio/src/server/modules/user/__tests__/user.service.test.ts, apps/studio/src/server/modules/user/user.router.ts, apps/studio/src/server/modules/user/user.service.ts, apps/studio/src/utils/__tests__/email.test.ts, apps/studio/tests/integration/helpers/iron-session.ts, apps/studio/tests/integration/helpers/seed/index.ts, apps/studio/tests/msw/constants.ts
Implement user management functionality with role-based access control and email domain restrictions.
**Features**:
- Restrict admin role to whitelisted gov.sg emails
- Implement user management router with CRUD operations
- Prevent recreating deleted users (due to incomplete audit trail at the moment)
- Prevent duplicate site-wide user permissions
- Add user management permissions service
- Improve createUser service with optional transaction support
- Extract mock test user name to constant
- Create setUpUserPermissions for more versatile user permission
- Comprehensive tests for isGovEmail utility function
- User management router tests
- User service tests
- Email validation tests
=> isom-1740 backend user management service (API endpoints)

packages/components/src/templates/next/components/internal/Footer/Footer.tsx
Footer had links for Contact Us and Feedback Form be in title case, so it was inconsistent with Isomer's preferred way of casing
[Slack discussion
](https://opengovproducts.slack.com/archives/C083KGWTX5X/p1739516960579799)
- Contact Us -> Contact
- Feedback Form -> Feedback
Note: "Report Vulnerability", "Terms of Use", and "Privacy Statement" represent programs (e.g., VDP) and/or legalese, so the casing has been left untouched.
=> [component] update footer copy

apps/studio/public/assets/css/preview-tw.css, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/Infobar/Infobar.stories.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.stories.tsx, packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx, packages/components/src/templates/next/components/internal/BlogCard/BlogCard.stories.tsx, packages/components/src/templates/next/components/internal/BlogCard/BlogCard.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.stories.tsx, packages/components/src/templates/next/components/internal/CollectionCard/CollectionCard.tsx, packages/components/src/templates/next/components/internal/CollectionCard/Title/ExternalLinkTitle.tsx, packages/components/src/templates/next/components/internal/CollectionCard/Title/InternalLinkTitle.tsx, packages/components/src/templates/next/components/internal/CollectionCard/Title/Title.tsx, packages/components/src/templates/next/components/internal/CollectionCard/Title/collectionCardLinkStyle.ts, packages/components/src/templates/next/components/internal/CollectionCard/Title/index.ts, packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.stories.tsx, packages/components/src/templates/next/components/internal/LinkButton/LinkButton.stories.tsx, packages/components/src/templates/next/components/internal/LinkButton/LinkButton.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
For buttons and collection/blog cards, external links 1) do not open in new tab and 2) show "new tab" icon at the end
Closes https://linear.app/ogp/issue/ISOM-1727/bug-external-link-all-should-have-new-tab-icon-open-in-new-tab
- Details ...
**Bug Fixes**:
- add a check in `LinkButton`
- add a check in the `CollectionCard` and `BlogCard` + add stories
1. go to a component with a button e.g. Hero. Add the link to an external link e.g. `https://google.com`.
2. go to a collection and create a collection link. Add the link to an external link e.g. `https://google.com`.
=> isom-1727 bug external link all should have new tab icon open in new

apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsMetaImageControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/constants.ts
RE: https://opengovproducts.slack.com/archives/C07CWUNUL68/p1740639058162289
Wrong copywriting for file upload
- Details ...
**Bug Fixes**:
- use the correct constants
1. go to a page -> create a text block -> click on "hyperlink" icon in tiptap -> click on "File" option -> It should show `Accepted file types: .pdf, .xls, .xlsx, .csv, .tsv`
2. go to a page -> click on "META SETTINGS" -> it should show `Accepted file types: .jpeg, .png, .gif, .svg, .tiff, .bmp, .webp`
=> fix: studio file/image upload acceptable file extension copywriting

apps/studio/src/components/PageEditor/FileAttachment.tsx
wrong file tyep description
- Details ...
**Bug Fixes**:
- use correct variables
**BEFORE**:
**AFTER**:
=> fix: Dynamically display accepted file types in FileAttachment

apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx
For some reason, we are now showing `(optional)` beside the form fields when creating new folders, but all the fields should be required.
**Bug Fixes**:
- Set the form fields in the create folder modal to all be required.
**BEFORE**:
**AFTER**:
1. Go to Studio and create a folder.
2. Verify that the create folder form has all the fields shown to be required (no optional text).
3. Verify that you are not able to create the folder if any of the fields are not filled in.
4. Verify that you can still proceed to create the folder with all the fields filled in.
=> fix: set required form fields for create folder modal

apps/studio/src/features/editing-experience/components/Block/BaseBlock.tsx, packages/components/src/templates/next/layouts/Article/Article.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx, packages/components/src/templates/next/layouts/Database/Database.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.tsx, packages/components/src/templates/next/layouts/IndexPage/IndexPage.tsx, packages/components/src/templates/next/layouts/Skeleton/Skeleton.tsx
When users have a very long URL, it causes a scrollbar to appear for the content.
**Bug Fixes**:
- Add break words to the component preview to remove the scrollbar.
- Also add break words to the Skeleton layout (which all layouts use) so the scrollbar doesn't appear.
**BEFORE**:
**AFTER**:
1. Copy and paste the JSON content [from this page](https://staging-studio.isomer.gov.sg/sites/1/pages/16893) into a new page.
2. Verify that there isn't a scrollbar in the component content preview on the left.
3. Verify that there isn't a scrollbar in the page preview itself on the right.
=> fix: break words for overflow preview and content

apps/studio/src/features/sign-in/components/EmailLogin/VerificationInput.tsx
So weird, suddenly our form fields are showing optional.
**Bug Fixes**:
- Make email verification OTP form field required.
**BEFORE**:
**AFTER**:
=> fix: remove optional for email OTP login

apps/studio/src/components/ResourceSelector/useResourceStack.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx
Closes https://linear.app/ogp/issue/ISOM-1760/internal-links-pr-follow-up-state-is-persisted-after-closing-modla
- Details ...
- remove console log lmao
**Bug Fixes**:
- cleanup state on dismount
**BEFORE**:
https://github.com/user-attachments/assets/fa674221-11b9-4cc3-8416-789bbff9af52
**AFTER**:
https://github.com/user-attachments/assets/645d146e-a78f-40ac-b6ad-a62a936ccba3
=> isom-1760: internal links PR- state persisted after closing

packages/components/src/interfaces/complex/Hero.ts, packages/components/src/templates/next/components/complex/Hero/Hero.stories.tsx, packages/components/src/templates/next/components/complex/Hero/Hero.tsx, tooling/template/data/config.json
The template can't support extremely vibrant colours like Yellow. Some default variants will fail contrast with a yellow. Unlike other colours, yellow loses its unique vibrance when you lower its lightness. 
- The Hero banner (block variant) should have a variant that support inverse.
- This variant uses a different mapping of colour tokens.
- This variant should NOT be exposed to the user on Studio. It is set by us only for sites that have a high luminosity theme colour. 
[More details on Notion
](https://www.notion.so/opengov/Mini-Inverse-hero-banner-variant-for-LiveOn-1af77dbba788803ba2a7dcf4ea782b25?pvs=4)
=> Inverse hero banner variant for sites with yellow as a colour theme

packages/components/src/utils/__tests__/validation.test.ts, packages/components/src/utils/validation.ts
We currently do not allow Google MyMaps and OneMap advanced minimap embeds.
**Features**:
- Expand the validation functions to allow Google MyMaps and OneMap advanced minimap embeds.
=> feat: allow Google MyMaps and OneMap advanced minimap

packages/components/src/templates/next/components/native/Table/Table.stories.tsx, packages/components/src/templates/next/components/native/Table/Table.tsx
Hyperlinks on a list nested inside a table had small touch targets because the list-spacing wasn't being applied.
This fails WCAG 2.5.8
Slack discussion: https://opengovproducts.slack.com/archives/C082M357BAA/p1741683515905209
The problem is not the line height of the list items itself, but more of the distance between each item in a list.
As a solution, adding mb-[15px] and mt-0.
=> [A11y] Increase touch target of list items nested in tables

apps/studio/src/features/users/components/CollaboratorsDescription.tsx
Missing/incorrect punctuation
- Details ...
**Bug Fixes**:
- fix fullstops
1. go to User Management feature and check that the text ends with `.`
=> fix: correct grammar in CollaboratorsDescription component text

apps/studio/prisma/generated/generatedEnums.ts, apps/studio/prisma/generated/generatedTypes.ts, apps/studio/prisma/migrations/20250318080632_add_audit_logs/migration.sql, apps/studio/prisma/schema.prisma, apps/studio/prisma/types.ts, apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/user/__tests__/user.router.test.ts
see related issue
1. add various service methods to log different events
- i didn't add `metadata` because i'm unsure what qualifies but feel free to extend the methods to add them yourself
=> feat(audit-logs): add initial service + methods to log various events

apps/studio/src/components/ResourceSelector/useResourceStack.tsx
Cannot link in modal due to state resetting on dependency changes
Closes https://linear.app/ogp/issue/ISOM-1794/bug-unable-to-create-links-to-nested-folders-and-pages
**Bug Fixes**:
- remove depdency in useEffect
https://github.com/user-attachments/assets/8d248cb2-6abf-461a-ba5c-857cb4d0414c
1. Go to Studio and create a Text component.
2. Type some random words and select some of them to add a link.
3. Attempt to add a link to a nested page/folder.
4. You should be able to do it successfully without the page list selector jumping back to the root.
=> isom-1794 bug unable to create links to nested folders and pages

apps/studio/prisma/migrations/20250319072442_prevent_audit_logs_update_and_delete/migration.sql, apps/studio/src/server/modules/audit/__tests__/audit.service.test.ts, apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/tests/integration/helpers/seed/index.ts
Closes ISOM-1768.
**Features**:
- Add new database migration to prevent UPDATE and DELETE actions on the AuditLog table.
- Make any changes that creates an AuditLog table.
- Use TablePlus to try and update any contents of any AuditLog row.
- Verify that you are blocked from performing the update.
- Attempt to delete any AuditLog row.
- Verify that you are blocked from performing the delete.
=> feat: add trigger to block UPDATE and DELETE of audit logs

apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts
Closes ISOM-1779.
Closes ISOM-1784.
**Features**:
- Added audit logging capabilities to the site router.
- Removed unused `setSiteConfig` function inside site.service.ts.
- Added test that was previously skipped, to test for 403 when the user has no access to the site in calling `getSiteName`.
=> feat: add audit logging to site router with tests

apps/studio/prisma/generated/generatedTypes.ts, apps/studio/public/assets/css/preview-tw.css, apps/studio/src/server/context.ts, apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/auth/__tests__/auth.router.test.ts, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/__tests__/email.service.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/modules/auth/email/email.service.ts, apps/studio/src/server/modules/me/me.router.ts, apps/studio/src/server/modules/me/me.select.ts, apps/studio/src/server/trpc.ts, apps/studio/tests/integration/helpers/seed/index.ts
Closes ISOM-1773.
Closes ISOM-1790.
**Features**:
- Added audit logging capabilities to the email router.
- Changed the DB queries on me.router.ts to use via Kysely instead of Prisma directly.
=> feat: add audit logging to email router with tests

apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/folder/__tests__/folder.router.test.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/folder/folder.select.ts
Closes ISOM-1777.
Closes ISOM-1786.
**Features**:
- Added audit logging capabilities to the folder router.
=> feat: add audit logging to folder router with tests

apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/collection/__tests__/collection.router.test.ts, apps/studio/src/server/modules/collection/__tests__/utils.ts, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/collection/collection.select.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/tests/integration/helpers/seed/index.ts
See the attached issue for the problem 
- add audit logging to folder router 
- constrain `collectionRouter.updateCollectionLink` to only update collection links
- fix incorrect handling for `updateBlobById` when the resource is published
- we create a `draftBlob` correctly but we don't use the `draftBlobId` of the newly created blob but isntead, the stale value of `page.draftBlobId` (which is `null`)
- previously, we returned a `UpdateResult`, which led to a silent failure. this has been updated to `returningAll` because we should always expect >= 1 result
- removed duplicate (and incorrect) updates of `updateCollectionLink`
=> feat(audit-logging): add audit logging to collection router + tests 

apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts
see attached issue
Closes https://linear.app/ogp/issue/ISOM-1783/[misc]-add-integration-tests-for-resourcerouter
- use the provided service method to log in `resourceRouter`
- instead of using the custom kysely statement which we were doing previously, we go through `getFullPage` to get the full resource to store in our audit logs
=> feat: add audit logging to resource router

apps/studio/prisma/types.ts, apps/studio/src/server/modules/audit/audit.service.ts, apps/studio/src/server/modules/collection/__tests__/collection.router.test.ts, apps/studio/src/server/modules/collection/collection.router.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/page/page.router.ts, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/server/modules/site/site.service.ts, apps/studio/src/server/modules/version/version.service.ts
see attached issue
1. log the delta of version for page publishes because this is the only write to db. we capture the resource at 2 points, first when it is being edited and secondly, when it is being published. when it is being edited, we capture the full delta (before/after) but at the point of pubilsh, we capture the resource **as-is**
=> feat(audit-logs): log publish events

.github/workflows/deploy_production.yml, .github/workflows/deploy_uat.yml
we shuold deploy to `uat` on every release so that the environment stays up to date with `production` and `uat` users can enjoy latest featureset
copy deployment workflow for `uat` over to production deploy workflow.
concretely, this means we will deploy to `uat` on every release and testing of new features (via pushing to `uat`) will have to be off `main` or it will reset the state of the environment
=> chore: deploy to `uat` on every release

.aws/deploy/task-definition.json
It is a recommended security practice to make the container root filesystem readonly.
Fulfils cs-6 of SSP requirements.
**Features**:
- Set `readonlyRootFilesystem` to be true for all containers that Isomer Studio uses.
=> feat: make container root filesystem readonly

.github/workflows/deploy_production.yml, .github/workflows/deploy_uat.yml
currently we put `deploy_uat` job in `deploy_production` workflow. this:
1. can be confusing (naming-wise)
2. duplicated code and no single source of truth
- move it to use `on -> release` (similar to prod) instead
=> refactor: move `deploy_uat` job into correct workflow

packages/components/src/hooks/useQueryParams.ts, packages/components/src/interfaces/internal/CollectionCard.ts, packages/components/src/templates/next/components/internal/PaginationControls/PaginationControls.tsx, packages/components/src/templates/next/layouts/Collection/Collection.tsx, packages/components/src/templates/next/layouts/Collection/CollectionResults.tsx, packages/components/src/templates/next/layouts/Collection/useCollection.ts, packages/components/src/templates/next/layouts/Collection/utils/getCategoryFilter.ts, packages/components/src/templates/next/layouts/Collection/utils/getCollectionItems.ts, packages/components/src/templates/next/layouts/Collection/utils/getTagFilters.ts, packages/components/src/templates/next/types/Pagination.ts
Agencies have been asking for enhancements about the collection filters:
- Having a permanent URL to share a particular set of active filters with other people
- Clicking on an article, then pressing back should retain the active filters
- Ordering of filters is not intuitive when it comes to numbers
**Features**:
- Revamped the way the collection filters are calculated and stored by using the query params as the source of truth, then deriving the other states from it.
- Enhanced the ordering of filters to take into account numbers (1 -> 2 -> 3 -> 22 rather than 1 -> 2 -> 22 -> 3).
**Bug fixes**:
- Fixed issue with phantom collection cards appearing when applying collection filters.
- Live demo is available on the NNA staging site: …
=> feat: add query params to collection filters

packages/components/src/interfaces/internal/Wizgov.ts, packages/components/src/templates/next/components/internal/Wizgov/WizgovWidget.tsx
Closes https://opengovproducts.slack.com/archives/C07CWUNUL68/p1743496259124609
- Details ...
- add support for `data-topic` for wizgov
1. add a `data-topic` into the wizgov config and it should filter the topics
=> wizgov widget add data topic props

packages/components/src/engine/metadata.ts
Search page got noindex but got feedback that we should put inside robots.txt instead.
- Add `/search` to disallow in robots.txt
=> chore: disable crawling of search page

apps/studio/src/server/modules/auth/session.ts
Closes https://linear.app/ogp/issue/ISOM-1811/[misc]-reduce-session-duration-from-7-days-to-12-hours
- Details ...
- update iron session duration to 12 hours
=> singpass: reduce iron session TTL from 7 days to 12 hours

.github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml, .github/workflows/deploy_uat.yml, .github/workflows/update_release_branch.yml
All CIs are using the same concurrency group, even though they are doing different things.
**Bug Fixes**:
- Make the concurrency groups more specific using the name of the workflow file as prefix
=> chore: make concurrency group more specific

packages/components/src/templates/next/layouts/Collection/useCollection.ts
The clear all filters button calls `updateQueryParams` twice, which results in a race condition.
**Bug Fixes**:
- Directly set the query params when clearing all filters.
=> fix: update all query params in one call

apps/studio/.storybook/preview.tsx, apps/studio/src/features/editing-experience/components/PreviewWithoutSitemap.tsx, apps/studio/src/features/editing-experience/components/form-builder/hooks/useImage.ts, apps/studio/src/features/editing-experience/components/form-builder/hooks/useS3Image.ts, apps/studio/src/stories/Page/EditPage/EditPageSettings.stories.tsx, apps/studio/src/utils/generateAssetUrl.ts, packages/components/src/templates/next/components/complex/Hero/Hero.stories.tsx, packages/components/src/templates/next/components/complex/Image/Image.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.stories.tsx, packages/components/src/templates/next/components/complex/Infobar/Infobar.stories.tsx, packages/components/src/templates/next/components/complex/Infopic/Infopic.stories.tsx, packages/components/src/templates/next/components/complex/KeyStatistics/KeyStatistics.stories.tsx, packages/components/src/templates/next/components/internal/ContentPageHeader/ContentPageHeader.stories.tsx, packages/components/src/templates/next/components/internal/Footer/Footer.stories.tsx, packages/components/src/templates/next/components/internal/Navbar/Navbar.stories.tsx
Storybook starts failing after https://github.com/opengovsg/isomer/pull/1199 e.g. https://www.chromatic.com/build?appId=66543928751c844d159a31ef&number=3059&captureStack=capture-v7
suspect its due to the infrastracture upgrade from chromatic since issue started after that
**Bug Fixes**:
- switch the order of env and manual overiding to not have it be overwritten e.g. https://www.chromatic.com/test?appId=66543928751c844d159a31ef&id=67ffce99c6d2e77ecc58d6d7
- create `generateAssetBaseUrl` so that we can set storybook's `NEXT_PUBLIC_S3_ASSETS_DOMAIN_NAME` as empty string for storybook so that it can fallback to use its static asset handling
- remove the need to reference `assetsBaseUrl` since we already set up static assets in storybook in …
=> fix: storybook rendering changes (out of nowhere 😔)

apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/server/modules/auth/singpass/__tests__/singpass.router.test.ts, apps/studio/src/server/modules/auth/singpass/singpass.router.ts
We need to add error logging and monitoring for the new 2FA flows, so we know and can respond to issues that users might face.
- Add logging with context to the authentication flows, so that they can be monitored via alarms on Datadog.
- Also add unit tests for the added/updated flows.
=> chore: add error logging for Singpass auth

packages/components/src/templates/next/layouts/Collection/utils/getCollectionItems.ts
Empty date strings are being treated as an article with a date.
**Bug Fixes**:
- Make empty date strings be treated as dateless variant of an article.
=> fix: treat empty date string as dateless variant

apps/studio/src/components/AppNavbar.tsx, apps/studio/src/features/dashboard/components/AdminCreateIndexPageButton.tsx, apps/studio/src/features/editing-experience/components/LinkEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/hooks/useIsUserIsomerAdmin.ts, apps/studio/src/lib/growthbook.ts, apps/studio/src/pages/godmode/create-site.tsx, apps/studio/src/pages/godmode/index.tsx, apps/studio/src/pages/godmode/publishing.tsx, apps/studio/src/pages/sites/[siteId]/admin.tsx, apps/studio/src/server/modules/permissions/permissions.service.ts, apps/studio/src/server/modules/site/site.router.ts, apps/studio/src/templates/layouts/AdminCmsSidebarLayout.tsx, apps/studio/src/templates/layouts/AdminSidebarOnlyLayout.tsx
Some features should only be limited to core team e.g. god mode
previously: https://github.com/opengovsg/isomer/pull/1251
- Details ...
**Features**:
- Details ...
- split `users` into `core` and `migrators` in growthbook
- TODO: clean-up and remove `users` key-value from `isomer_admins` after this is launched
=> Add growthbook for isomer core 

packages/components/src/interfaces/complex/InfoCards.ts, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.stories.tsx, packages/components/src/templates/next/components/complex/InfoCards/InfoCards.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/templates/next/layouts/Homepage/Homepage.stories.tsx
Infocards were using variant aspect ratios, so it was difficult for site editors to prepare images that display nicely across all breakpoints.
Closes [ISOM-1831]
Applied fixed aspect ratios based on document shared with team in Feb:
Thank you Zhong Jun for helping with this PR!
=> [component] enhance infocards to use fixed aspect ratio across all breakpoints

apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx
Closes ISOM-1894.
**Bug Fixes**:
- Reset the editor drawer state before mutating the page state.
=> fix: reset the editor drawer state first before mutation

.github/dependabot.yml
Dependabot is opening too many PRs and we don't have the bandwidth to look into them.
- Reduce the limit on the number of PRs open by dependabot from 10 to 5.
=> chore: reduce dependabot PR limit

apps/studio/src/features/me/api/useMe.ts, apps/studio/src/features/sign-in/components/EmailLogin/EmailLoginForm.tsx, apps/studio/src/features/sign-in/components/SignInContext.tsx, apps/studio/src/server/modules/auth/email/email.router.ts, apps/studio/src/types/growthbook.ts
Closes ISOM-1883.
**Features**:
- Added email attribute to Growthbook to allow for selective enabling of Singpass using the email address.
=> feat: allow enabling of Singpass for selected users

packages/components/src/interfaces/complex/InfoCards.ts
Closes ISOM-1900.
- Increased the limit on the number of InfoCards from 12 to 30.
=> chore: increase InfoCards limit from 12 to 30

apps/studio/public/assets/css/preview-tw.css, apps/studio/src/components/Disable.tsx, apps/studio/src/features/editing-experience/components/ConfirmConvertIndexPageModal/ConfirmConvertIndexPageModal.tsx, apps/studio/src/features/editing-experience/components/ConfirmConvertIndexPageModal/index.ts, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/stories/Page/EditPage/EditIndexPage.stories.tsx, apps/studio/tests/msw/handlers/page.ts
Closes ISOM-1897.
**Features**:
- Add a new toggle for converting custom index pages into the new index page.
=> feat: add toggle to switch to new index page

apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/utils/sitemap.ts
[see slack thread](https://opengovproducts.slack.com/archives/C06R4DX966P/p1746684298741139)
1. first, we pre-generate the list of full URLs 
2. we then generate the list of resources **that are actually going to be in our sitemap** - the source of truth for this shuold be based off publishing. 
3. based off `publishing/index`, we will only create index pages for **folders that have some children** (regardless of nesting depth).
1. because we only take `immediateChildren` + `childCousinIndexPages`, this isn't quite enough to get the full list of pages under a folder. this means that for folders with `draft` index pagse (or no index pages) but deeply nested children, there will be a difference in preview
=> chore: add check for immediate children

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
Previously, the code had an inner conditional for `!isPreviewingIndexPage` - this led to issues because the inner conditional evaluated to `true` (see below code) 
```ts
(savedPageState.content.length === 0 &&
pageLayout !==
ISOMER_USABLE_PAGE_LAYOUTS.Index) ||
// default value for this is `false` -> this becomes `true` here 
!isPreviewingIndexPage)
```
Shift the `!isPreviewingIndexPage` conditional out - we should always check that the index page is not being shown on the outermost layer because it has the highest priority
**Before**
**After**
https://github.com/user-attachments/assets/f8dee592-aad7-4b8a-882e-2b9bedd63579
=> fix: fix erroneous conditional for homepage

package-lock.json, packages/components/.storybook/preview.tsx, packages/components/package.json
tired of approving date-related changes for storybook
- mock it using `mockdate` and a mockdate decorator for Component storybook
=> storybook mockdate for Component

apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx
At present, deleting any block above a `Text` block causes a crash. This is because (**note**: i'm guessing here as i'm not 100% confident) the blocks re-rendered and the new state is immediately fed to `JSONForms` via `FormBuilder` prior to the update loop being complete.
Shift the update for block state **below** the state update for drawer, so that `FormBuilder` doesn't see the new state whilst its internal state hasn't been updated.
https://github.com/user-attachments/assets/8c59bdf0-3c1f-4c08-bdbc-7390ffbd16f4
=> fix: set page state only after return to root

apps/studio/src/features/editing-experience/components/Block/DraggableBlock.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/EditPageDrawer.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, packages/components/src/interfaces/complex/Infobar.ts, packages/components/src/interfaces/complex/index.ts, packages/components/src/schemas/components.ts
A follow-up to https://github.com/opengovsg/isomer/pull/1293 based on what was discussed
- Details ...
- make `variant` be dynamic for layouts based on whats generated
- pass in that props from studio
=> isom-1904 support infobar styling dark selective display 2

apps/studio/src/server/modules/resource/resource.service.ts, apps/studio/src/utils/sitemap.ts
- we fetch the `RootPage` as part of the `immediateSibilngs` because on root page, the `parentId` is also `null`. this leads to alot of sub children if the tree is wide. later on, this blows the stack due to excessive processing in `getSitemapTreeFromArray` 
we never need teh `RootPage`, so it's removed from filter + we update the name to maek it clearer
=> chore: remove extra rootpage resource fetched from db

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
- our infobox isn't full width on bigger screens for the toggle 
- add full width for infobox
**old**
**new**
=> chore: fix styling on infobox

packages/components/src/interfaces/complex/Blockquote.ts
Users cannot create block quotes without image as alt text is required
- Details ...
**Bug Fixes**:
- make image alt text optional
> [!NOTE]
> this is not ideal as users will be able to create an image without an alt text, but this is a workabout 
- try to create a block quote component with NO image. you should be able to do so
=> fix: make blockquote image alt optional

packages/components/src/templates/next/layouts/Collection/utils/getTagFilters.ts
Potential fix for [https://github.com/opengovsg/isomer/security/code-scanning/9](https://github.com/opengovsg/isomer/security/code-scanning/9)
To fix the issue, we need to prevent prototype pollution by ensuring that untrusted input cannot be used to modify `Object.prototype`. The best approach here is to replace the plain object `tagCategories` with a `Map`, which does not inherit from `Object.prototype` and is immune to prototype pollution. Alternatively, we could validate the `category` key to reject unsafe values like `__proto__`, but using a `Map` is a more robust and future-proof solution.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 9: Prototype-polluting assignment

apps/studio/tests/e2e/singpass.test.ts
the E2E test for singpass seems quite flakey - wondering if we should temp. disable it until its fixed?
- it is flakey test doesn't give us clear indication of whether something is really working
- its a blocker for the "Required" step in CI which means we have to keep retrying the failed tests in order to deploy.
- Might be an issue during VAPT if we have fixes for vulnerabilities but cannot merge and deploy
=> test(e2e): skip initial login tests with Singpass

apps/studio/src/pages/godmode/publishing.tsx, apps/studio/src/server/modules/site/site.router.ts
app crashes due to spike in connection pool opening and exceeding Prisma's default connection pool of 10
- Details ...
- do a loop instead of Promise.all
- process these in the background insstead of holding onto the thread -> also give more immediate feedback to the user
=> Fix godmode publishall

.aws/deploy/task-definition.json
1. we should not use secrets in github actions.
Closes ISOM-1855 
1. remove the key from our ci (still need to remove from GHA)
2. add the key in an associated PR in infra
1. [Run](https://github.com/opengovsg/isomer-next-infra/pull/144) the `pulumi up` to add the api key to our `production` + `uat` + `vapt` environment (already done for `staging`)
2. release this PR to `production`
3. force push to `vapt` (for `uat`, we have a workflow that'll deploy post release)=
=> fix: get datadog api key from ssm secretes

package.json
don't want to have ot manually run `watch` every time a thing change on components
add `npm run watch:packages` command that watches our `build` whenever there are code changes so that it'll reflect on studio automatically
=> chore: add watch command

apps/studio/src/features/editing-experience/atoms.ts, apps/studio/src/features/editing-experience/components/EditLinkPreview.tsx, apps/studio/src/schemas/collection.ts, apps/studio/src/server/modules/collection/collection.router.ts, packages/components/src/types/page.ts
see ticket
1. add the `item` to the `LinkProps` in components
2. on studio, add this to the atom and to the backend where we send it to save. we also update the data being sent to teh preview iwth the image.
https://github.com/user-attachments/assets/5163b902-8fc5-4056-a974-68aa1b822f63
- this PR isn't quite ideal because this change requires alot of manual work, whereas our ideal state is that we're hooked into json forms and the update is automatic (+ now our validation is out of sync on our backend). i can't quite remember why i needed to use the `atom`, but i'll try using the same `ajv` validator and see how it goes
=> feat(collection-links): alllow users to add thumbnails to items

packages/components/src/templates/next/components/complex/Hero/HeroFloating.tsx, packages/components/src/templates/next/components/complex/Infopic/components/FullInfopic.tsx
Some minor UI bugs on bold components:
- The infocards full variant's background image was aligned to the top. Have to set to `background-position: center` explicitly.
- The floating hero banner's image wasn't set to `image-fit: cover`, so some images were getting squished. Migrators reported. 
Closes [ISOM-1953]
(look closely where the rhino's legs are!!)
Before:
After:
Before:
After:
=> Fix UI janks in bold components

.github/workflows/aws_deploy.yml
right now, our docker images are uniquely identified by the github sha. most of the itme, this is ok. however, when we want to rollback a commit, what happens is that we will attach a tag to the old version. this results in deploys failing as our tags are immutable on production
- add `github.ref` to be part fo the image tag. when this is from a push, this will be a branch name. however, on release, this will be the `release_tag`; this means we can have 2 release tags that are differently only ihn the release version but having the same commit hash
=> fix(deploy): add github ref to image tag 

apps/studio/package.json, apps/studio/src/server/modules/folder/__tests__/folder.router.test.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/turbo.json, packages/components/package.json, packages/components/src/templates/next/components/complex/ChildrenPages/ChildrenPages.tsx, packages/components/src/templates/next/components/complex/ChildrenPages/__tests__/utils.test.ts, packages/components/src/templates/next/components/complex/ChildrenPages/types.ts, packages/components/src/templates/next/components/complex/ChildrenPages/utils.ts, packages/components/turbo.json
This PR adds tests as a follow up to the previous PR - mainly for sort + list behaviour
1. reorg some files in `ChildrenPages` for testing
2. add tests 
3. add `test:watch` command to `turbo` so we can watch test executions
=> chore(tests): add tests for `listChildrenPage`

packages/components/src/templates/next/components/complex/InfoCols/InfoCols.stories.tsx, packages/components/src/templates/next/components/complex/InfoCols/InfoCols.tsx
When an infocol has a CTA that spans across more than 1 line, the arrow is aligned differently or becomes very tiny.
This is because the CTA and arrow were aligned using a `flex`, instead of the arrow being `inline` with the CTA.
Closes [ISOM-1952]
Use inline. 
Looks like this now:
=> Infocols has tiny/misaligned arrows when text is very long

tooling/build/scripts/publishing/index.ts
**NOTE: THIS PR IS PENDING A TEST ON STAGING**
we want the siderail to be sorted via the index page's sorting order also 
1. sort the index page at the publishing level 
2. we take the index page order preferentially then fallback to folder meta if found. 
3. not removing the existing sort order on `ChildrenPages` -> this sort in publishing is kidna magical and i'd prefer to keep the extra sort in components just for guarantees
=> feat: take sort order from index pages

.github/workflows/aws_deploy.yml, .github/workflows/ci.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_staging.yml, .github/workflows/deploy_uat.yml, .github/workflows/deploy_vapt.yml
- still have 2 usages of our own `DD_API_KEY` for GHA to configure test visibility; this has been replaced with our org wide secret
- use org wide secret
- reusable workflow for `aws_deploy` passes in `DD_API_KEY_GITHUB_ACTIONS` as the `secrets.DD_API_KEY`
will proceed to delete our own secret after this has been merged
=> chore: update to use the org wide secret

apps/studio/src/server/modules/folder/__tests__/folder.router.test.ts, apps/studio/src/server/modules/folder/folder.router.ts, apps/studio/src/server/modules/resource/__tests__/resource.service.test.ts, apps/studio/src/utils/sitemap.ts
Closes https://opengovproducts.slack.com/archives/C0924LBA0PR
**Bug Fixes**:
- revert changes on how `id` is generated for collection that has index pages
1. Go to studio and create a collection with an index page
2. Go to root page and add a valid collectionblock to the homepage (linking to the collection ID as reference) - page should render
=> Fix collectionblock preview

packages/components/src/templates/next/components/internal/GoogleTagManager/GoogleTagManagerHeader.tsx
Why `dangerouslySetInnerHTML` performs worse
- even if it eventually injects GTM asynchronously (j.async = true), the execution of that whole IIFE **runs immediately**, during the main thread’s execution window.
- That adds script evaluation time to your page load, which: 1) Shows up in "Long Tasks" in Chrome performance profiler, and 2) Contributes to TBT and INP in Lighthouse
- using `src` and `afterinteractive` instead of inline
improved performance and UX
- delaying the loading of GTM to reduce render-blocking resources
- ensures that critical content is available to users without delay. 
_note, this is our tradeoff_
- Delayed tag firing: Tags that rely on GTM may fire later than expected, potentially missing early user interactions e.g. **missing tracking of users who bounced too …
=> Improve lighthouse TBT (update GTM to use "src" instead of inline)

tooling/build/scripts/publisher.sh
The uploading and downloading progress to and from S3 generates a lot of output which is not helpful for debugging. Additionally, these outputs are being ingested into CloudWatch, which charges $0.70 per GB ingested, making it the largest cost component of Isomer.
- Set `--only-show-errors` for all `aws s3` commands, so that the upload/download progress outputs can be suppressed.
=> chore: suppress S3 upload/download progress output

.github/workflows/aws_deploy.yml
see corresponding ticket 
1. add aws inpsector on infra side (corresponding `pulumi up` has been performed on `staging`)
2. scan the buiilt docker image iwth `aws inspector` then check if it's over thereshold (we have 2 critical vulnerability - 1 in nextjs, 1 in golang but no known exploits...)
3. fail the deploy if over threshold + upload assets
=> feat(aws): scan images with inspector and fail deploy if threshold exceeded

apps/studio/src/lib/growthbook.ts, apps/studio/src/server/modules/auth/email/__tests__/email.router.test.ts, apps/studio/tests/integration/helpers/growthbook/mockFeatureFlags.ts
- singpass currently defaults to false despite it being rolled out
- tests will fail if growthbook not being mocked correctly 
- Details ...
- set default growthbook value for singpass as true
- add feature flags mocking
- split test for `verifyOtp` for email router to handle both scenarios of singpass enabled/disabled
=> chore: Singpass - set default to true + mock feature flags

apps/studio/package.json, apps/studio/src/server/modules/asset/__tests__/asset.service.test.ts, apps/studio/src/server/modules/asset/asset.service.ts, package-lock.json
see attached issue (sensitive as security and this is open repo)
1. use `filenamify` to strip special characters
2. write tests (thx claude) to ensure that unicode/other languages are preserved
=> fix(filenames): sanitise filenames so that special characters are stripped 

apps/studio/src/components/PageEditor/constants.ts
> [!NOTE]
> this entire PR and description is created by Cursor's background agent, to test its capabilities to improve engineering output
The image gallery component was not selectable in the Page Editor UI for article pages, limiting content creation options.
Closes https://linear.app/ogp/issue/ISOM-1949/image-gallery-enable-for-article
The `IMAGE_GALLERY_TYPE` has been added to the `ARTICLE_ALLOWED_BLOCKS` configuration in `apps/studio/src/components/PageEditor/constants.ts`. This makes the image gallery block available under a new "Add a new section" category for article pages.
**Features**:
- Enabled the Image Gallery component for Article Pages in the Page Editor.
- Enhanced content creation flexibility for article pages.
**Bug Fixes**:
- …
=> (cursor) isom-1949 - Enable image gallery for article pages

apps/studio/src/schemas/auth/singpass.ts, apps/studio/src/server/modules/auth/singpass/__tests__/singpass.router.test.ts, apps/studio/src/server/modules/auth/singpass/singpass.constants.ts, apps/studio/src/server/modules/auth/singpass/singpass.router.ts, apps/studio/src/server/modules/auth/singpass/singpass.service.ts
See https://opengovproducts.slack.com/archives/C0949RH4NTA/p1751898618082599 for more details.
**Bug Fixes**:
- A randomised `state` is used alongside `nonce` for better protection.
=> fix: use a random state with Singpass OIDC

apps/studio/src/features/dashboard/components/FolderSettingsModal/FolderSettingsModal.tsx, apps/studio/src/features/editing-experience/components/Block/BaseBlock.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionModal/CreateCollectionModal.tsx, apps/studio/src/features/editing-experience/components/CreateCollectionPageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/CreateFolderModal/CreateFolderModal.tsx, apps/studio/src/features/editing-experience/components/CreatePageModal/DetailsScreen.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextAreaControl.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsTextControl.tsx, packages/components/src/templates/next/components/complex/ChildrenPages/__tests__/utils.test.ts, packages/components/src/templates/next/components/complex/ChildrenPages/types.ts, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardContainer.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardImage.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardNoImage.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardText.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardWithFullImage.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/InfoCardWithImage.tsx, packages/components/src/templates/next/components/complex/InfoCards/components/types.ts
For some reason the spacing between the form field helper text and the input boxes have narrowed.
**Bug Fixes**:
- Restore the spacing between the helper text and the input fields to be 0.5rem.
- We have also not ran lint and formatting fixes for some time, so ran it to clean up the codebase.
**BEFORE**:
**AFTER**:
=> fix: adjust spacing for form fields helper text

apps/studio/package.json, apps/studio/src/constants/misc.ts, apps/studio/src/features/mail/service.ts, apps/studio/src/features/mail/templates/__tests__/templates.test.ts, apps/studio/src/features/mail/templates/templates.ts, apps/studio/src/features/mail/templates/types.ts, apps/studio/src/server/modules/database/constants.ts, apps/studio/src/server/modules/user/__tests__/inactiveUsers.service.test.ts, apps/studio/src/server/modules/user/__tests__/user.router.test.ts, apps/studio/src/server/modules/user/__tests__/utils.ts, apps/studio/src/server/modules/user/constants.ts, apps/studio/src/server/modules/user/inactiveUsers.service.ts, apps/studio/tests/integration/helpers/seed/index.ts, package-lock.json
Partially closes https://linear.app/ogp/issue/ISOM-1867/ac-3-create-script-to-automatically-prune-users-not-logged-in-90-days
> [!NOTE]
> this PR does not include the scheduler aspect of it - will do that in another branch and PR 
- Details ...
**Features**:
- add service to remove inactive users from sites
- add email template for sending to them when deactivating
=> isom-1867 prune inactive users (service + email)

.github/workflows/aws_deploy.yml
Blocking release while many of the findings raised are relating to esbuild toolchain
- Details ...
- increase from 10 to 12 in aws_deploy workflow
=> increase inspector high threshold from 10 to 12

apps/studio/src/server/modules/site/__tests__/site.router.test.ts, apps/studio/src/server/modules/site/site.router.ts
Currently this endpoint is restricted to any admins with admin access to isomer, but in fact, we should play it more safe by only allowing isomer admins and migrators to access it
- Details ...
- switch ACL validation from using site perms to growthbook list
=> Limit setSiteConfigByAdmin endpoint to isomer migrators and admins

packages/components/src/templates/next/components/internal/CollectionCard/Title/collectionCardLinkStyle.ts
* When navigating using keyboard, the blogCards and collectionCards titles don't get a proper focus-visible state. This is a violation of WCAG 2.4.7 
Closes [ISOM-2033]
* Use groupFocusVisibleHighlight() instead
=> Blogs/Collection links don't get a proper focus highlight

apps/studio/src/schemas/__tests__/asset.test.ts, apps/studio/src/schemas/asset.ts
Currently someone can actually maliciously upload a unsafe file via the `getPresignedPutUrl` API directly.
We only restrict it via the frontend at the moment and not the API
- Details ...
- add it to schema to validate the file extension to be one that's in our allowed list
- write test
1. try to call the API directly (via Insonmia, maybe) with a filename that contains `.html` or `.js` -> it should be rejected
=> security: only allow filename of extension from the allowlist to be uploaded

apps/studio/src/server/cron/index.ts, apps/studio/src/server/modules/user/inactiveUsers.service.ts
We do not want to remove users for all envs, only production.
**Bug Fixes**:
- Schedule the remove inactive users cron job only for the production env.
=> fix: remove inactive users only for production

packages/components/src/interfaces/internal/Vica.ts
The Vica chatbot widget schema was using boolean types for configuration options, but React omits boolean props when spreading onto DOM elements, causing them to not appear as attributes in the rendered HTML. This prevents the Vica script from receiving the intended boolean configuration values.
Changed the Vica schema to use string literal types (`"true"` and `"false"`) instead of boolean types for all boolean configuration options. This ensures that the boolean values are properly passed as string attributes to the Vica script.
- The Vica configuration props that were previously boolean types are now string literal types (`"true"` | `"false"`)
- **note: have checked and fixed so no longer breaking change**
- Fixed Vica chatbot configuration to …
=> refactor: update VicaSchema to use string literals for boolean options

apps/studio/next.config.mjs, apps/studio/src/features/editing-experience/components/utils.ts, packages/components/src/interfaces/complex/Map.ts, packages/components/src/templates/next/components/complex/Map/Map.stories.tsx, packages/components/src/templates/next/components/complex/Map/Map.tsx, packages/components/src/templates/next/components/internal/BaseParagraph/BaseParagraph.tsx, packages/components/src/templates/next/layouts/Content/Content.stories.tsx, packages/components/src/utils/__tests__/validation.test.ts, packages/components/src/utils/validation.ts
OGP Maps is not supported on Isomer Next.
**Features**:
- Add support for OGP Maps.
- CSP whitelist is on infra repo: https://github.com/opengovsg/isomer-next-infra/pull/191
```
<iframe src="https://maps.gov.sg/scdf-aed" width="100%" height="600" frameborder="0"></iframe>
```
=> feat: allow OGP Maps to be embedded in Isomer Next

apps/studio/src/components/PageEditor/FileAttachment.tsx, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsObjectControl.tsx
- right now, when a user adds image/alt text and then deletes both of them (ie, both image/alt are empty), we still show an error and prevent them from saving
- this is because the object containing both properties (`image` and `alt`) still exists as an empty object but our schema specifies that the object has to be either `undefined | { image, alt }` 
- update props to our object control
- `handleChange` so that when `isEmpty(object)`, we set `object` itself to `undefined` 
https://github.com/user-attachments/assets/d8214ecf-809a-47ae-823c-2365af1c6018
(basically is opposite of XOR for imgae/alt)
=> chore: fix image showing errors when empty

apps/studio/public/assets/css/preview-tw.css, package-lock.json
The package-lock.json file is outdated and Dependabot is not running.
- Update package-lock.json by running `npm run build`.
=> chore: update outdated package lock

apps/studio/src/contexts/EditorDrawerContext.tsx, apps/studio/src/features/editing-experience/components/ComplexEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/HeroEditorDrawer.tsx, apps/studio/src/features/editing-experience/components/MetadataEditorStateDrawer.tsx, apps/studio/src/features/editing-experience/components/MoveResourceModal/MoveResourceModal.tsx, apps/studio/src/features/editing-experience/components/RawJsonEditorModeStateDrawer.tsx, apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx, apps/studio/src/features/editing-experience/components/TipTapProseComponent.tsx, apps/studio/src/features/users/components/UserTable/UserTableMenu.tsx
Fixed incorrect toast status, e.g. should not be green and success
- Details ...
**Bug Fixes**:
- add missing `status`
- add explicit `status` for all instances even if its `success` 
actually not very easy to simulate this since need to send to a non-whitelisted email, can just assume its fixed
=> fix: add correct statuses to toast notifications

apps/studio/.env.test, package.json, turbo.json
The turbo cache is active for the `db:connect` command which is incorrect.
- Disabled turbo cache for the db:connect commands
- Fix the `build-storybook` turbo command
=> chore: disable turbo cache for db:connect

apps/studio/src/components/ResourceSelector/ResourceSelector.tsx, apps/studio/src/components/Searchbar/SearchModal.tsx, apps/studio/src/constants/resources.ts, apps/studio/src/server/modules/resource/__tests__/resource.router.test.ts, apps/studio/src/server/modules/resource/resource.router.ts, apps/studio/src/utils/resources.ts
Extension of #1549.
**Bug Fixes**:
- Prevent CollectionLink from appearing in the search result when adding links to internal resources.
=> fix: remove CollectionLink from search results

apps/studio/src/features/editing-experience/components/RootStateDrawer.tsx
- our current check for disabling creating blocks on index pages uses the `page.layout` property
- unfortunately, this is **only** for `page.layout == index`, which doesn't hold true for collection index pages (`layout == collection`, which leads to users being able to add block but these blocks don't do anything (collection layout just renders the filters)
- update the condition to prevent adding blocks whne layout is `collection`
=> fix: disable creating blocks on collection index pages

packages/components/src/templates/next/components/internal/ScrollToTop.tsx
Currently when user click on an anchor link, it ignores it and auto scrolls to the top, making it jank
reason due to a fix previously to force position to reset, due to next/link issue (as stated in the component)
- Details ...
**Bug Fixes**:
- only scroll to the top if URL does not have any hash
1. create a page with multiple sections, and publish
2. once build finish, go to that page and copy the link to a section from the table of content
3. open new tab and paste it in the search bar -> you should be directed to that section instead of teleporting back to the top
=> fix: prevent scrolling to top if URL contains an anchor

packages/components/src/templates/next/components/internal/BackToTopLink.tsx, packages/components/src/templates/next/components/internal/Siderail/Siderail.tsx, packages/components/src/templates/next/layouts/Content/Content.tsx
Back to top is missing when there's no siderail contents (e.g., root page, standalone page)
Closes [ISOM-2104]
Added back to top for all variants; removed hasSiderail flag
=> back to top is missing when there's no siderail contents

.github/dependabot.yml
Add cooldown period to Dependabot configuration to mitigate supply chain attacks by preventing rapid-fire dependency updates.
reference
- https://github.blog/changelog/2025-07-01-dependabot-supports-configuration-of-a-minimum-package-age/
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
Added a 7-day cooldown period to the Dependabot configuration to reduce the risk of supply chain attacks by limiting how frequently dependency updates can be created.
- Added 7-day cooldown period to Dependabot configuration
No tests required - this is a configuration-only change.
=> chore(dependabot): add cooldown period to mitigate supply chain attacks

packages/components/src/templates/next/layouts/Collection/utils/getTagFilters.ts
we already ran the migration to sort `tagCategories` alphabetically, so we should remove the sort in our codebase
remove sorting function in `getTagFilters`
=> chore: remove sorting

packages/components/src/utils/__tests__/validation.test.ts, packages/components/src/utils/validation.ts
We currently only allow normal links and mailto: links. But, while very rare, there are some sites that would benefit from having tel: and sms: protocol links.
**Features**:
- Allow tel: and sms: links as valid link href patterns.
- NOTE: Studio support is explicitly **NOT** being added as the editing experience based on the current link editor is not ideal. This change is only to unblock migrators.
=> feat: allow tel: and sms: protocols on template

apps/studio/src/features/editing-experience/__tests__/schema.test.ts, apps/studio/src/features/editing-experience/components/form-builder/renderers/controls/JsonFormsObjectControl.tsx, apps/studio/src/features/editing-experience/schema.ts, apps/studio/src/schemas/asset.ts, apps/studio/src/server/modules/asset/asset.service.ts, apps/studio/src/server/modules/permissions/permissions.type.ts
Two problems to fix in one PR:
1. We don't have a toggle right now for optional objects
2. Asset permissions is tied to resources, but there are use-cases where we need to upload assets on the root/site-wide level
**Features**:
- Add a toggle to ObjectControl if the entire object is optional.
- Allow for the case where both the pageId and linkId is missing, then default to root-level/site-wide permissions
_No tests, this is more internal, will be visible in downstream PRs (navbar/footer/site settings)_
=> feat: add toggle for optional and relax asset permissions

apps/studio/src/lib/mail.ts
postman will return 201 on successful emails, which we log errors for. this is wrong and should be fiexd
update status code to >= 300. thought about setting to >500 but i think more visibility now might still be good since postman hasn't sent over non 201/200 for now
=> chore: fix logs
